In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [120]:
input_file = 'most-recent-cohorts-all-data-elements-1.csv'
column_template = 'column_heading_template.csv'
path = './data/'
path2 = './data_documentation/'

In [104]:
df = pd.read_csv(path+input_file, low_memory=False)

In [123]:
column_heading_df = pd.read_csv(path2 + column_template)

In [124]:
column_heading_df

,dev-category,VARIABLE NAME,developer-friendly name,API data type,NAME OF DATA ELEMENT,VALUE,LABEL,SOURCE,NOTES
0,academics,MTHCMP1,program_reporter.program_1.cip_6_digit.avg_mon...,integer,Average number of months needed to complete la...,(blank),(blank),IPEDS,(blank)
1,academics,MTHCMP2,program_reporter.program_2.cip_6_digit.avg_mon...,integer,Average number of months needed to complete pr...,(blank),(blank),IPEDS,(blank)
2,academics,MTHCMP3,program_reporter.program_3.cip_6_digit.avg_mon...,integer,Average number of months needed to complete pr...,(blank),(blank),IPEDS,(blank)
3,academics,MTHCMP4,program_reporter.program_4.cip_6_digit.avg_mon...,integer,Average number of months needed to complete pr...,(blank),(blank),IPEDS,(blank)
4,academics,MTHCMP5,program_reporter.program_5.cip_6_digit.avg_mon...,integer,Average number of months needed to complete pr...,(blank),(blank),IPEDS,(blank)
...,...,...,...,...,...,...,...,...,...
597,student,UG_HISPOLD,demographics.race_ethnicity.hispanic_2000,float,Total share of enrollment of undergraduate stu...,(blank),(blank),IPEDS,Not available in all datafiles due to changing...
598,student,UG_NRA,demographics.non_resident_aliens_2000,float,Total share of enrollment of undergraduate stu...,(blank),(blank),IPEDS,Not available in all datafiles due to changing...
599,student,UG_WHITENH,demographics.race_ethnicity.white_2000,float,Total share of enrollment of undergraduate stu...,(blank),(blank),IPEDS,Not available in all datafiles due to changing...
600,student,UG_UNKN,demographics.race_ethnicity.unknown_2000,float,Total share of enrollment of undergraduate stu...,(blank),(blank),IPEDS,Not available in all datafiles due to changing...
601,student,UNEMP_RATE,demographics.unemployment,float,"Unemployment rate, via Census data",(blank),(blank),Treasury,Data element describes the earnings cohort (wi...

In [136]:
complete_variable_name_list = df.columns.to_list()
complete_variable_name_list

['UNITID',
 'OPEID',
 'OPEID6',
 'INSTNM',
 'CITY',
 'STABBR',
 'ZIP',
 'ACCREDAGENCY',
 'INSTURL',
 'NPCURL',
 'SCH_DEG',
 'HCM2',
 'MAIN',
 'NUMBRANCH',
 'PREDDEG',
 'HIGHDEG',
 'CONTROL',
 'ST_FIPS',
 'REGION',
 'LOCALE',
 'LOCALE2',
 'LATITUDE',
 'LONGITUDE',
 'CCBASIC',
 'CCUGPROF',
 'CCSIZSET',
 'HBCU',
 'PBI',
 'ANNHI',
 'TRIBAL',
 'AANAPII',
 'HSI',
 'NANTI',
 'MENONLY',
 'WOMENONLY',
 'RELAFFIL',
 'ADM_RATE',
 'ADM_RATE_ALL',
 'SATVR25',
 'SATVR75',
 'SATMT25',
 'SATMT75',
 'SATWR25',
 'SATWR75',
 'SATVRMID',
 'SATMTMID',
 'SATWRMID',
 'ACTCM25',
 'ACTCM75',
 'ACTEN25',
 'ACTEN75',
 'ACTMT25',
 'ACTMT75',
 'ACTWR25',
 'ACTWR75',
 'ACTCMMID',
 'ACTENMID',
 'ACTMTMID',
 'ACTWRMID',
 'SAT_AVG',
 'SAT_AVG_ALL',
 'PCIP01',
 'PCIP03',
 'PCIP04',
 'PCIP05',
 'PCIP09',
 'PCIP10',
 'PCIP11',
 'PCIP12',
 'PCIP13',
 'PCIP14',
 'PCIP15',
 'PCIP16',
 'PCIP19',
 'PCIP22',
 'PCIP23',
 'PCIP24',
 'PCIP25',
 'PCIP26',
 'PCIP27',
 'PCIP29',
 'PCIP30',
 'PCIP31',
 'PCIP38',
 'PCIP39',
 'PCIP40',
 'PCIP41',
 'PCIP42',
 'PCIP43',
 'PCIP44',
 'PCIP45',
 'PCIP46',
 'PCIP47',
 'PCIP48',
 'PCIP49',
 'PCIP50',
 'PCIP51',
 'PCIP52',
 'PCIP54',
 'CIP01CERT1',
 'CIP01CERT2',
 'CIP01ASSOC',
 'CIP01CERT4',
 'CIP01BACHL',
 'CIP03CERT1',
 'CIP03CERT2',
 'CIP03ASSOC',
 'CIP03CERT4',
 'CIP03BACHL',
 'CIP04CERT1',
 'CIP04CERT2',
 'CIP04ASSOC',
 'CIP04CERT4',
 'CIP04BACHL',
 'CIP05CERT1',
 'CIP05CERT2',
 'CIP05ASSOC',
 'CIP05CERT4',
 'CIP05BACHL',
 'CIP09CERT1',
 'CIP09CERT2',
 'CIP09ASSOC',
 'CIP09CERT4',
 'CIP09BACHL',
 'CIP10CERT1',
 'CIP10CERT2',
 'CIP10ASSOC',
 'CIP10CERT4',
 'CIP10BACHL',
 'CIP11CERT1',
 'CIP11CERT2',
 'CIP11ASSOC',
 'CIP11CERT4',
 'CIP11BACHL',
 'CIP12CERT1',
 'CIP12CERT2',
 'CIP12ASSOC',
 'CIP12CERT4',
 'CIP12BACHL',
 'CIP13CERT1',
 'CIP13CERT2',
 'CIP13ASSOC',
 'CIP13CERT4',
 'CIP13BACHL',
 'CIP14CERT1',
 'CIP14CERT2',
 'CIP14ASSOC',
 'CIP14CERT4',
 'CIP14BACHL',
 'CIP15CERT1',
 'CIP15CERT2',
 'CIP15ASSOC',
 'CIP15CERT4',
 'CIP15BACHL',
 'CIP16CERT1',
 'CIP16CERT2',
 'CIP16ASSOC',
 'CIP16CERT4',
 'CIP16BACHL',
 'CIP19CERT1',
 'CIP19CERT2',
 'CIP19ASSOC',
 'CIP19CERT4',
 'CIP19BACHL',
 'CIP22CERT1',
 'CIP22CERT2',
 'CIP22ASSOC',
 'CIP22CERT4',
 'CIP22BACHL',
 'CIP23CERT1',
 'CIP23CERT2',
 'CIP23ASSOC',
 'CIP23CERT4',
 'CIP23BACHL',
 'CIP24CERT1',
 'CIP24CERT2',
 'CIP24ASSOC',
 'CIP24CERT4',
 'CIP24BACHL',
 'CIP25CERT1',
 'CIP25CERT2',
 'CIP25ASSOC',
 'CIP25CERT4',
 'CIP25BACHL',
 'CIP26CERT1',
 'CIP26CERT2',
 'CIP26ASSOC',
 'CIP26CERT4',
 'CIP26BACHL',
 'CIP27CERT1',
 'CIP27CERT2',
 'CIP27ASSOC',
 'CIP27CERT4',
 'CIP27BACHL',
 'CIP29CERT1',
 'CIP29CERT2',
 'CIP29ASSOC',
 'CIP29CERT4',
 'CIP29BACHL',
 'CIP30CERT1',
 'CIP30CERT2',
 'CIP30ASSOC',
 'CIP30CERT4',
 'CIP30BACHL',
 'CIP31CERT1',
 'CIP31CERT2',
 'CIP31ASSOC',
 'CIP31CERT4',
 'CIP31BACHL',
 'CIP38CERT1',
 'CIP38CERT2',
 'CIP38ASSOC',
 'CIP38CERT4',
 'CIP38BACHL',
 'CIP39CERT1',
 'CIP39CERT2',
 'CIP39ASSOC',
 'CIP39CERT4',
 'CIP39BACHL',
 'CIP40CERT1',
 'CIP40CERT2',
 'CIP40ASSOC',
 'CIP40CERT4',
 'CIP40BACHL',
 'CIP41CERT1',
 'CIP41CERT2',
 'CIP41ASSOC',
 'CIP41CERT4',
 'CIP41BACHL',
 'CIP42CERT1',
 'CIP42CERT2',
 'CIP42ASSOC',
 'CIP42CERT4',
 'CIP42BACHL',
 'CIP43CERT1',
 'CIP43CERT2',
 'CIP43ASSOC',
 'CIP43CERT4',
 'CIP43BACHL',
 'CIP44CERT1',
 'CIP44CERT2',
 'CIP44ASSOC',
 'CIP44CERT4',
 'CIP44BACHL',
 'CIP45CERT1',
 'CIP45CERT2',
 'CIP45ASSOC',
 'CIP45CERT4',
 'CIP45BACHL',
 'CIP46CERT1',
 'CIP46CERT2',
 'CIP46ASSOC',
 'CIP46CERT4',
 'CIP46BACHL',
 'CIP47CERT1',
 'CIP47CERT2',
 'CIP47ASSOC',
 'CIP47CERT4',
 'CIP47BACHL',
 'CIP48CERT1',
 'CIP48CERT2',
 'CIP48ASSOC',
 'CIP48CERT4',
 'CIP48BACHL',
 'CIP49CERT1',
 'CIP49CERT2',
 'CIP49ASSOC',
 'CIP49CERT4',
 'CIP49BACHL',
 'CIP50CERT1',
 'CIP50CERT2',
 'CIP50ASSOC',
 'CIP50CERT4',
 'CIP50BACHL',
 'CIP51CERT1',
 'CIP51CERT2',
 'CIP51ASSOC',
 'CIP51CERT4',
 'CIP51BACHL',
 'CIP52CERT1',
 'CIP52CERT2',
 'CIP52ASSOC',
 'CIP52CERT4',
 'CIP52BACHL',
 'CIP54CERT1',
 'CIP54CERT2',
 'CIP54ASSOC',
 'CIP54CERT4',
 'CIP54BACHL',
 'DISTANCEONLY',
 'UGDS',
 'UG',
 'UGDS_WHITE',
 'UGDS_BLACK',
 'UGDS_HISP',
 'UGDS_ASIAN',
 'UGDS_AIAN',
 'UGDS_NHPI',
 'UGDS_2MOR',
 'UGDS_NRA',
 'UGDS_UNKN',
 'UGDS_WHITENH',
 'UGDS_BLACKNH',
 'UGDS_API',
 'UGDS_AIANOLD',
 'UGDS_HISPOLD',
 'UG_NRA',
 'UG_UNKN',
 'UG_WHITENH',
 'UG_BLACKNH',
 'UG_API',
 'UG_AIANOLD',
 'UG_HISPOLD',
 'PPTUG_EF',
 'PPTUG_EF2',
 'CURROPER',
 'NPT4_PUB',
 'NPT4_PRIV',
 'NPT4_PROG',
 'NPT4_OTHER',
 'NPT41_PUB',
 'NPT42_PUB',
 'NPT43_PUB',
 'NPT44_PUB',
 'NPT45_PUB',
 'NPT41_PRIV',
 'NPT42_PRIV',
 'NPT43_PRIV',
 'NPT44_PRIV',
 'NPT45_PRIV',
 'NPT41_PROG',
 'NPT42_PROG',
 'NPT43_PROG',
 'NPT44_PROG',
 'NPT45_PROG',
 'NPT41_OTHER',
 'NPT42_OTHER',
 'NPT43_OTHER',
 'NPT44_OTHER',
 'NPT45_OTHER',
 'NPT4_048_PUB',
 'NPT4_048_PRIV',
 'NPT4_048_PROG',
 'NPT4_048_OTHER',
 'NPT4_3075_PUB',
 'NPT4_3075_PRIV',
 'NPT4_75UP_PUB',
 'NPT4_75UP_PRIV',
 'NPT4_3075_PROG',
 'NPT4_3075_OTHER',
 'NPT4_75UP_PROG',
 'NPT4_75UP_OTHER',
 'NUM4_PUB',
 'NUM4_PRIV',
 'NUM4_PROG',
 'NUM4_OTHER',
 'NUM41_PUB',
 'NUM42_PUB',
 'NUM43_PUB',
 'NUM44_PUB',
 'NUM45_PUB',
 'NUM41_PRIV',
 'NUM42_PRIV',
 'NUM43_PRIV',
 'NUM44_PRIV',
 'NUM45_PRIV',
 'NUM41_PROG',
 'NUM42_PROG',
 'NUM43_PROG',
 'NUM44_PROG',
 'NUM45_PROG',
 'NUM41_OTHER',
 'NUM42_OTHER',
 'NUM43_OTHER',
 'NUM44_OTHER',
 'NUM45_OTHER',
 'COSTT4_A',
 'COSTT4_P',
 'TUITIONFEE_IN',
 'TUITIONFEE_OUT',
 'TUITIONFEE_PROG',
 'TUITFTE',
 'INEXPFTE',
 'AVGFACSAL',
 'PFTFAC',
 'PCTPELL',
 'C150_4',
 'C150_L4',
 'C150_4_POOLED',
 'C150_L4_POOLED',
 'POOLYRS',
 'PFTFTUG1_EF',
 'D150_4',
 'D150_L4',
 'D150_4_POOLED',
 'D150_L4_POOLED',
 'C150_4_WHITE',
 'C150_4_BLACK',
 'C150_4_HISP',
 'C150_4_ASIAN',
 'C150_4_AIAN',
 'C150_4_NHPI',
 'C150_4_2MOR',
 'C150_4_NRA',
 'C150_4_UNKN',
 'C150_4_WHITENH',
 'C150_4_BLACKNH',
 'C150_4_API',
 'C150_4_AIANOLD',
 'C150_4_HISPOLD',
 'C150_L4_WHITE',
 'C150_L4_BLACK',
 'C150_L4_HISP',
 'C150_L4_ASIAN',
 'C150_L4_AIAN',
 'C150_L4_NHPI',
 'C150_L4_2MOR',
 'C150_L4_NRA',
 'C150_L4_UNKN',
 'C150_L4_WHITENH',
 'C150_L4_BLACKNH',
 'C150_L4_API',
 'C150_L4_AIANOLD',
 'C150_L4_HISPOLD',
 'C200_4',
 'C200_L4',
 'D200_4',
 'D200_L4',
 'RET_FT4',
 'RET_FTL4',
 'RET_PT4',
 'RET_PTL4',
 'C200_4_POOLED',
 'C200_L4_POOLED',
 'POOLYRS200',
 'D200_4_POOLED',
 'D200_L4_POOLED',
 'PCTFLOAN',
 'UG25ABV',
 'CDR2',
 'CDR3',
 'DEATH_YR2_RT',
 'COMP_ORIG_YR2_RT',
 'COMP_4YR_TRANS_YR2_RT',
 'COMP_2YR_TRANS_YR2_RT',
 'WDRAW_ORIG_YR2_RT',
 'WDRAW_4YR_TRANS_YR2_RT',
 'WDRAW_2YR_TRANS_YR2_RT',
 'ENRL_ORIG_YR2_RT',
 'ENRL_4YR_TRANS_YR2_RT',
 'ENRL_2YR_TRANS_YR2_RT',
 'UNKN_ORIG_YR2_RT',
 'UNKN_4YR_TRANS_YR2_RT',
 'UNKN_2YR_TRANS_YR2_RT',
 'LO_INC_DEATH_YR2_RT',
 'LO_INC_COMP_ORIG_YR2_RT',
 'LO_INC_COMP_4YR_TRANS_YR2_RT',
 'LO_INC_COMP_2YR_TRANS_YR2_RT',
 'LO_INC_WDRAW_ORIG_YR2_RT',
 'LO_INC_WDRAW_4YR_TRANS_YR2_RT',
 'LO_INC_WDRAW_2YR_TRANS_YR2_RT',
 'LO_INC_ENRL_ORIG_YR2_RT',
 'LO_INC_ENRL_4YR_TRANS_YR2_RT',
 'LO_INC_ENRL_2YR_TRANS_YR2_RT',
 'LO_INC_UNKN_ORIG_YR2_RT',
 'LO_INC_UNKN_4YR_TRANS_YR2_RT',
 'LO_INC_UNKN_2YR_TRANS_YR2_RT',
 'MD_INC_DEATH_YR2_RT',
 'MD_INC_COMP_ORIG_YR2_RT',
 'MD_INC_COMP_4YR_TRANS_YR2_RT',
 'MD_INC_COMP_2YR_TRANS_YR2_RT',
 'MD_INC_WDRAW_ORIG_YR2_RT',
 'MD_INC_WDRAW_4YR_TRANS_YR2_RT',
 'MD_INC_WDRAW_2YR_TRANS_YR2_RT',
 'MD_INC_ENRL_ORIG_YR2_RT',
 'MD_INC_ENRL_4YR_TRANS_YR2_RT',
 'MD_INC_ENRL_2YR_TRANS_YR2_RT',
 'MD_INC_UNKN_ORIG_YR2_RT',
 'MD_INC_UNKN_4YR_TRANS_YR2_RT',
 'MD_INC_UNKN_2YR_TRANS_YR2_RT',
 'HI_INC_DEATH_YR2_RT',
 'HI_INC_COMP_ORIG_YR2_RT',
 'HI_INC_COMP_4YR_TRANS_YR2_RT',
 'HI_INC_COMP_2YR_TRANS_YR2_RT',
 'HI_INC_WDRAW_ORIG_YR2_RT',
 'HI_INC_WDRAW_4YR_TRANS_YR2_RT',
 'HI_INC_WDRAW_2YR_TRANS_YR2_RT',
 'HI_INC_ENRL_ORIG_YR2_RT',
 'HI_INC_ENRL_4YR_TRANS_YR2_RT',
 'HI_INC_ENRL_2YR_TRANS_YR2_RT',
 'HI_INC_UNKN_ORIG_YR2_RT',
 'HI_INC_UNKN_4YR_TRANS_YR2_RT',
 'HI_INC_UNKN_2YR_TRANS_YR2_RT',
 'DEP_DEATH_YR2_RT',
 'DEP_COMP_ORIG_YR2_RT',
 'DEP_COMP_4YR_TRANS_YR2_RT',
 'DEP_COMP_2YR_TRANS_YR2_RT',
 'DEP_WDRAW_ORIG_YR2_RT',
 'DEP_WDRAW_4YR_TRANS_YR2_RT',
 'DEP_WDRAW_2YR_TRANS_YR2_RT',
 'DEP_ENRL_ORIG_YR2_RT',
 'DEP_ENRL_4YR_TRANS_YR2_RT',
 'DEP_ENRL_2YR_TRANS_YR2_RT',
 'DEP_UNKN_ORIG_YR2_RT',
 'DEP_UNKN_4YR_TRANS_YR2_RT',
 'DEP_UNKN_2YR_TRANS_YR2_RT',
 'IND_DEATH_YR2_RT',
 'IND_COMP_ORIG_YR2_RT',
 'IND_COMP_4YR_TRANS_YR2_RT',
 'IND_COMP_2YR_TRANS_YR2_RT',
 'IND_WDRAW_ORIG_YR2_RT',
 'IND_WDRAW_4YR_TRANS_YR2_RT',
 'IND_WDRAW_2YR_TRANS_YR2_RT',
 'IND_ENRL_ORIG_YR2_RT',
 'IND_ENRL_4YR_TRANS_YR2_RT',
 'IND_ENRL_2YR_TRANS_YR2_RT',
 'IND_UNKN_ORIG_YR2_RT',
 'IND_UNKN_4YR_TRANS_YR2_RT',
 'IND_UNKN_2YR_TRANS_YR2_RT',
 'FEMALE_DEATH_YR2_RT',
 'FEMALE_COMP_ORIG_YR2_RT',
 'FEMALE_COMP_4YR_TRANS_YR2_RT',
 'FEMALE_COMP_2YR_TRANS_YR2_RT',
 'FEMALE_WDRAW_ORIG_YR2_RT',
 'FEMALE_WDRAW_4YR_TRANS_YR2_RT',
 'FEMALE_WDRAW_2YR_TRANS_YR2_RT',
 'FEMALE_ENRL_ORIG_YR2_RT',
 'FEMALE_ENRL_4YR_TRANS_YR2_RT',
 'FEMALE_ENRL_2YR_TRANS_YR2_RT',
 'FEMALE_UNKN_ORIG_YR2_RT',
 'FEMALE_UNKN_4YR_TRANS_YR2_RT',
 'FEMALE_UNKN_2YR_TRANS_YR2_RT',
 'MALE_DEATH_YR2_RT',
 'MALE_COMP_ORIG_YR2_RT',
 'MALE_COMP_4YR_TRANS_YR2_RT',
 'MALE_COMP_2YR_TRANS_YR2_RT',
 'MALE_WDRAW_ORIG_YR2_RT',
 'MALE_WDRAW_4YR_TRANS_YR2_RT',
 'MALE_WDRAW_2YR_TRANS_YR2_RT',
 'MALE_ENRL_ORIG_YR2_RT',
 'MALE_ENRL_4YR_TRANS_YR2_RT',
 'MALE_ENRL_2YR_TRANS_YR2_RT',
 'MALE_UNKN_ORIG_YR2_RT',
 'MALE_UNKN_4YR_TRANS_YR2_RT',
 'MALE_UNKN_2YR_TRANS_YR2_RT',
 'PELL_DEATH_YR2_RT',
 'PELL_COMP_ORIG_YR2_RT',
 'PELL_COMP_4YR_TRANS_YR2_RT',
 'PELL_COMP_2YR_TRANS_YR2_RT',
 'PELL_WDRAW_ORIG_YR2_RT',
 'PELL_WDRAW_4YR_TRANS_YR2_RT',
 'PELL_WDRAW_2YR_TRANS_YR2_RT',
 'PELL_ENRL_ORIG_YR2_RT',
 'PELL_ENRL_4YR_TRANS_YR2_RT',
 'PELL_ENRL_2YR_TRANS_YR2_RT',
 'PELL_UNKN_ORIG_YR2_RT',
 'PELL_UNKN_4YR_TRANS_YR2_RT',
 'PELL_UNKN_2YR_TRANS_YR2_RT',
 'NOPELL_DEATH_YR2_RT',
 'NOPELL_COMP_ORIG_YR2_RT',
 'NOPELL_COMP_4YR_TRANS_YR2_RT',
 'NOPELL_COMP_2YR_TRANS_YR2_RT',
 'NOPELL_WDRAW_ORIG_YR2_RT',
 'NOPELL_WDRAW_4YR_TRANS_YR2_RT',
 'NOPELL_WDRAW_2YR_TRANS_YR2_RT',
 'NOPELL_ENRL_ORIG_YR2_RT',
 'NOPELL_ENRL_4YR_TRANS_YR2_RT',
 'NOPELL_ENRL_2YR_TRANS_YR2_RT',
 'NOPELL_UNKN_ORIG_YR2_RT',
 'NOPELL_UNKN_4YR_TRANS_YR2_RT',
 'NOPELL_UNKN_2YR_TRANS_YR2_RT',
 'LOAN_DEATH_YR2_RT',
 'LOAN_COMP_ORIG_YR2_RT',
 'LOAN_COMP_4YR_TRANS_YR2_RT',
 'LOAN_COMP_2YR_TRANS_YR2_RT',
 'LOAN_WDRAW_ORIG_YR2_RT',
 'LOAN_WDRAW_4YR_TRANS_YR2_RT',
 'LOAN_WDRAW_2YR_TRANS_YR2_RT',
 'LOAN_ENRL_ORIG_YR2_RT',
 'LOAN_ENRL_4YR_TRANS_YR2_RT',
 'LOAN_ENRL_2YR_TRANS_YR2_RT',
 'LOAN_UNKN_ORIG_YR2_RT',
 'LOAN_UNKN_4YR_TRANS_YR2_RT',
 'LOAN_UNKN_2YR_TRANS_YR2_RT',
 'NOLOAN_DEATH_YR2_RT',
 'NOLOAN_COMP_ORIG_YR2_RT',
 'NOLOAN_COMP_4YR_TRANS_YR2_RT',
 'NOLOAN_COMP_2YR_TRANS_YR2_RT',
 'NOLOAN_WDRAW_ORIG_YR2_RT',
 'NOLOAN_WDRAW_4YR_TRANS_YR2_RT',
 'NOLOAN_WDRAW_2YR_TRANS_YR2_RT',
 'NOLOAN_ENRL_ORIG_YR2_RT',
 'NOLOAN_ENRL_4YR_TRANS_YR2_RT',
 'NOLOAN_ENRL_2YR_TRANS_YR2_RT',
 'NOLOAN_UNKN_ORIG_YR2_RT',
 'NOLOAN_UNKN_4YR_TRANS_YR2_RT',
 'NOLOAN_UNKN_2YR_TRANS_YR2_RT',
 'FIRSTGEN_DEATH_YR2_RT',
 'FIRSTGEN_COMP_ORIG_YR2_RT',
 'FIRSTGEN_COMP_4YR_TRANS_YR2_RT',
 'FIRSTGEN_COMP_2YR_TRANS_YR2_RT',
 'FIRSTGEN_WDRAW_ORIG_YR2_RT',
 'FIRSTGEN_WDRAW_4YR_TRANS_YR2_RT',
 'FIRSTGEN_WDRAW_2YR_TRANS_YR2_RT',
 'FIRSTGEN_ENRL_ORIG_YR2_RT',
 'FIRSTGEN_ENRL_4YR_TRANS_YR2_RT',
 'FIRSTGEN_ENRL_2YR_TRANS_YR2_RT',
 'FIRSTGEN_UNKN_ORIG_YR2_RT',
 'FIRSTGEN_UNKN_4YR_TRANS_YR2_RT',
 'FIRSTGEN_UNKN_2YR_TRANS_YR2_RT',
 'NOT1STGEN_DEATH_YR2_RT',
 'NOT1STGEN_COMP_ORIG_YR2_RT',
 'NOT1STGEN_COMP_4YR_TRANS_YR2_RT',
 'NOT1STGEN_COMP_2YR_TRANS_YR2_RT',
 'NOT1STGEN_WDRAW_ORIG_YR2_RT',
 'NOT1STGEN_WDRAW_4YR_TRANS_YR2_RT',
 'NOT1STGEN_WDRAW_2YR_TRANS_YR2_RT',
 'NOT1STGEN_ENRL_ORIG_YR2_RT',
 'NOT1STGEN_ENRL_4YR_TRANS_YR2_RT',
 'NOT1STGEN_ENRL_2YR_TRANS_YR2_RT',
 'NOT1STGEN_UNKN_ORIG_YR2_RT',
 'NOT1STGEN_UNKN_4YR_TRANS_YR2_RT',
 'NOT1STGEN_UNKN_2YR_TRANS_YR2_RT',
 'DEATH_YR3_RT',
 'COMP_ORIG_YR3_RT',
 'COMP_4YR_TRANS_YR3_RT',
 'COMP_2YR_TRANS_YR3_RT',
 'WDRAW_ORIG_YR3_RT',
 'WDRAW_4YR_TRANS_YR3_RT',
 'WDRAW_2YR_TRANS_YR3_RT',
 'ENRL_ORIG_YR3_RT',
 'ENRL_4YR_TRANS_YR3_RT',
 'ENRL_2YR_TRANS_YR3_RT',
 'UNKN_ORIG_YR3_RT',
 'UNKN_4YR_TRANS_YR3_RT',
 'UNKN_2YR_TRANS_YR3_RT',
 'LO_INC_DEATH_YR3_RT',
 'LO_INC_COMP_ORIG_YR3_RT',
 'LO_INC_COMP_4YR_TRANS_YR3_RT',
 'LO_INC_COMP_2YR_TRANS_YR3_RT',
 'LO_INC_WDRAW_ORIG_YR3_RT',
 'LO_INC_WDRAW_4YR_TRANS_YR3_RT',
 'LO_INC_WDRAW_2YR_TRANS_YR3_RT',
 'LO_INC_ENRL_ORIG_YR3_RT',
 'LO_INC_ENRL_4YR_TRANS_YR3_RT',
 'LO_INC_ENRL_2YR_TRANS_YR3_RT',
 'LO_INC_UNKN_ORIG_YR3_RT',
 'LO_INC_UNKN_4YR_TRANS_YR3_RT',
 'LO_INC_UNKN_2YR_TRANS_YR3_RT',
 'MD_INC_DEATH_YR3_RT',
 'MD_INC_COMP_ORIG_YR3_RT',
 'MD_INC_COMP_4YR_TRANS_YR3_RT',
 'MD_INC_COMP_2YR_TRANS_YR3_RT',
 'MD_INC_WDRAW_ORIG_YR3_RT',
 'MD_INC_WDRAW_4YR_TRANS_YR3_RT',
 'MD_INC_WDRAW_2YR_TRANS_YR3_RT',
 'MD_INC_ENRL_ORIG_YR3_RT',
 'MD_INC_ENRL_4YR_TRANS_YR3_RT',
 'MD_INC_ENRL_2YR_TRANS_YR3_RT',
 'MD_INC_UNKN_ORIG_YR3_RT',
 'MD_INC_UNKN_4YR_TRANS_YR3_RT',
 'MD_INC_UNKN_2YR_TRANS_YR3_RT',
 'HI_INC_DEATH_YR3_RT',
 'HI_INC_COMP_ORIG_YR3_RT',
 'HI_INC_COMP_4YR_TRANS_YR3_RT',
 'HI_INC_COMP_2YR_TRANS_YR3_RT',
 'HI_INC_WDRAW_ORIG_YR3_RT',
 'HI_INC_WDRAW_4YR_TRANS_YR3_RT',
 'HI_INC_WDRAW_2YR_TRANS_YR3_RT',
 'HI_INC_ENRL_ORIG_YR3_RT',
 'HI_INC_ENRL_4YR_TRANS_YR3_RT',
 'HI_INC_ENRL_2YR_TRANS_YR3_RT',
 'HI_INC_UNKN_ORIG_YR3_RT',
 'HI_INC_UNKN_4YR_TRANS_YR3_RT',
 'HI_INC_UNKN_2YR_TRANS_YR3_RT',
 'DEP_DEATH_YR3_RT',
 'DEP_COMP_ORIG_YR3_RT',
 'DEP_COMP_4YR_TRANS_YR3_RT',
 'DEP_COMP_2YR_TRANS_YR3_RT',
 'DEP_WDRAW_ORIG_YR3_RT',
 'DEP_WDRAW_4YR_TRANS_YR3_RT',
 'DEP_WDRAW_2YR_TRANS_YR3_RT',
 'DEP_ENRL_ORIG_YR3_RT',
 'DEP_ENRL_4YR_TRANS_YR3_RT',
 'DEP_ENRL_2YR_TRANS_YR3_RT',
 'DEP_UNKN_ORIG_YR3_RT',
 'DEP_UNKN_4YR_TRANS_YR3_RT',
 'DEP_UNKN_2YR_TRANS_YR3_RT',
 'IND_DEATH_YR3_RT',
 'IND_COMP_ORIG_YR3_RT',
 'IND_COMP_4YR_TRANS_YR3_RT',
 'IND_COMP_2YR_TRANS_YR3_RT',
 'IND_WDRAW_ORIG_YR3_RT',
 'IND_WDRAW_4YR_TRANS_YR3_RT',
 'IND_WDRAW_2YR_TRANS_YR3_RT',
 'IND_ENRL_ORIG_YR3_RT',
 'IND_ENRL_4YR_TRANS_YR3_RT',
 'IND_ENRL_2YR_TRANS_YR3_RT',
 'IND_UNKN_ORIG_YR3_RT',
 'IND_UNKN_4YR_TRANS_YR3_RT',
 'IND_UNKN_2YR_TRANS_YR3_RT',
 'FEMALE_DEATH_YR3_RT',
 'FEMALE_COMP_ORIG_YR3_RT',
 'FEMALE_COMP_4YR_TRANS_YR3_RT',
 'FEMALE_COMP_2YR_TRANS_YR3_RT',
 'FEMALE_WDRAW_ORIG_YR3_RT',
 'FEMALE_WDRAW_4YR_TRANS_YR3_RT',
 'FEMALE_WDRAW_2YR_TRANS_YR3_RT',
 'FEMALE_ENRL_ORIG_YR3_RT',
 'FEMALE_ENRL_4YR_TRANS_YR3_RT',
 'FEMALE_ENRL_2YR_TRANS_YR3_RT',
 'FEMALE_UNKN_ORIG_YR3_RT',
 'FEMALE_UNKN_4YR_TRANS_YR3_RT',
 'FEMALE_UNKN_2YR_TRANS_YR3_RT',
 'MALE_DEATH_YR3_RT',
 'MALE_COMP_ORIG_YR3_RT',
 'MALE_COMP_4YR_TRANS_YR3_RT',
 'MALE_COMP_2YR_TRANS_YR3_RT',
 'MALE_WDRAW_ORIG_YR3_RT',
 'MALE_WDRAW_4YR_TRANS_YR3_RT',
 'MALE_WDRAW_2YR_TRANS_YR3_RT',
 'MALE_ENRL_ORIG_YR3_RT',
 'MALE_ENRL_4YR_TRANS_YR3_RT',
 'MALE_ENRL_2YR_TRANS_YR3_RT',
 'MALE_UNKN_ORIG_YR3_RT',
 'MALE_UNKN_4YR_TRANS_YR3_RT',
 'MALE_UNKN_2YR_TRANS_YR3_RT',
 'PELL_DEATH_YR3_RT',
 'PELL_COMP_ORIG_YR3_RT',
 'PELL_COMP_4YR_TRANS_YR3_RT',
 'PELL_COMP_2YR_TRANS_YR3_RT',
 'PELL_WDRAW_ORIG_YR3_RT',
 'PELL_WDRAW_4YR_TRANS_YR3_RT',
 'PELL_WDRAW_2YR_TRANS_YR3_RT',
 'PELL_ENRL_ORIG_YR3_RT',
 'PELL_ENRL_4YR_TRANS_YR3_RT',
 'PELL_ENRL_2YR_TRANS_YR3_RT',
 'PELL_UNKN_ORIG_YR3_RT',
 'PELL_UNKN_4YR_TRANS_YR3_RT',
 'PELL_UNKN_2YR_TRANS_YR3_RT',
 'NOPELL_DEATH_YR3_RT',
 'NOPELL_COMP_ORIG_YR3_RT',
 'NOPELL_COMP_4YR_TRANS_YR3_RT',
 'NOPELL_COMP_2YR_TRANS_YR3_RT',
 'NOPELL_WDRAW_ORIG_YR3_RT',
 'NOPELL_WDRAW_4YR_TRANS_YR3_RT',
 'NOPELL_WDRAW_2YR_TRANS_YR3_RT',
 'NOPELL_ENRL_ORIG_YR3_RT',
 'NOPELL_ENRL_4YR_TRANS_YR3_RT',
 'NOPELL_ENRL_2YR_TRANS_YR3_RT',
 'NOPELL_UNKN_ORIG_YR3_RT',
 'NOPELL_UNKN_4YR_TRANS_YR3_RT',
 'NOPELL_UNKN_2YR_TRANS_YR3_RT',
 'LOAN_DEATH_YR3_RT',
 'LOAN_COMP_ORIG_YR3_RT',
 'LOAN_COMP_4YR_TRANS_YR3_RT',
 'LOAN_COMP_2YR_TRANS_YR3_RT',
 'LOAN_WDRAW_ORIG_YR3_RT',
 'LOAN_WDRAW_4YR_TRANS_YR3_RT',
 'LOAN_WDRAW_2YR_TRANS_YR3_RT',
 'LOAN_ENRL_ORIG_YR3_RT',
 'LOAN_ENRL_4YR_TRANS_YR3_RT',
 'LOAN_ENRL_2YR_TRANS_YR3_RT',
 'LOAN_UNKN_ORIG_YR3_RT',
 'LOAN_UNKN_4YR_TRANS_YR3_RT',
 'LOAN_UNKN_2YR_TRANS_YR3_RT',
 'NOLOAN_DEATH_YR3_RT',
 'NOLOAN_COMP_ORIG_YR3_RT',
 'NOLOAN_COMP_4YR_TRANS_YR3_RT',
 'NOLOAN_COMP_2YR_TRANS_YR3_RT',
 'NOLOAN_WDRAW_ORIG_YR3_RT',
 'NOLOAN_WDRAW_4YR_TRANS_YR3_RT',
 'NOLOAN_WDRAW_2YR_TRANS_YR3_RT',
 'NOLOAN_ENRL_ORIG_YR3_RT',
 'NOLOAN_ENRL_4YR_TRANS_YR3_RT',
 'NOLOAN_ENRL_2YR_TRANS_YR3_RT',
 'NOLOAN_UNKN_ORIG_YR3_RT',
 'NOLOAN_UNKN_4YR_TRANS_YR3_RT',
 'NOLOAN_UNKN_2YR_TRANS_YR3_RT',
 'FIRSTGEN_DEATH_YR3_RT',
 'FIRSTGEN_COMP_ORIG_YR3_RT',
 'FIRSTGEN_COMP_4YR_TRANS_YR3_RT',
 'FIRSTGEN_COMP_2YR_TRANS_YR3_RT',
 'FIRSTGEN_WDRAW_ORIG_YR3_RT',
 'FIRSTGEN_WDRAW_4YR_TRANS_YR3_RT',
 'FIRSTGEN_WDRAW_2YR_TRANS_YR3_RT',
 'FIRSTGEN_ENRL_ORIG_YR3_RT',
 'FIRSTGEN_ENRL_4YR_TRANS_YR3_RT',
 'FIRSTGEN_ENRL_2YR_TRANS_YR3_RT',
 'FIRSTGEN_UNKN_ORIG_YR3_RT',
 'FIRSTGEN_UNKN_4YR_TRANS_YR3_RT',
 'FIRSTGEN_UNKN_2YR_TRANS_YR3_RT',
 'NOT1STGEN_DEATH_YR3_RT',
 'NOT1STGEN_COMP_ORIG_YR3_RT',
 'NOT1STGEN_COMP_4YR_TRANS_YR3_RT',
 'NOT1STGEN_COMP_2YR_TRANS_YR3_RT',
 'NOT1STGEN_WDRAW_ORIG_YR3_RT',
 'NOT1STGEN_WDRAW_4YR_TRANS_YR3_RT',
 'NOT1STGEN_WDRAW_2YR_TRANS_YR3_RT',
 'NOT1STGEN_ENRL_ORIG_YR3_RT',
 'NOT1STGEN_ENRL_4YR_TRANS_YR3_RT',
 'NOT1STGEN_ENRL_2YR_TRANS_YR3_RT',
 'NOT1STGEN_UNKN_ORIG_YR3_RT',
 'NOT1STGEN_UNKN_4YR_TRANS_YR3_RT',
 'NOT1STGEN_UNKN_2YR_TRANS_YR3_RT',
 'DEATH_YR4_RT',
 'COMP_ORIG_YR4_RT',
 'COMP_4YR_TRANS_YR4_RT',
 'COMP_2YR_TRANS_YR4_RT',
 'WDRAW_ORIG_YR4_RT',
 'WDRAW_4YR_TRANS_YR4_RT',
 'WDRAW_2YR_TRANS_YR4_RT',
 'ENRL_ORIG_YR4_RT',
 'ENRL_4YR_TRANS_YR4_RT',
 'ENRL_2YR_TRANS_YR4_RT',
 'UNKN_ORIG_YR4_RT',
 'UNKN_4YR_TRANS_YR4_RT',
 'UNKN_2YR_TRANS_YR4_RT',
 'LO_INC_DEATH_YR4_RT',
 'LO_INC_COMP_ORIG_YR4_RT',
 'LO_INC_COMP_4YR_TRANS_YR4_RT',
 'LO_INC_COMP_2YR_TRANS_YR4_RT',
 'LO_INC_WDRAW_ORIG_YR4_RT',
 'LO_INC_WDRAW_4YR_TRANS_YR4_RT',
 'LO_INC_WDRAW_2YR_TRANS_YR4_RT',
 'LO_INC_ENRL_ORIG_YR4_RT',
 'LO_INC_ENRL_4YR_TRANS_YR4_RT',
 'LO_INC_ENRL_2YR_TRANS_YR4_RT',
 'LO_INC_UNKN_ORIG_YR4_RT',
 'LO_INC_UNKN_4YR_TRANS_YR4_RT',
 'LO_INC_UNKN_2YR_TRANS_YR4_RT',
 'MD_INC_DEATH_YR4_RT',
 'MD_INC_COMP_ORIG_YR4_RT',
 'MD_INC_COMP_4YR_TRANS_YR4_RT',
 'MD_INC_COMP_2YR_TRANS_YR4_RT',
 'MD_INC_WDRAW_ORIG_YR4_RT',
 'MD_INC_WDRAW_4YR_TRANS_YR4_RT',
 'MD_INC_WDRAW_2YR_TRANS_YR4_RT',
 'MD_INC_ENRL_ORIG_YR4_RT',
 'MD_INC_ENRL_4YR_TRANS_YR4_RT',
 'MD_INC_ENRL_2YR_TRANS_YR4_RT',
 'MD_INC_UNKN_ORIG_YR4_RT',
 'MD_INC_UNKN_4YR_TRANS_YR4_RT',
 'MD_INC_UNKN_2YR_TRANS_YR4_RT',
 'HI_INC_DEATH_YR4_RT',
 'HI_INC_COMP_ORIG_YR4_RT',
 'HI_INC_COMP_4YR_TRANS_YR4_RT',
 'HI_INC_COMP_2YR_TRANS_YR4_RT',
 'HI_INC_WDRAW_ORIG_YR4_RT',
 'HI_INC_WDRAW_4YR_TRANS_YR4_RT',
 'HI_INC_WDRAW_2YR_TRANS_YR4_RT',
 'HI_INC_ENRL_ORIG_YR4_RT',
 'HI_INC_ENRL_4YR_TRANS_YR4_RT',
 'HI_INC_ENRL_2YR_TRANS_YR4_RT',
 'HI_INC_UNKN_ORIG_YR4_RT',
 'HI_INC_UNKN_4YR_TRANS_YR4_RT',
 'HI_INC_UNKN_2YR_TRANS_YR4_RT',
 'DEP_DEATH_YR4_RT',
 'DEP_COMP_ORIG_YR4_RT',
 'DEP_COMP_4YR_TRANS_YR4_RT',
 'DEP_COMP_2YR_TRANS_YR4_RT',
 'DEP_WDRAW_ORIG_YR4_RT',
 'DEP_WDRAW_4YR_TRANS_YR4_RT',
 'DEP_WDRAW_2YR_TRANS_YR4_RT',
 'DEP_ENRL_ORIG_YR4_RT',
 'DEP_ENRL_4YR_TRANS_YR4_RT',
 'DEP_ENRL_2YR_TRANS_YR4_RT',
 'DEP_UNKN_ORIG_YR4_RT',
 'DEP_UNKN_4YR_TRANS_YR4_RT',
 'DEP_UNKN_2YR_TRANS_YR4_RT',
 'IND_DEATH_YR4_RT',
 'IND_COMP_ORIG_YR4_RT',
 'IND_COMP_4YR_TRANS_YR4_RT',
 'IND_COMP_2YR_TRANS_YR4_RT',
 'IND_WDRAW_ORIG_YR4_RT',
 'IND_WDRAW_4YR_TRANS_YR4_RT',
 'IND_WDRAW_2YR_TRANS_YR4_RT',
 'IND_ENRL_ORIG_YR4_RT',
 'IND_ENRL_4YR_TRANS_YR4_RT',
 'IND_ENRL_2YR_TRANS_YR4_RT',
 'IND_UNKN_ORIG_YR4_RT',
 'IND_UNKN_4YR_TRANS_YR4_RT',
 'IND_UNKN_2YR_TRANS_YR4_RT',
 'FEMALE_DEATH_YR4_RT',
 'FEMALE_COMP_ORIG_YR4_RT',
 'FEMALE_COMP_4YR_TRANS_YR4_RT',
 'FEMALE_COMP_2YR_TRANS_YR4_RT',
 'FEMALE_WDRAW_ORIG_YR4_RT',
 'FEMALE_WDRAW_4YR_TRANS_YR4_RT',
 'FEMALE_WDRAW_2YR_TRANS_YR4_RT',
 'FEMALE_ENRL_ORIG_YR4_RT',
 'FEMALE_ENRL_4YR_TRANS_YR4_RT',
 'FEMALE_ENRL_2YR_TRANS_YR4_RT',
 'FEMALE_UNKN_ORIG_YR4_RT',
 'FEMALE_UNKN_4YR_TRANS_YR4_RT',
 'FEMALE_UNKN_2YR_TRANS_YR4_RT',
 'MALE_DEATH_YR4_RT',
 'MALE_COMP_ORIG_YR4_RT',
 'MALE_COMP_4YR_TRANS_YR4_RT',
 'MALE_COMP_2YR_TRANS_YR4_RT',

In [143]:
filtered_variable_name_list = column_heading_df['VARIABLE NAME'].unique().tolist()
filtered_variable_name_list

['MTHCMP1',
 'MTHCMP2',
 'MTHCMP3',
 'MTHCMP4',
 'MTHCMP5',
 'MTHCMP6',
 'CIP01BACHL',
 'CIP04BACHL',
 'CIP05BACHL',
 'CIP26BACHL',
 'CIP52BACHL',
 'CIP09BACHL',
 'CIP10BACHL',
 'CIP11BACHL',
 'CIP46BACHL',
 'CIP13BACHL',
 'CIP15BACHL',
 'CIP14BACHL',
 'CIP23BACHL',
 'CIP19BACHL',
 'CIP16BACHL',
 'CIP51BACHL',
 'CIP54BACHL',
 'CIP43BACHL',
 'CIP22BACHL',
 'CIP24BACHL',
 'CIP25BACHL',
 'CIP27BACHL',
 'CIP47BACHL',
 'CIP29BACHL',
 'CIP30BACHL',
 'CIP03BACHL',
 'CIP31BACHL',
 'CIP12BACHL',
 'CIP38BACHL',
 'CIP40BACHL',
 'CIP48BACHL',
 'CIP42BACHL',
 'CIP44BACHL',
 'CIP41BACHL',
 'CIP45BACHL',
 'CIP39BACHL',
 'CIP49BACHL',
 'CIP50BACHL',
 'CIPCODE1',
 'CIPCODE2',
 'CIPCODE3',
 'CIPCODE4',
 'CIPCODE5',
 'CIPCODE6',
 'CIPTITLE1',
 'CIPTITLE2',
 'CIPTITLE3',
 'CIPTITLE4',
 'CIPTITLE5',
 'CIPTITLE6',
 'PRGMOFR',
 'PCIP01',
 'PCIP04',
 'PCIP05',
 'PCIP26',
 'PCIP52',
 'PCIP09',
 'PCIP10',
 'PCIP11',
 'PCIP46',
 'PCIP13',
 'PCIP15',
 'PCIP14',
 'PCIP23',
 'PCIP19',
 'PCIP16',
 'PCIP51',
 'PCIP54',
 'PCIP43',
 'PCIP22',
 'PCIP24',
 'PCIP25',
 'PCIP27',
 'PCIP47',
 'PCIP29',
 'PCIP30',
 'PCIP03',
 'PCIP31',
 'PCIP12',
 'PCIP38',
 'PCIP40',
 'PCIP48',
 'PCIP42',
 'PCIP44',
 'PCIP41',
 'PCIP45',
 'PCIP39',
 'PCIP49',
 'PCIP50',
 'SATVR25',
 'SATMT25',
 'SATWR25',
 'ACTCM25',
 'ACTEN25',
 'ACTMT25',
 'ACTWR25',
 'SATVR75',
 'SATMT75',
 'SATWR75',
 'ACTCM75',
 'ACTEN75',
 'ACTMT75',
 'ACTWR75',
 'ADM_RATE',
 'ADM_RATE_ALL',
 'SAT_AVG',
 'SAT_AVG_ALL',
 'SATVRMID',
 'SATMTMID',
 'SATWRMID',
 'ACTCMMID',
 'ACTENMID',
 'ACTMTMID',
 'ACTWRMID',
 'CUML_DEBT_P10',
 'CUML_DEBT_P25',
 'CUML_DEBT_P75',
 'CUML_DEBT_P90',
 'GRAD_DEBT_MDN10YR_SUPP',
 'GRAD_DEBT_MDN_SUPP',
 'DEBT_MDN_SUPP',
 'GRAD_DEBT_MDN10YR',
 'CUML_DEBT_N',
 'PCTFLOAN',
 'FTFTPCTFLOAN_POOLED_SUPP',
 'FTFTPCTPELL_POOLED_SUPP',
 'LOAN_EVER',
 'DEP_DEBT_MDN',
 'FEMALE_DEBT_MDN',
 'FIRSTGEN_DEBT_MDN',
 'IND_DEBT_MDN',
 'MALE_DEBT_MDN',
 'NOPELL_DEBT_MDN',
 'NOTFIRSTGEN_DEBT_MDN',
 'PELL_DEBT_MDN',
 'GRAD_DEBT_MDN',
 'WDRAW_DEBT_MDN',
 'HI_INC_DEBT_MDN',
 'LO_INC_DEBT_MDN',
 'MD_INC_DEBT_MDN',
 'DEBT_MDN',
 'DEBT_N',
 'GRAD_DEBT_N',
 'DEP_DEBT_N',
 'FEMALE_DEBT_N',
 'FIRSTGEN_DEBT_N',
 'HI_INC_DEBT_N',
 'IND_DEBT_N',
 'LO_INC_DEBT_N',
 'MALE_DEBT_N',
 'MD_INC_DEBT_N',
 'NOPELL_DEBT_N',
 'NOTFIRSTGEN_DEBT_N',
 'PELL_DEBT_N',
 'WDRAW_DEBT_N',
 'C200_4',
 'C150_4',
 'C150_4_AIAN',
 'C150_4_AIANOLD',
 'C150_4_ASIAN',
 'C150_4_API',
 'C150_4_BLACK',
 'C150_4_BLACKNH',
 'C150_4_HISP',
 'C150_4_HISPOLD',
 'C150_4_NHPI',
 'C150_4_NRA',
 'C150_4_2MOR',
 'C150_4_UNKN',
 'C150_4_WHITE',
 'C150_4_WHITENH',
 'C150_4_POOLED',
 'C150_L4_AIAN',
 'C150_L4_AIANOLD',
 'C150_L4_ASIAN',
 'C150_L4_API',
 'C150_L4_BLACKNH',
 'C150_L4_BLACK',
 'C150_L4_HISP',
 'C150_L4_HISPOLD',
 'C150_L4_NHPI',
 'C150_L4_NRA',
 'C150_L4_2MOR',
 'C150_L4_UNKN',
 'C150_L4_WHITENH',
 'C150_L4_WHITE',
 'C200_L4',
 'DEP_YR4_N',
 'DEP_YR6_N',
 'FEMALE_YR4_N',
 'FEMALE_YR6_N',
 'FIRSTGEN_YR4_N',
 'FIRSTGEN_YR6_N',
 'HI_INC_YR4_N',
 'HI_INC_YR6_N',
 'IND_YR4_N',
 'IND_YR6_N',
 'LOAN_YR4_N',
 'LOAN_YR6_N',
 'LO_INC_YR4_N',
 'LO_INC_YR6_N',
 'MALE_YR4_N',
 'MALE_YR6_N',
 'MD_INC_YR4_N',
 'MD_INC_YR6_N',
 'NOLOAN_YR4_N',
 'NOLOAN_YR6_N',
 'NOPELL_YR4_N',
 'NOPELL_YR6_N',
 'NOT1STGEN_YR4_N',
 'NOT1STGEN_YR6_N',
 'PELL_YR4_N',
 'PELL_YR6_N',
 'OVERALL_YR4_N',
 'OVERALL_YR6_N',
 'HI_INC_COMP_ORIG_YR4_RT',
 'HI_INC_COMP_ORIG_YR6_RT',
 'HI_INC_DEATH_YR4_RT',
 'HI_INC_DEATH_YR6_RT',
 'HI_INC_COMP_2YR_TRANS_YR4_RT',
 'HI_INC_COMP_2YR_TRANS_YR6_RT',
 'HI_INC_ENRL_2YR_TRANS_YR4_RT',
 'HI_INC_ENRL_2YR_TRANS_YR6_RT',
 'HI_INC_UNKN_2YR_TRANS_YR4_RT',
 'HI_INC_UNKN_2YR_TRANS_YR6_RT',
 'HI_INC_WDRAW_2YR_TRANS_YR4_RT',
 'HI_INC_WDRAW_2YR_TRANS_YR6_RT',
 'HI_INC_COMP_4YR_TRANS_YR4_RT',
 'HI_INC_COMP_4YR_TRANS_YR6_RT',
 'HI_INC_ENRL_4YR_TRANS_YR4_RT',
 'HI_INC_ENRL_4YR_TRANS_YR6_RT',
 'HI_INC_UNKN_4YR_TRANS_YR4_RT',
 'HI_INC_UNKN_4YR_TRANS_YR6_RT',
 'HI_INC_WDRAW_4YR_TRANS_YR4_RT',
 'HI_INC_WDRAW_4YR_TRANS_YR6_RT',
 'HI_INC_ENRL_ORIG_YR4_RT',
 'HI_INC_ENRL_ORIG_YR6_RT',
 'HI_INC_UNKN_ORIG_YR4_RT',
 'HI_INC_UNKN_ORIG_YR6_RT',
 'HI_INC_WDRAW_ORIG_YR4_RT',
 'HI_INC_WDRAW_ORIG_YR6_RT',
 'LO_INC_COMP_ORIG_YR4_RT',
 'LO_INC_COMP_ORIG_YR6_RT',
 'LO_INC_DEATH_YR4_RT',
 'LO_INC_DEATH_YR6_RT',
 'LO_INC_COMP_2YR_TRANS_YR4_RT',
 'LO_INC_COMP_2YR_TRANS_YR6_RT',
 'LO_INC_ENRL_2YR_TRANS_YR4_RT',
 'LO_INC_ENRL_2YR_TRANS_YR6_RT',
 'LO_INC_UNKN_2YR_TRANS_YR4_RT',
 'LO_INC_UNKN_2YR_TRANS_YR6_RT',
 'LO_INC_WDRAW_2YR_TRANS_YR4_RT',
 'LO_INC_WDRAW_2YR_TRANS_YR6_RT',
 'LO_INC_COMP_4YR_TRANS_YR4_RT',
 'LO_INC_COMP_4YR_TRANS_YR6_RT',
 'LO_INC_ENRL_4YR_TRANS_YR4_RT',
 'LO_INC_ENRL_4YR_TRANS_YR6_RT',
 'LO_INC_UNKN_4YR_TRANS_YR4_RT',
 'LO_INC_UNKN_4YR_TRANS_YR6_RT',
 'LO_INC_WDRAW_4YR_TRANS_YR4_RT',
 'LO_INC_WDRAW_4YR_TRANS_YR6_RT',
 'LO_INC_ENRL_ORIG_YR4_RT',
 'LO_INC_ENRL_ORIG_YR6_RT',
 'LO_INC_UNKN_ORIG_YR4_RT',
 'LO_INC_UNKN_ORIG_YR6_RT',
 'LO_INC_WDRAW_ORIG_YR4_RT',
 'LO_INC_WDRAW_ORIG_YR6_RT',
 'MD_INC_COMP_ORIG_YR4_RT',
 'MD_INC_COMP_ORIG_YR6_RT',
 'MD_INC_DEATH_YR4_RT',
 'MD_INC_DEATH_YR6_RT',
 'MD_INC_COMP_2YR_TRANS_YR4_RT',
 'MD_INC_COMP_2YR_TRANS_YR6_RT',
 'MD_INC_ENRL_2YR_TRANS_YR4_RT',
 'MD_INC_ENRL_2YR_TRANS_YR6_RT',
 'MD_INC_UNKN_2YR_TRANS_YR4_RT',
 'MD_INC_UNKN_2YR_TRANS_YR6_RT',
 'MD_INC_WDRAW_2YR_TRANS_YR4_RT',
 'MD_INC_WDRAW_2YR_TRANS_YR6_RT',
 'MD_INC_COMP_4YR_TRANS_YR4_RT',
 'MD_INC_COMP_4YR_TRANS_YR6_RT',
 'MD_INC_ENRL_4YR_TRANS_YR4_RT',
 'MD_INC_ENRL_4YR_TRANS_YR6_RT',
 'MD_INC_UNKN_4YR_TRANS_YR4_RT',
 'MD_INC_UNKN_4YR_TRANS_YR6_RT',
 'MD_INC_WDRAW_4YR_TRANS_YR4_RT',
 'MD_INC_WDRAW_4YR_TRANS_YR6_RT',
 'MD_INC_ENRL_ORIG_YR4_RT',
 'MD_INC_ENRL_ORIG_YR6_RT',
 'MD_INC_UNKN_ORIG_YR4_RT',
 'MD_INC_UNKN_ORIG_YR6_RT',
 'MD_INC_WDRAW_ORIG_YR4_RT',
 'MD_INC_WDRAW_ORIG_YR6_RT',
 'WDRAW_ORIG_YR2_RT',
 'COSTT4_A',
 'COSTT4_P',
 'NPT41_OTHER',
 'NPT41_PRIV',
 'NPT41_PROG',
 'NPT41_PUB',
 'NPT4_048_OTHER',
 'NPT4_048_PRIV',
 'NPT4_048_PROG',
 'NPT4_048_PUB',
 'NPT45_OTHER',
 'NPT45_PRIV',
 'NPT45_PROG',
 'NPT45_PUB',
 'NPT42_OTHER',
 'NPT42_PRIV',
 'NPT42_PROG',
 'NPT42_PUB',
 'NPT4_3075_OTHER',
 'NPT4_3075_PRIV',
 'NPT4_3075_PROG',
 'NPT4_3075_PUB',
 'NPT43_OTHER',
 'NPT43_PRIV',
 'NPT43_PROG',
 'NPT43_PUB',
 'NPT4_75UP_OTHER',
 'NPT4_75UP_PRIV',
 'NPT4_75UP_PROG',
 'NPT4_75UP_PUB',
 'NPT44_OTHER',
 'NPT44_PRIV',
 'NPT44_PROG',
 'NPT44_PUB',
 'NPT4_PROG',
 'NPT4_OTHER',
 'NPT4_PRIV',
 'NPT4_PUB',
 'TUITIONFEE_IN',
 'NUM4_OTHER',
 'NUM4_PRIV',
 'NUM4_PROG',
 'NUM4_PUB',
 'NUM41_OTHER',
 'NUM41_PRIV',
 'NUM41_PROG',
 'NUM41_PUB',
 'NUM45_OTHER',
 'NUM45_PRIV',
 'NUM45_PROG',
 'NUM45_PUB',
 'NUM42_OTHER',
 'NUM42_PRIV',
 'NUM42_PROG',
 'NUM42_PUB',
 'NUM43_OTHER',
 'NUM43_PRIV',
 'NUM43_PROG',
 'NUM43_PUB',
 'NUM44_OTHER',
 'NUM44_PRIV',
 'NUM44_PROG',
 'NUM44_PUB',
 'TUITIONFEE_OUT',
 'TUITIONFEE_PROG',
 'CIPTFBSANNUAL1',
 'CIPTFBS1',
 'CIPTFBSANNUAL2',
 'CIPTFBS2',
 'CIPTFBSANNUAL3',
 'CIPTFBS3',
 'CIPTFBSANNUAL4',
 'CIPTFBS4',
 'CIPTFBSANNUAL5',
 'CIPTFBS5',
 'CIPTFBSANNUAL6',
 'CIPTFBS6',
 'PCT10_EARN_WNE_P10',
 'PCT10_EARN_WNE_P6',
 'PCT10_EARN_WNE_P8',
 'PCT25_EARN_WNE_P10',
 'PCT25_EARN_WNE_P6',
 'PCT25_EARN_WNE_P8',
 'PCT75_EARN_WNE_P10',
 'PCT75_EARN_WNE_P6',
 'PCT75_EARN_WNE_P8',
 'PCT90_EARN_WNE_P10',
 'PCT90_EARN_WNE_P6',
 'PCT90_EARN_WNE_P8',
 'MN_EARN_WNE_INDEP0_P10',
 'MN_EARN_WNE_INDEP0_INC1_P10',
 'MN_EARN_WNE_INDEP0_P6',
 'MN_EARN_WNE_INDEP0_INC1_P6',
 'MN_EARN_WNE_MALE0_P10',
 'MN_EARN_WNE_MALE0_P6',
 'MN_EARN_WNE_INDEP1_P10',
 'MN_EARN_WNE_INDEP1_P6',
 'MN_EARN_WNE_MALE1_P10',
 'MN_EARN_WNE_MALE1_P6',
 'MN_EARN_WNE_P10',
 'MN_EARN_WNE_INC3_P10',
 'MN_EARN_WNE_INC1_P10',
 'MN_EARN_WNE_INC2_P10',
 'MN_EARN_WNE_P6',
 'MN_EARN_WNE_INC3_P6',
 'MN_EARN_WNE_INC1_P6',
 'MN_EARN_WNE_INC2_P6',
 'MN_EARN_WNE_P7',
 'MN_EARN_WNE_P8',
 'MN_EARN_WNE_P9',
 'MD_EARN_WNE_P10',
 'MD_EARN_WNE_P6',
 'MD_EARN_WNE_P8',
 'COUNT_WNE_INDEP0_P10',
 'COUNT_WNE_INDEP0_INC1_P10',
 'COUNT_WNE_INDEP0_P6',
 'COUNT_WNE_INDEP0_INC1_P6',
 'COUNT_WNE_MALE0_P10',
 'COUNT_WNE_MALE0_P6',
 'COUNT_WNE_INDEP1_P10',
 'COUNT_WNE_INDEP1_P6',
 'COUNT_WNE_MALE1_P10',
 'COUNT_WNE_MALE1_P6',
 'COUNT_NWNE_P10',
 'COUNT_NWNE_P6',
 'COUNT_NWNE_P7',
 'COUNT_NWNE_P8',
 'COUNT_NWNE_P9',
 'COUNT_WNE_P10',
 'COUNT_WNE_INC3_P10',
 'COUNT_WNE_INC1_P10',
 'COUNT_WNE_INC2_P10',
 'COUNT_WNE_P6',
 'COUNT_WNE_INC3_P6',
 'COUNT_WNE_INC1_P6',
 'COUNT_WNE_INC2_P6',
 'COUNT_WNE_P7',
 'COUNT_WNE_P8',
 'COUNT_WNE_P9',
 'GT_25K_P10',
 'GT_25K_P6',
 'GT_25K_P7',
 'GT_25K_P8',
 'GT_25K_P9',
 'GT_28K_P10',
 'GT_28K_P6',
 'GT_28K_P8',
 'SD_EARN_WNE_P10',
 'SD_EARN_WNE_P6',
 'SD_EARN_WNE_P7',
 'SD_EARN_WNE_P8',
 'SD_EARN_WNE_P9',
 'LO_INC_RPY_5YR_RT',
 'MD_INC_RPY_5YR_RT',
 'HI_INC_RPY_5YR_RT',
 'COMPL_RPY_5YR_RT',
 'DEP_RPY_5YR_RT',
 'FEMALE_RPY_5YR_RT',
 'FIRSTGEN_RPY_5YR_RT',
 'IND_RPY_5YR_RT',
 'MALE_RPY_5YR_RT',
 'NONCOM_RPY_5YR_RT',
 'NOTFIRSTGEN_RPY_5YR_RT',
 'NOPELL_RPY_5YR_RT',
 'PELL_RPY_5YR_RT',
 'RPY_5YR_RT',
 'RPY_1YR_RT',
 'RPY_7YR_RT',
 'RPY_3YR_RT',
 'LO_INC_RPY_1YR_RT',
 'MD_INC_RPY_1YR_RT',
 'HI_INC_RPY_1YR_RT',
 'COMPL_RPY_1YR_RT',
 'DEP_RPY_1YR_RT',
 'FEMALE_RPY_1YR_RT',
 'FIRSTGEN_RPY_1YR_RT',
 'IND_RPY_1YR_RT',
 'MALE_RPY_1YR_RT',
 'NONCOM_RPY_1YR_RT',
 'NOTFIRSTGEN_RPY_1YR_RT',
 'NOPELL_RPY_1YR_RT',
 'PELL_RPY_1YR_RT',
 'LO_INC_RPY_7YR_RT',
 'MD_INC_RPY_7YR_RT',
 'HI_INC_RPY_7YR_RT',
 'COMPL_RPY_7YR_RT',
 'DEP_RPY_7YR_RT',
 'FEMALE_RPY_7YR_RT',
 'FIRSTGEN_RPY_7YR_RT',
 'IND_RPY_7YR_RT',
 'MALE_RPY_7YR_RT',
 'NONCOM_RPY_7YR_RT',
 'NOTFIRSTGEN_RPY_7YR_RT',
 'NOPELL_RPY_7YR_RT',
 'PELL_RPY_7YR_RT',
 'LO_INC_RPY_3YR_RT',
 'MD_INC_RPY_3YR_RT',
 'HI_INC_RPY_3YR_RT',
 'COMPL_RPY_3YR_RT',
 'DEP_RPY_3YR_RT',
 'FEMALE_RPY_3YR_RT',
 'FIRSTGEN_RPY_3YR_RT',
 'IND_RPY_3YR_RT',
 'MALE_RPY_3YR_RT',
 'NONCOM_RPY_3YR_RT',
 'NOTFIRSTGEN_RPY_3YR_RT',
 'NOPELL_RPY_3YR_RT',
 'PELL_RPY_3YR_RT',
 'OPEID6',
 'OPEID',
 'LATITUDE',
 'LONGITUDE',
 'UNITID',
 'AVGFACSAL',
 'CCBASIC',
 'CCSIZSET',
 'CCUGPROF',
 'CITY',
 'CONTROL',
 'SCHTYPE',
 'LOCALE2',
 'ST_FIPS',
 'CURROPER',
 'DISTANCEONLY',
 'MAIN',
 'MENONLY',
 'WOMENONLY',
 'INSTNM',
 'INEXPFTE',
 'ICLEVEL',
 'LOCALE',
 'TUITFTE',
 'NUMBRANCH',
 'SCH_DEG',
 'PREDDEG',
 'PFTFAC',
 'REGION',
 'STABBR',
 'INSTURL',
 'ZIP',
 'INC_PCT_H2',
 'INC_PCT_M1',
 'INC_PCT_M2',
 'INC_PCT_H1',
 'AGE_ENTRY',
 'FAMINC_IND',
 'FAMINC',
 'FSEND_COUNT',
 'AGE_ENTRY_SQ',
 'LNFAMINC',
 'LNFAMINC_IND',
 'UG',
 'UGDS',
 'LN_MEDIAN_HH_INC',
 'MD_FAMINC',
 'MEDIAN_HH_INC',
 'SCUGFFN_POOLED',
 'AGEGE24',
 'PCT_GRAD_PROF',
 'PCT_ASIAN',
 'PCT_BLACK',
 'PCT_HISPANIC',
 'PCT_WHITE',
 'PCT_BORN_US',
 'PCT_BA',
 'UG25ABV',
 'POVERTY_RATE',
 'DEPENDENT',
 'FEMALE',
 'FIRST_GEN',
 'MARRIED',
 'PELL_EVER',
 'FSEND_5',
 'FSEND_4',
 'FSEND_1',
 'FSEND_3',
 'FSEND_2',
 'PPTUG_EF',
 'PPTUG_EF2',
 'VETERAN',
 'UGDS_AIAN',
 'UGDS_AIANOLD',
 'UGDS_ASIAN',
 'UGDS_API',
 'UGDS_BLACK',
 'UGDS_BLACKNH',
 'UGDS_HISP',
 'UGDS_HISPOLD',
 'UGDS_NHPI',
 'UGDS_NRA',
 'UGDS_2MOR',
 'UGDS_WHITE',
 'UGDS_WHITENH',
 'UGDS_UNKN',
 'UG_AIANOLD',
 'UG_API',
 'UG_BLACKNH',
 'UG_HISPOLD',
 'UG_NRA',
 'UG_WHITENH',
 'UG_UNKN',
 'UNEMP_RATE']

In [137]:
filtered_df = df.copy()

In [144]:
for variable in complete_variable_name_list:
    if variable not in filtered_variable_name_list:
        filtered_df.drop(columns = variable, inplace = True)

In [145]:
filtered_df

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,INSTURL,SCH_DEG,MAIN,...,CIPTFBSANNUAL6,MTHCMP1,MTHCMP2,MTHCMP3,MTHCMP4,MTHCMP5,MTHCMP6,FTFTPCTPELL_POOLED_SUPP,FTFTPCTFLOAN_POOLED_SUPP,SCUGFFN_POOLED
0,100654,100200,1002,Alabama A & M University,Normal,AL,35762,www.aamu.edu/,3.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.7083,0.7287,2698.0
1,100663,105200,1052,University of Alabama at Birmingham,Birmingham,AL,35294-0110,https://www.uab.edu,3.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.3891,0.5414,4176.0
2,100690,2503400,25034,Amridge University,Montgomery,AL,36117-3553,www.amridgeuniversity.edu,3.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PrivacySuppressed,PrivacySuppressed,24.0
3,100706,105500,1055,University of Alabama in Huntsville,Huntsville,AL,35899,www.uah.edu,3.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.2378,0.4402,2544.0
4,100724,100500,1005,Alabama State University,Montgomery,AL,36104-0271,www.alasu.edu,3.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.7684,0.7464,2094.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6801,48511112,157114,1571,Georgia Military College - Dublin,Dublin,GA,310215149,https://www.gmc.edu/index.cms,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6802,48511113,157115,1571,Georgia Military College - Eastman,Eastman,GA,310236109,https://www.gmc.edu/index.cms,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6803,48616901,4204801,42048,American College of Barbering - Florence,Florence,KY,410421801,NaN,NaN,0,...,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6804,49005401,4182601,41826,HCI College - Fort Lauderdale Campus,Fort Lauderdale,FL,33309,www.hci.edu/,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6805,49146401,4227001,42270,ABC Adult School - Cabrillo Lane,Cerritos,CA,907037748,NaN,NaN,0,...,NaN,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [125]:
column_heading_df['dev-category'].unique()

array(['academics', 'admissions', 'aid', 'completion', 'cost', 'earnings',
       'repayment', 'root', 'school', 'student'], dtype=object)

In [105]:
df

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,ACCREDAGENCY,INSTURL,NPCURL,...,OMENRUP_PARTTIME_POOLED_SUPP,FTFTPCTPELL,FTFTPCTFLOAN,UG12MN,G12MN,SCUGFFN,POOLYRS_FTFTAIDPCT,FTFTPCTPELL_POOLED_SUPP,FTFTPCTFLOAN_POOLED_SUPP,SCUGFFN_POOLED
0,100654,100200,1002,Alabama A & M University,Normal,AL,35762,Southern Association of Colleges and Schools C...,www.aamu.edu/,www.aamu.edu/admissions-aid/tuition-fees/net-p...,...,0.3193,0.7057,0.7143,5343.0,1165.0,1288.0,2.0,0.7083,0.7287,2698.0
1,100663,105200,1052,University of Alabama at Birmingham,Birmingham,AL,35294-0110,Southern Association of Colleges and Schools C...,https://www.uab.edu,https://uab.studentaidcalculator.com/survey.aspx,...,0.2475,0.3788,0.5350,14445.0,10498.0,2228.0,2.0,0.3891,0.5414,4176.0
2,100690,2503400,25034,Amridge University,Montgomery,AL,36117-3553,Southern Association of Colleges and Schools C...,www.amridgeuniversity.edu,www2.amridgeuniversity.edu:9091/,...,0.2836,1.0000,1.0000,440.0,527.0,5.0,4.0,PrivacySuppressed,PrivacySuppressed,24.0
3,100706,105500,1055,University of Alabama in Huntsville,Huntsville,AL,35899,Southern Association of Colleges and Schools C...,www.uah.edu,finaid.uah.edu/,...,0.2496,0.2707,0.4556,8145.0,2443.0,1341.0,2.0,0.2378,0.4402,2544.0
4,100724,100500,1005,Alabama State University,Montgomery,AL,36104-0271,Southern Association of Colleges and Schools C...,www.alasu.edu,www.alasu.edu/cost-aid/tuition-costs/net-price...,...,0.2621,0.7792,0.7539,4732.0,642.0,951.0,2.0,0.7684,0.7464,2094.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6801,48511112,157114,1571,Georgia Military College - Dublin,Dublin,GA,310215149,Southern Association of Colleges and Schools C...,https://www.gmc.edu/index.cms,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6802,48511113,157115,1571,Georgia Military College - Eastman,Eastman,GA,310236109,Southern Association of Colleges and Schools C...,https://www.gmc.edu/index.cms,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6803,48616901,4204801,42048,American College of Barbering - Florence,Florence,KY,410421801,National Accrediting Commission of Career Arts...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6804,49005401,4182601,41826,HCI College - Fort Lauderdale Campus,Fort Lauderdale,FL,33309,Accrediting Commission of Career Schools and C...,www.hci.edu/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6805,49146401,4227001,42270,ABC Adult School - Cabrillo Lane,Cerritos,CA,907037748,Council on Occupational Education,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [106]:
df.loc[df['INSTNM'] == 'Harvard University', ['PREDDEG','NPT4_PRIV', 'TUITIONFEE_IN']]

      PREDDEG  NPT4_PRIV  TUITIONFEE_IN
1492        3    15561.0        50420.0

In [107]:
df.loc[df['INSTNM'] == 'Ohio State University-Main Campus', ['PREDDEG','NPT4_PRIV', 'TUITIONFEE_IN']]

      PREDDEG  NPT4_PRIV  TUITIONFEE_IN
2666        3        NaN        10726.0

In [108]:
df.loc[df['INSTNM'] == 'Dartmouth College', ['PREDDEG','NPT4_PRIV', 'TUITIONFEE_IN']]

      PREDDEG  NPT4_PRIV  TUITIONFEE_IN
1959        3    31449.0        55453.0

In [109]:
df.loc[df['INSTNM'] == 'Harvey Mudd College', ['PREDDEG','NPT4_PRIV', 'TUITIONFEE_IN']]

     PREDDEG  NPT4_PRIV  TUITIONFEE_IN
315        3    32739.0        56620.0

In [110]:
df.columns

Index(['UNITID', 'OPEID', 'OPEID6', 'INSTNM', 'CITY', 'STABBR', 'ZIP',
       'ACCREDAGENCY', 'INSTURL', 'NPCURL',
       ...
       'OMENRUP_PARTTIME_POOLED_SUPP', 'FTFTPCTPELL', 'FTFTPCTFLOAN', 'UG12MN',
       'G12MN', 'SCUGFFN', 'POOLYRS_FTFTAIDPCT', 'FTFTPCTPELL_POOLED_SUPP',
       'FTFTPCTFLOAN_POOLED_SUPP', 'SCUGFFN_POOLED'],
      dtype='object', length=1986)

In [111]:
df['PREDDEG']

0       3
1       3
2       3
3       3
4       3
       ..
6801    0
6802    0
6803    0
6804    0
6805    0
Name: PREDDEG, Length: 6806, dtype: int64

In [112]:
df.loc[df['PREDDEG'] == 3, :]

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,ACCREDAGENCY,INSTURL,NPCURL,...,OMENRUP_PARTTIME_POOLED_SUPP,FTFTPCTPELL,FTFTPCTFLOAN,UG12MN,G12MN,SCUGFFN,POOLYRS_FTFTAIDPCT,FTFTPCTPELL_POOLED_SUPP,FTFTPCTFLOAN_POOLED_SUPP,SCUGFFN_POOLED
0,100654,100200,1002,Alabama A & M University,Normal,AL,35762,Southern Association of Colleges and Schools C...,www.aamu.edu/,www.aamu.edu/admissions-aid/tuition-fees/net-p...,...,0.3193,0.7057,0.7143,5343.0,1165.0,1288.0,2.0,0.7083,0.7287,2698.0
1,100663,105200,1052,University of Alabama at Birmingham,Birmingham,AL,35294-0110,Southern Association of Colleges and Schools C...,https://www.uab.edu,https://uab.studentaidcalculator.com/survey.aspx,...,0.2475,0.3788,0.5350,14445.0,10498.0,2228.0,2.0,0.3891,0.5414,4176.0
2,100690,2503400,25034,Amridge University,Montgomery,AL,36117-3553,Southern Association of Colleges and Schools C...,www.amridgeuniversity.edu,www2.amridgeuniversity.edu:9091/,...,0.2836,1.0000,1.0000,440.0,527.0,5.0,4.0,PrivacySuppressed,PrivacySuppressed,24.0
3,100706,105500,1055,University of Alabama in Huntsville,Huntsville,AL,35899,Southern Association of Colleges and Schools C...,www.uah.edu,finaid.uah.edu/,...,0.2496,0.2707,0.4556,8145.0,2443.0,1341.0,2.0,0.2378,0.4402,2544.0
4,100724,100500,1005,Alabama State University,Montgomery,AL,36104-0271,Southern Association of Colleges and Schools C...,www.alasu.edu,www.alasu.edu/cost-aid/tuition-costs/net-price...,...,0.2621,0.7792,0.7539,4732.0,642.0,951.0,2.0,0.7684,0.7464,2094.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6299,492069,4276100,42761,Champion Christian College,Hot Springs,AR,71913,Transnational Association of Christian College...,championchristiancollege.com,championchristiancollege.com/NetPriceCalculato...,...,PrivacySuppressed,0.0000,0.0000,57.0,NaN,20.0,4.0,PrivacySuppressed,PrivacySuppressed,20.0
6314,492689,1067401,10674,Texas Tech University Health Sciences Center-E...,El Paso,TX,79905-2827,Southern Association of Colleges and Schools C...,elpaso.ttuhsc.edu/,www.depts.ttu.edu/financialaid/netCostCalcHome...,...,NaN,NaN,NaN,370.0,471.0,0.0,4.0,NaN,NaN,0.0
6318,492759,638521,6385,Chamberlain University-Louisiana,Jefferson,LA,70121,Higher Learning Commission,https://www.chamberlain.edu/,https://www.chamberlain.edu/admissions/financi...,...,NaN,NaN,NaN,21.0,NaN,NaN,NaN,NaN,NaN,NaN
6319,492801,246100,2461,Drury University-College of Continuing Profess...,Springfield,MO,65802,Higher Learning Commission,www.drury.edu/ccps/,tcc.ruffalonl.com/Drury%20University/Freshman-...,...,0.3681,0.7619,0.4048,2857.0,NaN,42.0,2.0,0.7619,0.4048,42.0
6322,492962,180500,1805,Indiana Institute of Technology-College of Pro...,Fort Wayne,IN,46803,Higher Learning Commission,cps.indianatech.edu/,cps.indianatech.edu/costs/,...,0.6939,0.8710,0.8996,6739.0,NaN,279.0,2.0,0.871,0.8996,279.0

In [113]:
cost_df = df.loc[df['PREDDEG'] == 3, ['INSTNM', 'STABBR','TUITIONFEE_IN', 'TUITIONFEE_OUT']]

In [114]:
cost_df = cost_df.fillna(0)

In [115]:
cost_df=cost_df.sort_values(by = 'TUITIONFEE_IN', ascending = False).reset_index()

In [116]:
cost_df

,index,INSTNM,STABBR,TUITIONFEE_IN,TUITIONFEE_OUT
0,2153,Columbia University in the City of New York,NY,59430.0,59430.0
1,890,University of Chicago,IL,58230.0,58230.0
2,2368,Vassar College,NY,56960.0,56960.0
3,600,Trinity College,CT,56910.0,56910.0
4,2219,Jewish Theological Seminary of America,NY,56778.0,56778.0
...,...,...,...,...,...
2053,229,Sofia University,CA,0.0,0.0
2054,2347,SUNY Downstate Health Sciences University,NY,0.0,0.0
2055,3560,Bon Secours Memorial College of Nursing,VA,0.0,0.0
2056,309,Golden Gate University-San Francisco,CA,0.0,0.0
2057,2366,United States Military Academy,NY,0.0,0.0

In [117]:
cost_df.loc[cost_df['INSTNM'] == 'Ohio State University-Main Campus', :]

,index,INSTNM,STABBR,TUITIONFEE_IN,TUITIONFEE_OUT
1382,2666,Ohio State University-Main Campus,OH,10726.0,30742.0

In [118]:
cost_df.loc[cost_df['index'] == 2666, :]

,index,INSTNM,STABBR,TUITIONFEE_IN,TUITIONFEE_OUT
1382,2666,Ohio State University-Main Campus,OH,10726.0,30742.0

In [119]:
cost_df.loc[cost_df['INSTNM'] == 'Smith College', :]

    index         INSTNM STABBR  TUITIONFEE_IN  TUITIONFEE_OUT
81   1544  Smith College     MA        52404.0         52404.0