In [1]:
#Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from numpy import nan
import matplotlib.pyplot as plt
from IPython.display import SVG
from keras.utils.vis_utils import model_to_dot
from keras.utils.vis_utils import plot_model
from IPython.display import Image

In [2]:
from sklearn import datasets
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import Dense
from sklearn.preprocessing import LabelBinarizer
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [3]:
import tensorflow as tf

In [4]:
path = './data_documentation/'
ranking_data = 'filtered_ranking_4_year_df.csv'

In [28]:
ranking_df = pd.read_csv(path + ranking_data, index_col = 0)

In [29]:
ranking_df

,Rank,INSTNM,PREDDEG,HIGHDEG,CONTROL,LOCALE,CCBASIC,CCUGPROF,CCSIZSET,HBCU,...,Alumni Salary,Acceptance Rate,SAT Lower,SAT Upper,ACT Lower,ACT Upper,10%_cut,5%_cut,20%_cut,50%_cut
0,456,University of Alabama at Birmingham,3,4,1,12.0,15.0,9.0,15.0,0.0,...,87200.0,92.0,990.0,1370.0,21.0,28.0,7,14,3,1
1,475,University of Alabama in Huntsville,3,4,1,12.0,16.0,15.0,12.0,0.0,...,103900.0,81.0,1080.0,1330.0,25.0,31.0,7,14,3,1
2,252,The University of Alabama,3,4,1,12.0,15.0,14.0,16.0,0.0,...,97400.0,53.0,1050.0,1280.0,23.0,32.0,3,7,1,0
3,166,Auburn University,3,4,1,13.0,15.0,14.0,15.0,0.0,...,104500.0,84.0,1130.0,1310.0,24.0,30.0,2,4,1,0
4,463,Birmingham-Southern College,3,3,2,12.0,21.0,14.0,11.0,0.0,...,88300.0,62.0,1030.0,1260.0,23.0,29.0,7,14,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
634,118,Purdue University-Main Campus,3,4,1,13.0,15.0,14.0,16.0,0.0,...,110000.0,57.0,1150.0,1380.0,25.0,31.0,1,3,0,0
635,577,St. John's College,3,4,2,41.0,21.0,15.0,8.0,0.0,...,0.0,63.0,1190.0,1350.0,23.0,32.0,8,17,4,1
636,277,New College of Florida,3,4,1,13.0,21.0,14.0,8.0,0.0,...,86500.0,69.0,1190.0,1380.0,25.0,30.0,4,8,2,0
637,519,Florida Gulf Coast University,3,4,1,21.0,18.0,9.0,16.0,0.0,...,80000.0,64.0,1060.0,1210.0,21.0,25.0,7,15,3,1
638,505,University of North Georgia,3,4,1,31.0,19.0,6.0,15.0,0.0,...,85600.0,78.0,910.0,1130.0,20.0,25.0,7,15,3,1

In [30]:
y_data = ranking_df['20%_cut']

In [31]:
y = y_data.to_numpy()

In [33]:
ranking_df = ranking_df.drop(columns = ['Rank', '5%_cut', '10%_cut', '20%_cut', '50%_cut', 'INSTNM'])

In [34]:
ranking_df

,PREDDEG,HIGHDEG,CONTROL,LOCALE,CCBASIC,CCUGPROF,CCSIZSET,HBCU,PBI,ANNHI,...,Student Population,Net Price,Average Grant Aid,Total Annual Cost,Alumni Salary,Acceptance Rate,SAT Lower,SAT Upper,ACT Lower,ACT Upper
0,3,4,1,12.0,15.0,9.0,15.0,0.0,0.0,0.0,...,20902,17535,9254,36800,87200.0,92.0,990.0,1370.0,21.0,28.0
1,3,4,1,12.0,16.0,15.0,12.0,0.0,0.0,0.0,...,9101,19986,9587,36881,103900.0,81.0,1080.0,1330.0,25.0,31.0
2,3,4,1,12.0,15.0,14.0,16.0,0.0,0.0,0.0,...,38563,21973,16494,46744,97400.0,53.0,1050.0,1280.0,23.0,32.0
3,3,4,1,13.0,15.0,14.0,15.0,0.0,0.0,0.0,...,29776,23416,9030,49954,104500.0,84.0,1130.0,1310.0,24.0,30.0
4,3,3,2,12.0,21.0,14.0,11.0,0.0,0.0,0.0,...,1325,22853,26594,52414,88300.0,62.0,1030.0,1260.0,23.0,29.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
634,3,4,1,13.0,15.0,14.0,16.0,0.0,0.0,0.0,...,42699,13746,10703,41614,110000.0,57.0,1150.0,1380.0,25.0,31.0
635,3,4,2,41.0,21.0,15.0,8.0,0.0,0.0,0.0,...,386,20605,31845,65456,0.0,63.0,1190.0,1350.0,23.0,32.0
636,3,4,1,13.0,21.0,14.0,8.0,0.0,0.0,0.0,...,885,10248,9341,43678,86500.0,69.0,1190.0,1380.0,25.0,30.0
637,3,4,1,21.0,18.0,9.0,16.0,0.0,0.0,0.0,...,15317,15376,4726,39434,80000.0,64.0,1060.0,1210.0,21.0,25.0
638,3,4,1,31.0,19.0,6.0,15.0,0.0,0.0,0.0,...,20811,9854,5483,28094,85600.0,78.0,910.0,1130.0,20.0,25.0

In [35]:
# Splitting the data into training and test test
#X = ranking_df.iloc[:,1:196].values
X = ranking_df.values

In [36]:
X

array([[3.00e+00, 4.00e+00, 1.00e+00, ..., 1.37e+03, 2.10e+01, 2.80e+01],
       [3.00e+00, 4.00e+00, 1.00e+00, ..., 1.33e+03, 2.50e+01, 3.10e+01],
       [3.00e+00, 4.00e+00, 1.00e+00, ..., 1.28e+03, 2.30e+01, 3.20e+01],
       ...,
       [3.00e+00, 4.00e+00, 1.00e+00, ..., 1.38e+03, 2.50e+01, 3.00e+01],
       [3.00e+00, 4.00e+00, 1.00e+00, ..., 1.21e+03, 2.10e+01, 2.50e+01],
       [3.00e+00, 4.00e+00, 1.00e+00, ..., 1.13e+03, 2.00e+01, 2.50e+01]])

In [37]:
len(X[0])

284

In [48]:
X.shape

(639, 284)

In [38]:
y

array([3, 3, 1, 1, 3, 1, 4, 4, 4, 4, 1, 1, 3, 4, 2, 2, 2, 3, 3, 2, 0, 1,
       0, 3, 3, 2, 2, 3, 2, 3, 2, 3, 3, 3, 0, 0, 0, 0, 1, 0, 1, 2, 1, 0,
       0, 4, 3, 2, 0, 2, 4, 0, 1, 0, 0, 1, 0, 2, 1, 1, 3, 1, 2, 0, 2, 3,
       4, 0, 1, 3, 3, 4, 1, 0, 0, 1, 1, 4, 4, 2, 4, 0, 0, 1, 4, 1, 2, 0,
       0, 0, 1, 0, 2, 0, 0, 2, 4, 1, 3, 2, 2, 3, 2, 2, 2, 3, 1, 0, 0, 0,
       3, 3, 1, 1, 3, 3, 4, 3, 3, 2, 0, 0, 2, 4, 3, 0, 3, 4, 4, 3, 2, 4,
       3, 4, 3, 2, 4, 2, 0, 1, 3, 2, 4, 0, 1, 4, 1, 2, 2, 3, 1, 4, 4, 3,
       4, 0, 4, 4, 4, 0, 4, 3, 1, 0, 2, 2, 3, 2, 4, 4, 4, 0, 0, 0, 2, 1,
       3, 2, 3, 4, 3, 3, 2, 1, 0, 1, 1, 2, 3, 3, 3, 1, 2, 4, 4, 3, 3, 1,
       4, 4, 2, 3, 4, 4, 2, 4, 4, 1, 3, 3, 4, 4, 4, 0, 4, 0, 0, 0, 3, 3,
       3, 4, 0, 1, 1, 0, 2, 1, 1, 2, 2, 3, 0, 2, 0, 0, 0, 0, 1, 1, 2, 2,
       0, 0, 3, 1, 4, 0, 2, 2, 1, 1, 1, 2, 0, 1, 0, 0, 2, 1, 0, 0, 3, 4,
       4, 2, 4, 2, 3, 1, 1, 3, 0, 1, 2, 4, 4, 4, 2, 0, 2, 1, 3, 0, 4, 0,
       3, 2, 3, 1, 4, 1, 3, 0, 3, 1, 4, 2, 3, 3, 3, 4, 3, 1, 1, 3, 1, 2,
       1, 1, 3, 0, 3, 4, 3, 3, 4, 3, 4, 1, 4, 4, 3, 3, 1, 4, 2, 0, 1, 2,
       2, 4, 2, 3, 2, 0, 2, 3, 0, 1, 1, 3, 1, 3, 4, 4, 2, 4, 1, 0, 3, 1,
       0, 0, 0, 0, 1, 2, 4, 3, 2, 3, 2, 4, 1, 0, 4, 1, 2, 3, 2, 1, 0, 2,
       1, 1, 3, 1, 1, 0, 3, 2, 0, 2, 0, 4, 1, 1, 2, 0, 2, 2, 3, 3, 2, 1,
       1, 1, 1, 2, 3, 2, 1, 3, 0, 0, 0, 2, 4, 0, 2, 4, 0, 0, 3, 0, 4, 3,
       3, 3, 0, 3, 4, 1, 2, 4, 4, 0, 3, 2, 3, 4, 4, 4, 0, 1, 2, 4, 1, 1,
       4, 2, 4, 0, 4, 1, 4, 0, 2, 0, 3, 3, 4, 2, 4, 3, 1, 4, 2, 2, 4, 3,
       1, 4, 1, 3, 1, 3, 3, 3, 1, 1, 3, 4, 0, 0, 1, 2, 4, 0, 0, 0, 0, 1,
       2, 3, 3, 0, 1, 0, 4, 4, 2, 4, 2, 0, 2, 0, 4, 2, 4, 3, 1, 0, 0, 0,
       1, 1, 3, 1, 3, 0, 2, 2, 0, 3, 3, 3, 0, 1, 1, 4, 3, 0, 2, 2, 1, 0,
       4, 0, 4, 2, 1, 1, 3, 3, 3, 3, 2, 4, 3, 2, 4, 4, 4, 4, 1, 1, 1, 3,
       2, 0, 3, 2, 1, 2, 2, 3, 4, 0, 2, 2, 4, 4, 0, 2, 3, 0, 3, 0, 1, 4,
       1, 4, 2, 4, 1, 0, 3, 1, 2, 2, 4, 0, 2, 1, 0, 2, 4, 1, 2, 4, 1, 4,
       1, 4, 4, 4, 3, 4, 0, 2, 0, 1, 0, 4, 1, 2, 1, 2, 1, 1, 0, 1, 0, 2,
       2, 3, 1, 4, 4, 1, 1, 2, 4, 2, 2, 2, 4, 0, 4, 4, 2, 0, 0, 4, 2, 3,
       3], dtype=int64)

In [39]:
from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)

In [40]:
y1

array([3, 3, 1, 1, 3, 1, 4, 4, 4, 4, 1, 1, 3, 4, 2, 2, 2, 3, 3, 2, 0, 1,
       0, 3, 3, 2, 2, 3, 2, 3, 2, 3, 3, 3, 0, 0, 0, 0, 1, 0, 1, 2, 1, 0,
       0, 4, 3, 2, 0, 2, 4, 0, 1, 0, 0, 1, 0, 2, 1, 1, 3, 1, 2, 0, 2, 3,
       4, 0, 1, 3, 3, 4, 1, 0, 0, 1, 1, 4, 4, 2, 4, 0, 0, 1, 4, 1, 2, 0,
       0, 0, 1, 0, 2, 0, 0, 2, 4, 1, 3, 2, 2, 3, 2, 2, 2, 3, 1, 0, 0, 0,
       3, 3, 1, 1, 3, 3, 4, 3, 3, 2, 0, 0, 2, 4, 3, 0, 3, 4, 4, 3, 2, 4,
       3, 4, 3, 2, 4, 2, 0, 1, 3, 2, 4, 0, 1, 4, 1, 2, 2, 3, 1, 4, 4, 3,
       4, 0, 4, 4, 4, 0, 4, 3, 1, 0, 2, 2, 3, 2, 4, 4, 4, 0, 0, 0, 2, 1,
       3, 2, 3, 4, 3, 3, 2, 1, 0, 1, 1, 2, 3, 3, 3, 1, 2, 4, 4, 3, 3, 1,
       4, 4, 2, 3, 4, 4, 2, 4, 4, 1, 3, 3, 4, 4, 4, 0, 4, 0, 0, 0, 3, 3,
       3, 4, 0, 1, 1, 0, 2, 1, 1, 2, 2, 3, 0, 2, 0, 0, 0, 0, 1, 1, 2, 2,
       0, 0, 3, 1, 4, 0, 2, 2, 1, 1, 1, 2, 0, 1, 0, 0, 2, 1, 0, 0, 3, 4,
       4, 2, 4, 2, 3, 1, 1, 3, 0, 1, 2, 4, 4, 4, 2, 0, 2, 1, 3, 0, 4, 0,
       3, 2, 3, 1, 4, 1, 3, 0, 3, 1, 4, 2, 3, 3, 3, 4, 3, 1, 1, 3, 1, 2,
       1, 1, 3, 0, 3, 4, 3, 3, 4, 3, 4, 1, 4, 4, 3, 3, 1, 4, 2, 0, 1, 2,
       2, 4, 2, 3, 2, 0, 2, 3, 0, 1, 1, 3, 1, 3, 4, 4, 2, 4, 1, 0, 3, 1,
       0, 0, 0, 0, 1, 2, 4, 3, 2, 3, 2, 4, 1, 0, 4, 1, 2, 3, 2, 1, 0, 2,
       1, 1, 3, 1, 1, 0, 3, 2, 0, 2, 0, 4, 1, 1, 2, 0, 2, 2, 3, 3, 2, 1,
       1, 1, 1, 2, 3, 2, 1, 3, 0, 0, 0, 2, 4, 0, 2, 4, 0, 0, 3, 0, 4, 3,
       3, 3, 0, 3, 4, 1, 2, 4, 4, 0, 3, 2, 3, 4, 4, 4, 0, 1, 2, 4, 1, 1,
       4, 2, 4, 0, 4, 1, 4, 0, 2, 0, 3, 3, 4, 2, 4, 3, 1, 4, 2, 2, 4, 3,
       1, 4, 1, 3, 1, 3, 3, 3, 1, 1, 3, 4, 0, 0, 1, 2, 4, 0, 0, 0, 0, 1,
       2, 3, 3, 0, 1, 0, 4, 4, 2, 4, 2, 0, 2, 0, 4, 2, 4, 3, 1, 0, 0, 0,
       1, 1, 3, 1, 3, 0, 2, 2, 0, 3, 3, 3, 0, 1, 1, 4, 3, 0, 2, 2, 1, 0,
       4, 0, 4, 2, 1, 1, 3, 3, 3, 3, 2, 4, 3, 2, 4, 4, 4, 4, 1, 1, 1, 3,
       2, 0, 3, 2, 1, 2, 2, 3, 4, 0, 2, 2, 4, 4, 0, 2, 3, 0, 3, 0, 1, 4,
       1, 4, 2, 4, 1, 0, 3, 1, 2, 2, 4, 0, 2, 1, 0, 2, 4, 1, 2, 4, 1, 4,
       1, 4, 4, 4, 3, 4, 0, 2, 0, 1, 0, 4, 1, 2, 1, 2, 1, 1, 0, 1, 0, 2,
       2, 3, 1, 4, 4, 1, 1, 2, 4, 2, 2, 2, 4, 0, 4, 4, 2, 0, 0, 4, 2, 3,
       3], dtype=int64)

In [41]:
Y = pd.get_dummies(y1).values

In [42]:
Y

array([[0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0],
       ...,
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0]], dtype=uint8)

In [47]:
len(Y)

639

In [43]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [44]:
#Defining the model 

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD,Adam

In [52]:
model = Sequential()
model.add(Dense(1000,input_dim = 284,activation='tanh', name = 'layer_1'))
#model.add(Dense(128,input_shape=(191,),activation='tanh', name = 'layer_1'))
#model.add(Dense(1000,activation='tanh', name = 'layer_2'))
#model.add(Dense(400,activation='tanh', name = 'layer_3'))
#model.add(Dense(400,activation='tanh', name = 'layer_4'))
#model.add(Dense(400,activation='tanh', name = 'layer_5'))
#model.add(Dense(400,activation='tanh', name = 'layer_6'))
model.add(Dense(5,activation='softmax'))

model.compile(Adam(lr=0.001),'categorical_crossentropy',metrics=['accuracy'])

model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
layer_1 (Dense)              (None, 1000)              285000
_________________________________________________________________
dense_2 (Dense)              (None, 5)                 5005
=================================================================
Total params: 290,005
Trainable params: 290,005
Non-trainable params: 0
_________________________________________________________________

In [50]:
X_train.shape

(511, 284)

In [51]:
y_train.shape

(511, 5)

In [53]:
#fitting the model and predicting 
model.fit(X_train,y_train,epochs=1000)
y_pred = model.predict(X_test)

y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

Epoch 1/1000

InternalError:  Blas GEMM launch failed : a.shape=(32, 284), b.shape=(284, 1000), m=32, n=1000, k=284
	 [[node sequential_2/layer_1/MatMul (defined at <ipython-input-53-4aa634cdff95>:2) ]] [Op:__inference_train_function_919]

Function call stack:
train_function

In [ ]:

#Accuracy of the predicted values
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

In [ ]:
# Summary of neural network
model.summary()

In [ ]:
plot_model(model, show_shapes=True, show_layer_names=True, to_file='model.png')

In [ ]:
tf.keras.utils.plot_model(
    model, to_file='model.png', show_shapes=False, show_layer_names=True,
    rankdir='TB', expand_nested=False, dpi=96
)