In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from numpy import nan
import matplotlib.pyplot as plt

In [2]:
input_file = 'most-recent-cohorts-all-data-elements-1.csv'
column_template = 'column_heading_template.csv'
forbes_data = 'ForbesFrom MAtt_clean.csv'
#there were simply too many wierd columns in the original data set of columns.  I went in and deleted several
#in the master excel file and regenerated the column template.
column_template_2 = 'column_heading_template_new.csv'
path = './data/'
path2 = './data_documentation/'

In [3]:
df = pd.read_csv(path+input_file, low_memory=False)

In [4]:
df

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,ACCREDAGENCY,INSTURL,NPCURL,...,OMENRUP_PARTTIME_POOLED_SUPP,FTFTPCTPELL,FTFTPCTFLOAN,UG12MN,G12MN,SCUGFFN,POOLYRS_FTFTAIDPCT,FTFTPCTPELL_POOLED_SUPP,FTFTPCTFLOAN_POOLED_SUPP,SCUGFFN_POOLED
0,100654,100200,1002,Alabama A & M University,Normal,AL,35762,Southern Association of Colleges and Schools C...,www.aamu.edu/,www.aamu.edu/admissions-aid/tuition-fees/net-p...,...,0.3193,0.7057,0.7143,5343.0,1165.0,1288.0,2.0,0.7083,0.7287,2698.0
1,100663,105200,1052,University of Alabama at Birmingham,Birmingham,AL,35294-0110,Southern Association of Colleges and Schools C...,https://www.uab.edu,https://uab.studentaidcalculator.com/survey.aspx,...,0.2475,0.3788,0.5350,14445.0,10498.0,2228.0,2.0,0.3891,0.5414,4176.0
2,100690,2503400,25034,Amridge University,Montgomery,AL,36117-3553,Southern Association of Colleges and Schools C...,www.amridgeuniversity.edu,www2.amridgeuniversity.edu:9091/,...,0.2836,1.0000,1.0000,440.0,527.0,5.0,4.0,PrivacySuppressed,PrivacySuppressed,24.0
3,100706,105500,1055,University of Alabama in Huntsville,Huntsville,AL,35899,Southern Association of Colleges and Schools C...,www.uah.edu,finaid.uah.edu/,...,0.2496,0.2707,0.4556,8145.0,2443.0,1341.0,2.0,0.2378,0.4402,2544.0
4,100724,100500,1005,Alabama State University,Montgomery,AL,36104-0271,Southern Association of Colleges and Schools C...,www.alasu.edu,www.alasu.edu/cost-aid/tuition-costs/net-price...,...,0.2621,0.7792,0.7539,4732.0,642.0,951.0,2.0,0.7684,0.7464,2094.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6801,48511112,157114,1571,Georgia Military College - Dublin,Dublin,GA,310215149,Southern Association of Colleges and Schools C...,https://www.gmc.edu/index.cms,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6802,48511113,157115,1571,Georgia Military College - Eastman,Eastman,GA,310236109,Southern Association of Colleges and Schools C...,https://www.gmc.edu/index.cms,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6803,48616901,4204801,42048,American College of Barbering - Florence,Florence,KY,410421801,National Accrediting Commission of Career Arts...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6804,49005401,4182601,41826,HCI College - Fort Lauderdale Campus,Fort Lauderdale,FL,33309,Accrediting Commission of Career Schools and C...,www.hci.edu/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6805,49146401,4227001,42270,ABC Adult School - Cabrillo Lane,Cerritos,CA,907037748,Council on Occupational Education,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.loc[1,'UNITID']

100663

In [6]:
df['UGDS']

0        4990.0
1       13186.0
2         351.0
3        7458.0
4        3903.0
         ...
6801        NaN
6802        NaN
6803        NaN
6804        NaN
6805        NaN
Name: UGDS, Length: 6806, dtype: float64

In [7]:
len(df)

6806

In [8]:
df.replace(to_replace = 'PrivacySuppressed', value = nan, inplace = True)

In [9]:
df.loc[df['OPEID6'] == 21997, 'MN_EARN_WNE_P8']

23    NaN
Name: MN_EARN_WNE_P8, dtype: object

In [10]:
column_heading_df = pd.read_csv(path2 + column_template_2)

In [11]:
column_heading_df

,dev-category,NAME OF DATA ELEMENT,developer-friendly name,API data type,VARIABLE NAME
0,academics,Average number of months needed to complete la...,program_reporter.program_1.cip_6_digit.avg_mon...,integer,MTHCMP1
1,academics,Average number of months needed to complete pr...,program_reporter.program_2.cip_6_digit.avg_mon...,integer,MTHCMP2
2,academics,Average number of months needed to complete pr...,program_reporter.program_3.cip_6_digit.avg_mon...,integer,MTHCMP3
3,academics,Average number of months needed to complete pr...,program_reporter.program_4.cip_6_digit.avg_mon...,integer,MTHCMP4
4,academics,Average number of months needed to complete pr...,program_reporter.program_5.cip_6_digit.avg_mon...,integer,MTHCMP5
...,...,...,...,...,...
423,student,Total share of enrollment of undergraduate stu...,demographics.race_ethnicity.hispanic_2000,float,UG_HISPOLD
424,student,Total share of enrollment of undergraduate stu...,demographics.non_resident_aliens_2000,float,UG_NRA
425,student,Total share of enrollment of undergraduate stu...,demographics.race_ethnicity.white_2000,float,UG_WHITENH
426,student,Total share of enrollment of undergraduate stu...,demographics.race_ethnicity.unknown_2000,float,UG_UNKN
427,student,"Unemployment rate, via Census data",demographics.unemployment,float,UNEMP_RATE

In [12]:
complete_variable_name_list = df.columns.to_list()
complete_variable_name_list

['UNITID',
 'OPEID',
 'OPEID6',
 'INSTNM',
 'CITY',
 'STABBR',
 'ZIP',
 'ACCREDAGENCY',
 'INSTURL',
 'NPCURL',
 'SCH_DEG',
 'HCM2',
 'MAIN',
 'NUMBRANCH',
 'PREDDEG',
 'HIGHDEG',
 'CONTROL',
 'ST_FIPS',
 'REGION',
 'LOCALE',
 'LOCALE2',
 'LATITUDE',
 'LONGITUDE',
 'CCBASIC',
 'CCUGPROF',
 'CCSIZSET',
 'HBCU',
 'PBI',
 'ANNHI',
 'TRIBAL',
 'AANAPII',
 'HSI',
 'NANTI',
 'MENONLY',
 'WOMENONLY',
 'RELAFFIL',
 'ADM_RATE',
 'ADM_RATE_ALL',
 'SATVR25',
 'SATVR75',
 'SATMT25',
 'SATMT75',
 'SATWR25',
 'SATWR75',
 'SATVRMID',
 'SATMTMID',
 'SATWRMID',
 'ACTCM25',
 'ACTCM75',
 'ACTEN25',
 'ACTEN75',
 'ACTMT25',
 'ACTMT75',
 'ACTWR25',
 'ACTWR75',
 'ACTCMMID',
 'ACTENMID',
 'ACTMTMID',
 'ACTWRMID',
 'SAT_AVG',
 'SAT_AVG_ALL',
 'PCIP01',
 'PCIP03',
 'PCIP04',
 'PCIP05',
 'PCIP09',
 'PCIP10',
 'PCIP11',
 'PCIP12',
 'PCIP13',
 'PCIP14',
 'PCIP15',
 'PCIP16',
 'PCIP19',
 'PCIP22',
 'PCIP23',
 'PCIP24',
 'PCIP25',
 'PCIP26',
 'PCIP27',
 'PCIP29',
 'PCIP30',
 'PCIP31',
 'PCIP38',
 'PCIP39',
 'PCIP40',
 'PCIP41',
 'PCIP42',
 'PCIP43',
 'PCIP44',
 'PCIP45',
 'PCIP46',
 'PCIP47',
 'PCIP48',
 'PCIP49',
 'PCIP50',
 'PCIP51',
 'PCIP52',
 'PCIP54',
 'CIP01CERT1',
 'CIP01CERT2',
 'CIP01ASSOC',
 'CIP01CERT4',
 'CIP01BACHL',
 'CIP03CERT1',
 'CIP03CERT2',
 'CIP03ASSOC',
 'CIP03CERT4',
 'CIP03BACHL',
 'CIP04CERT1',
 'CIP04CERT2',
 'CIP04ASSOC',
 'CIP04CERT4',
 'CIP04BACHL',
 'CIP05CERT1',
 'CIP05CERT2',
 'CIP05ASSOC',
 'CIP05CERT4',
 'CIP05BACHL',
 'CIP09CERT1',
 'CIP09CERT2',
 'CIP09ASSOC',
 'CIP09CERT4',
 'CIP09BACHL',
 'CIP10CERT1',
 'CIP10CERT2',
 'CIP10ASSOC',
 'CIP10CERT4',
 'CIP10BACHL',
 'CIP11CERT1',
 'CIP11CERT2',
 'CIP11ASSOC',
 'CIP11CERT4',
 'CIP11BACHL',
 'CIP12CERT1',
 'CIP12CERT2',
 'CIP12ASSOC',
 'CIP12CERT4',
 'CIP12BACHL',
 'CIP13CERT1',
 'CIP13CERT2',
 'CIP13ASSOC',
 'CIP13CERT4',
 'CIP13BACHL',
 'CIP14CERT1',
 'CIP14CERT2',
 'CIP14ASSOC',
 'CIP14CERT4',
 'CIP14BACHL',
 'CIP15CERT1',
 'CIP15CERT2',
 'CIP15ASSOC',
 'CIP15CERT4',
 'CIP15BACHL',
 'CIP16CERT1',
 'CIP16CERT2',
 'CIP16ASSOC',
 'CIP16CERT4',
 'CIP16BACHL',
 'CIP19CERT1',
 'CIP19CERT2',
 'CIP19ASSOC',
 'CIP19CERT4',
 'CIP19BACHL',
 'CIP22CERT1',
 'CIP22CERT2',
 'CIP22ASSOC',
 'CIP22CERT4',
 'CIP22BACHL',
 'CIP23CERT1',
 'CIP23CERT2',
 'CIP23ASSOC',
 'CIP23CERT4',
 'CIP23BACHL',
 'CIP24CERT1',
 'CIP24CERT2',
 'CIP24ASSOC',
 'CIP24CERT4',
 'CIP24BACHL',
 'CIP25CERT1',
 'CIP25CERT2',
 'CIP25ASSOC',
 'CIP25CERT4',
 'CIP25BACHL',
 'CIP26CERT1',
 'CIP26CERT2',
 'CIP26ASSOC',
 'CIP26CERT4',
 'CIP26BACHL',
 'CIP27CERT1',
 'CIP27CERT2',
 'CIP27ASSOC',
 'CIP27CERT4',
 'CIP27BACHL',
 'CIP29CERT1',
 'CIP29CERT2',
 'CIP29ASSOC',
 'CIP29CERT4',
 'CIP29BACHL',
 'CIP30CERT1',
 'CIP30CERT2',
 'CIP30ASSOC',
 'CIP30CERT4',
 'CIP30BACHL',
 'CIP31CERT1',
 'CIP31CERT2',
 'CIP31ASSOC',
 'CIP31CERT4',
 'CIP31BACHL',
 'CIP38CERT1',
 'CIP38CERT2',
 'CIP38ASSOC',
 'CIP38CERT4',
 'CIP38BACHL',
 'CIP39CERT1',
 'CIP39CERT2',
 'CIP39ASSOC',
 'CIP39CERT4',
 'CIP39BACHL',
 'CIP40CERT1',
 'CIP40CERT2',
 'CIP40ASSOC',
 'CIP40CERT4',
 'CIP40BACHL',
 'CIP41CERT1',
 'CIP41CERT2',
 'CIP41ASSOC',
 'CIP41CERT4',
 'CIP41BACHL',
 'CIP42CERT1',
 'CIP42CERT2',
 'CIP42ASSOC',
 'CIP42CERT4',
 'CIP42BACHL',
 'CIP43CERT1',
 'CIP43CERT2',
 'CIP43ASSOC',
 'CIP43CERT4',
 'CIP43BACHL',
 'CIP44CERT1',
 'CIP44CERT2',
 'CIP44ASSOC',
 'CIP44CERT4',
 'CIP44BACHL',
 'CIP45CERT1',
 'CIP45CERT2',
 'CIP45ASSOC',
 'CIP45CERT4',
 'CIP45BACHL',
 'CIP46CERT1',
 'CIP46CERT2',
 'CIP46ASSOC',
 'CIP46CERT4',
 'CIP46BACHL',
 'CIP47CERT1',
 'CIP47CERT2',
 'CIP47ASSOC',
 'CIP47CERT4',
 'CIP47BACHL',
 'CIP48CERT1',
 'CIP48CERT2',
 'CIP48ASSOC',
 'CIP48CERT4',
 'CIP48BACHL',
 'CIP49CERT1',
 'CIP49CERT2',
 'CIP49ASSOC',
 'CIP49CERT4',
 'CIP49BACHL',
 'CIP50CERT1',
 'CIP50CERT2',
 'CIP50ASSOC',
 'CIP50CERT4',
 'CIP50BACHL',
 'CIP51CERT1',
 'CIP51CERT2',
 'CIP51ASSOC',
 'CIP51CERT4',
 'CIP51BACHL',
 'CIP52CERT1',
 'CIP52CERT2',
 'CIP52ASSOC',
 'CIP52CERT4',
 'CIP52BACHL',
 'CIP54CERT1',
 'CIP54CERT2',
 'CIP54ASSOC',
 'CIP54CERT4',
 'CIP54BACHL',
 'DISTANCEONLY',
 'UGDS',
 'UG',
 'UGDS_WHITE',
 'UGDS_BLACK',
 'UGDS_HISP',
 'UGDS_ASIAN',
 'UGDS_AIAN',
 'UGDS_NHPI',
 'UGDS_2MOR',
 'UGDS_NRA',
 'UGDS_UNKN',
 'UGDS_WHITENH',
 'UGDS_BLACKNH',
 'UGDS_API',
 'UGDS_AIANOLD',
 'UGDS_HISPOLD',
 'UG_NRA',
 'UG_UNKN',
 'UG_WHITENH',
 'UG_BLACKNH',
 'UG_API',
 'UG_AIANOLD',
 'UG_HISPOLD',
 'PPTUG_EF',
 'PPTUG_EF2',
 'CURROPER',
 'NPT4_PUB',
 'NPT4_PRIV',
 'NPT4_PROG',
 'NPT4_OTHER',
 'NPT41_PUB',
 'NPT42_PUB',
 'NPT43_PUB',
 'NPT44_PUB',
 'NPT45_PUB',
 'NPT41_PRIV',
 'NPT42_PRIV',
 'NPT43_PRIV',
 'NPT44_PRIV',
 'NPT45_PRIV',
 'NPT41_PROG',
 'NPT42_PROG',
 'NPT43_PROG',
 'NPT44_PROG',
 'NPT45_PROG',
 'NPT41_OTHER',
 'NPT42_OTHER',
 'NPT43_OTHER',
 'NPT44_OTHER',
 'NPT45_OTHER',
 'NPT4_048_PUB',
 'NPT4_048_PRIV',
 'NPT4_048_PROG',
 'NPT4_048_OTHER',
 'NPT4_3075_PUB',
 'NPT4_3075_PRIV',
 'NPT4_75UP_PUB',
 'NPT4_75UP_PRIV',
 'NPT4_3075_PROG',
 'NPT4_3075_OTHER',
 'NPT4_75UP_PROG',
 'NPT4_75UP_OTHER',
 'NUM4_PUB',
 'NUM4_PRIV',
 'NUM4_PROG',
 'NUM4_OTHER',
 'NUM41_PUB',
 'NUM42_PUB',
 'NUM43_PUB',
 'NUM44_PUB',
 'NUM45_PUB',
 'NUM41_PRIV',
 'NUM42_PRIV',
 'NUM43_PRIV',
 'NUM44_PRIV',
 'NUM45_PRIV',
 'NUM41_PROG',
 'NUM42_PROG',
 'NUM43_PROG',
 'NUM44_PROG',
 'NUM45_PROG',
 'NUM41_OTHER',
 'NUM42_OTHER',
 'NUM43_OTHER',
 'NUM44_OTHER',
 'NUM45_OTHER',
 'COSTT4_A',
 'COSTT4_P',
 'TUITIONFEE_IN',
 'TUITIONFEE_OUT',
 'TUITIONFEE_PROG',
 'TUITFTE',
 'INEXPFTE',
 'AVGFACSAL',
 'PFTFAC',
 'PCTPELL',
 'C150_4',
 'C150_L4',
 'C150_4_POOLED',
 'C150_L4_POOLED',
 'POOLYRS',
 'PFTFTUG1_EF',
 'D150_4',
 'D150_L4',
 'D150_4_POOLED',
 'D150_L4_POOLED',
 'C150_4_WHITE',
 'C150_4_BLACK',
 'C150_4_HISP',
 'C150_4_ASIAN',
 'C150_4_AIAN',
 'C150_4_NHPI',
 'C150_4_2MOR',
 'C150_4_NRA',
 'C150_4_UNKN',
 'C150_4_WHITENH',
 'C150_4_BLACKNH',
 'C150_4_API',
 'C150_4_AIANOLD',
 'C150_4_HISPOLD',
 'C150_L4_WHITE',
 'C150_L4_BLACK',
 'C150_L4_HISP',
 'C150_L4_ASIAN',
 'C150_L4_AIAN',
 'C150_L4_NHPI',
 'C150_L4_2MOR',
 'C150_L4_NRA',
 'C150_L4_UNKN',
 'C150_L4_WHITENH',
 'C150_L4_BLACKNH',
 'C150_L4_API',
 'C150_L4_AIANOLD',
 'C150_L4_HISPOLD',
 'C200_4',
 'C200_L4',
 'D200_4',
 'D200_L4',
 'RET_FT4',
 'RET_FTL4',
 'RET_PT4',
 'RET_PTL4',
 'C200_4_POOLED',
 'C200_L4_POOLED',
 'POOLYRS200',
 'D200_4_POOLED',
 'D200_L4_POOLED',
 'PCTFLOAN',
 'UG25ABV',
 'CDR2',
 'CDR3',
 'DEATH_YR2_RT',
 'COMP_ORIG_YR2_RT',
 'COMP_4YR_TRANS_YR2_RT',
 'COMP_2YR_TRANS_YR2_RT',
 'WDRAW_ORIG_YR2_RT',
 'WDRAW_4YR_TRANS_YR2_RT',
 'WDRAW_2YR_TRANS_YR2_RT',
 'ENRL_ORIG_YR2_RT',
 'ENRL_4YR_TRANS_YR2_RT',
 'ENRL_2YR_TRANS_YR2_RT',
 'UNKN_ORIG_YR2_RT',
 'UNKN_4YR_TRANS_YR2_RT',
 'UNKN_2YR_TRANS_YR2_RT',
 'LO_INC_DEATH_YR2_RT',
 'LO_INC_COMP_ORIG_YR2_RT',
 'LO_INC_COMP_4YR_TRANS_YR2_RT',
 'LO_INC_COMP_2YR_TRANS_YR2_RT',
 'LO_INC_WDRAW_ORIG_YR2_RT',
 'LO_INC_WDRAW_4YR_TRANS_YR2_RT',
 'LO_INC_WDRAW_2YR_TRANS_YR2_RT',
 'LO_INC_ENRL_ORIG_YR2_RT',
 'LO_INC_ENRL_4YR_TRANS_YR2_RT',
 'LO_INC_ENRL_2YR_TRANS_YR2_RT',
 'LO_INC_UNKN_ORIG_YR2_RT',
 'LO_INC_UNKN_4YR_TRANS_YR2_RT',
 'LO_INC_UNKN_2YR_TRANS_YR2_RT',
 'MD_INC_DEATH_YR2_RT',
 'MD_INC_COMP_ORIG_YR2_RT',
 'MD_INC_COMP_4YR_TRANS_YR2_RT',
 'MD_INC_COMP_2YR_TRANS_YR2_RT',
 'MD_INC_WDRAW_ORIG_YR2_RT',
 'MD_INC_WDRAW_4YR_TRANS_YR2_RT',
 'MD_INC_WDRAW_2YR_TRANS_YR2_RT',
 'MD_INC_ENRL_ORIG_YR2_RT',
 'MD_INC_ENRL_4YR_TRANS_YR2_RT',
 'MD_INC_ENRL_2YR_TRANS_YR2_RT',
 'MD_INC_UNKN_ORIG_YR2_RT',
 'MD_INC_UNKN_4YR_TRANS_YR2_RT',
 'MD_INC_UNKN_2YR_TRANS_YR2_RT',
 'HI_INC_DEATH_YR2_RT',
 'HI_INC_COMP_ORIG_YR2_RT',
 'HI_INC_COMP_4YR_TRANS_YR2_RT',
 'HI_INC_COMP_2YR_TRANS_YR2_RT',
 'HI_INC_WDRAW_ORIG_YR2_RT',
 'HI_INC_WDRAW_4YR_TRANS_YR2_RT',
 'HI_INC_WDRAW_2YR_TRANS_YR2_RT',
 'HI_INC_ENRL_ORIG_YR2_RT',
 'HI_INC_ENRL_4YR_TRANS_YR2_RT',
 'HI_INC_ENRL_2YR_TRANS_YR2_RT',
 'HI_INC_UNKN_ORIG_YR2_RT',
 'HI_INC_UNKN_4YR_TRANS_YR2_RT',
 'HI_INC_UNKN_2YR_TRANS_YR2_RT',
 'DEP_DEATH_YR2_RT',
 'DEP_COMP_ORIG_YR2_RT',
 'DEP_COMP_4YR_TRANS_YR2_RT',
 'DEP_COMP_2YR_TRANS_YR2_RT',
 'DEP_WDRAW_ORIG_YR2_RT',
 'DEP_WDRAW_4YR_TRANS_YR2_RT',
 'DEP_WDRAW_2YR_TRANS_YR2_RT',
 'DEP_ENRL_ORIG_YR2_RT',
 'DEP_ENRL_4YR_TRANS_YR2_RT',
 'DEP_ENRL_2YR_TRANS_YR2_RT',
 'DEP_UNKN_ORIG_YR2_RT',
 'DEP_UNKN_4YR_TRANS_YR2_RT',
 'DEP_UNKN_2YR_TRANS_YR2_RT',
 'IND_DEATH_YR2_RT',
 'IND_COMP_ORIG_YR2_RT',
 'IND_COMP_4YR_TRANS_YR2_RT',
 'IND_COMP_2YR_TRANS_YR2_RT',
 'IND_WDRAW_ORIG_YR2_RT',
 'IND_WDRAW_4YR_TRANS_YR2_RT',
 'IND_WDRAW_2YR_TRANS_YR2_RT',
 'IND_ENRL_ORIG_YR2_RT',
 'IND_ENRL_4YR_TRANS_YR2_RT',
 'IND_ENRL_2YR_TRANS_YR2_RT',
 'IND_UNKN_ORIG_YR2_RT',
 'IND_UNKN_4YR_TRANS_YR2_RT',
 'IND_UNKN_2YR_TRANS_YR2_RT',
 'FEMALE_DEATH_YR2_RT',
 'FEMALE_COMP_ORIG_YR2_RT',
 'FEMALE_COMP_4YR_TRANS_YR2_RT',
 'FEMALE_COMP_2YR_TRANS_YR2_RT',
 'FEMALE_WDRAW_ORIG_YR2_RT',
 'FEMALE_WDRAW_4YR_TRANS_YR2_RT',
 'FEMALE_WDRAW_2YR_TRANS_YR2_RT',
 'FEMALE_ENRL_ORIG_YR2_RT',
 'FEMALE_ENRL_4YR_TRANS_YR2_RT',
 'FEMALE_ENRL_2YR_TRANS_YR2_RT',
 'FEMALE_UNKN_ORIG_YR2_RT',
 'FEMALE_UNKN_4YR_TRANS_YR2_RT',
 'FEMALE_UNKN_2YR_TRANS_YR2_RT',
 'MALE_DEATH_YR2_RT',
 'MALE_COMP_ORIG_YR2_RT',
 'MALE_COMP_4YR_TRANS_YR2_RT',
 'MALE_COMP_2YR_TRANS_YR2_RT',
 'MALE_WDRAW_ORIG_YR2_RT',
 'MALE_WDRAW_4YR_TRANS_YR2_RT',
 'MALE_WDRAW_2YR_TRANS_YR2_RT',
 'MALE_ENRL_ORIG_YR2_RT',
 'MALE_ENRL_4YR_TRANS_YR2_RT',
 'MALE_ENRL_2YR_TRANS_YR2_RT',
 'MALE_UNKN_ORIG_YR2_RT',
 'MALE_UNKN_4YR_TRANS_YR2_RT',
 'MALE_UNKN_2YR_TRANS_YR2_RT',
 'PELL_DEATH_YR2_RT',
 'PELL_COMP_ORIG_YR2_RT',
 'PELL_COMP_4YR_TRANS_YR2_RT',
 'PELL_COMP_2YR_TRANS_YR2_RT',
 'PELL_WDRAW_ORIG_YR2_RT',
 'PELL_WDRAW_4YR_TRANS_YR2_RT',
 'PELL_WDRAW_2YR_TRANS_YR2_RT',
 'PELL_ENRL_ORIG_YR2_RT',
 'PELL_ENRL_4YR_TRANS_YR2_RT',
 'PELL_ENRL_2YR_TRANS_YR2_RT',
 'PELL_UNKN_ORIG_YR2_RT',
 'PELL_UNKN_4YR_TRANS_YR2_RT',
 'PELL_UNKN_2YR_TRANS_YR2_RT',
 'NOPELL_DEATH_YR2_RT',
 'NOPELL_COMP_ORIG_YR2_RT',
 'NOPELL_COMP_4YR_TRANS_YR2_RT',
 'NOPELL_COMP_2YR_TRANS_YR2_RT',
 'NOPELL_WDRAW_ORIG_YR2_RT',
 'NOPELL_WDRAW_4YR_TRANS_YR2_RT',
 'NOPELL_WDRAW_2YR_TRANS_YR2_RT',
 'NOPELL_ENRL_ORIG_YR2_RT',
 'NOPELL_ENRL_4YR_TRANS_YR2_RT',
 'NOPELL_ENRL_2YR_TRANS_YR2_RT',
 'NOPELL_UNKN_ORIG_YR2_RT',
 'NOPELL_UNKN_4YR_TRANS_YR2_RT',
 'NOPELL_UNKN_2YR_TRANS_YR2_RT',
 'LOAN_DEATH_YR2_RT',
 'LOAN_COMP_ORIG_YR2_RT',
 'LOAN_COMP_4YR_TRANS_YR2_RT',
 'LOAN_COMP_2YR_TRANS_YR2_RT',
 'LOAN_WDRAW_ORIG_YR2_RT',
 'LOAN_WDRAW_4YR_TRANS_YR2_RT',
 'LOAN_WDRAW_2YR_TRANS_YR2_RT',
 'LOAN_ENRL_ORIG_YR2_RT',
 'LOAN_ENRL_4YR_TRANS_YR2_RT',
 'LOAN_ENRL_2YR_TRANS_YR2_RT',
 'LOAN_UNKN_ORIG_YR2_RT',
 'LOAN_UNKN_4YR_TRANS_YR2_RT',
 'LOAN_UNKN_2YR_TRANS_YR2_RT',
 'NOLOAN_DEATH_YR2_RT',
 'NOLOAN_COMP_ORIG_YR2_RT',
 'NOLOAN_COMP_4YR_TRANS_YR2_RT',
 'NOLOAN_COMP_2YR_TRANS_YR2_RT',
 'NOLOAN_WDRAW_ORIG_YR2_RT',
 'NOLOAN_WDRAW_4YR_TRANS_YR2_RT',
 'NOLOAN_WDRAW_2YR_TRANS_YR2_RT',
 'NOLOAN_ENRL_ORIG_YR2_RT',
 'NOLOAN_ENRL_4YR_TRANS_YR2_RT',
 'NOLOAN_ENRL_2YR_TRANS_YR2_RT',
 'NOLOAN_UNKN_ORIG_YR2_RT',
 'NOLOAN_UNKN_4YR_TRANS_YR2_RT',
 'NOLOAN_UNKN_2YR_TRANS_YR2_RT',
 'FIRSTGEN_DEATH_YR2_RT',
 'FIRSTGEN_COMP_ORIG_YR2_RT',
 'FIRSTGEN_COMP_4YR_TRANS_YR2_RT',
 'FIRSTGEN_COMP_2YR_TRANS_YR2_RT',
 'FIRSTGEN_WDRAW_ORIG_YR2_RT',
 'FIRSTGEN_WDRAW_4YR_TRANS_YR2_RT',
 'FIRSTGEN_WDRAW_2YR_TRANS_YR2_RT',
 'FIRSTGEN_ENRL_ORIG_YR2_RT',
 'FIRSTGEN_ENRL_4YR_TRANS_YR2_RT',
 'FIRSTGEN_ENRL_2YR_TRANS_YR2_RT',
 'FIRSTGEN_UNKN_ORIG_YR2_RT',
 'FIRSTGEN_UNKN_4YR_TRANS_YR2_RT',
 'FIRSTGEN_UNKN_2YR_TRANS_YR2_RT',
 'NOT1STGEN_DEATH_YR2_RT',
 'NOT1STGEN_COMP_ORIG_YR2_RT',
 'NOT1STGEN_COMP_4YR_TRANS_YR2_RT',
 'NOT1STGEN_COMP_2YR_TRANS_YR2_RT',
 'NOT1STGEN_WDRAW_ORIG_YR2_RT',
 'NOT1STGEN_WDRAW_4YR_TRANS_YR2_RT',
 'NOT1STGEN_WDRAW_2YR_TRANS_YR2_RT',
 'NOT1STGEN_ENRL_ORIG_YR2_RT',
 'NOT1STGEN_ENRL_4YR_TRANS_YR2_RT',
 'NOT1STGEN_ENRL_2YR_TRANS_YR2_RT',
 'NOT1STGEN_UNKN_ORIG_YR2_RT',
 'NOT1STGEN_UNKN_4YR_TRANS_YR2_RT',
 'NOT1STGEN_UNKN_2YR_TRANS_YR2_RT',
 'DEATH_YR3_RT',
 'COMP_ORIG_YR3_RT',
 'COMP_4YR_TRANS_YR3_RT',
 'COMP_2YR_TRANS_YR3_RT',
 'WDRAW_ORIG_YR3_RT',
 'WDRAW_4YR_TRANS_YR3_RT',
 'WDRAW_2YR_TRANS_YR3_RT',
 'ENRL_ORIG_YR3_RT',
 'ENRL_4YR_TRANS_YR3_RT',
 'ENRL_2YR_TRANS_YR3_RT',
 'UNKN_ORIG_YR3_RT',
 'UNKN_4YR_TRANS_YR3_RT',
 'UNKN_2YR_TRANS_YR3_RT',
 'LO_INC_DEATH_YR3_RT',
 'LO_INC_COMP_ORIG_YR3_RT',
 'LO_INC_COMP_4YR_TRANS_YR3_RT',
 'LO_INC_COMP_2YR_TRANS_YR3_RT',
 'LO_INC_WDRAW_ORIG_YR3_RT',
 'LO_INC_WDRAW_4YR_TRANS_YR3_RT',
 'LO_INC_WDRAW_2YR_TRANS_YR3_RT',
 'LO_INC_ENRL_ORIG_YR3_RT',
 'LO_INC_ENRL_4YR_TRANS_YR3_RT',
 'LO_INC_ENRL_2YR_TRANS_YR3_RT',
 'LO_INC_UNKN_ORIG_YR3_RT',
 'LO_INC_UNKN_4YR_TRANS_YR3_RT',
 'LO_INC_UNKN_2YR_TRANS_YR3_RT',
 'MD_INC_DEATH_YR3_RT',
 'MD_INC_COMP_ORIG_YR3_RT',
 'MD_INC_COMP_4YR_TRANS_YR3_RT',
 'MD_INC_COMP_2YR_TRANS_YR3_RT',
 'MD_INC_WDRAW_ORIG_YR3_RT',
 'MD_INC_WDRAW_4YR_TRANS_YR3_RT',
 'MD_INC_WDRAW_2YR_TRANS_YR3_RT',
 'MD_INC_ENRL_ORIG_YR3_RT',
 'MD_INC_ENRL_4YR_TRANS_YR3_RT',
 'MD_INC_ENRL_2YR_TRANS_YR3_RT',
 'MD_INC_UNKN_ORIG_YR3_RT',
 'MD_INC_UNKN_4YR_TRANS_YR3_RT',
 'MD_INC_UNKN_2YR_TRANS_YR3_RT',
 'HI_INC_DEATH_YR3_RT',
 'HI_INC_COMP_ORIG_YR3_RT',
 'HI_INC_COMP_4YR_TRANS_YR3_RT',
 'HI_INC_COMP_2YR_TRANS_YR3_RT',
 'HI_INC_WDRAW_ORIG_YR3_RT',
 'HI_INC_WDRAW_4YR_TRANS_YR3_RT',
 'HI_INC_WDRAW_2YR_TRANS_YR3_RT',
 'HI_INC_ENRL_ORIG_YR3_RT',
 'HI_INC_ENRL_4YR_TRANS_YR3_RT',
 'HI_INC_ENRL_2YR_TRANS_YR3_RT',
 'HI_INC_UNKN_ORIG_YR3_RT',
 'HI_INC_UNKN_4YR_TRANS_YR3_RT',
 'HI_INC_UNKN_2YR_TRANS_YR3_RT',
 'DEP_DEATH_YR3_RT',
 'DEP_COMP_ORIG_YR3_RT',
 'DEP_COMP_4YR_TRANS_YR3_RT',
 'DEP_COMP_2YR_TRANS_YR3_RT',
 'DEP_WDRAW_ORIG_YR3_RT',
 'DEP_WDRAW_4YR_TRANS_YR3_RT',
 'DEP_WDRAW_2YR_TRANS_YR3_RT',
 'DEP_ENRL_ORIG_YR3_RT',
 'DEP_ENRL_4YR_TRANS_YR3_RT',
 'DEP_ENRL_2YR_TRANS_YR3_RT',
 'DEP_UNKN_ORIG_YR3_RT',
 'DEP_UNKN_4YR_TRANS_YR3_RT',
 'DEP_UNKN_2YR_TRANS_YR3_RT',
 'IND_DEATH_YR3_RT',
 'IND_COMP_ORIG_YR3_RT',
 'IND_COMP_4YR_TRANS_YR3_RT',
 'IND_COMP_2YR_TRANS_YR3_RT',
 'IND_WDRAW_ORIG_YR3_RT',
 'IND_WDRAW_4YR_TRANS_YR3_RT',
 'IND_WDRAW_2YR_TRANS_YR3_RT',
 'IND_ENRL_ORIG_YR3_RT',
 'IND_ENRL_4YR_TRANS_YR3_RT',
 'IND_ENRL_2YR_TRANS_YR3_RT',
 'IND_UNKN_ORIG_YR3_RT',
 'IND_UNKN_4YR_TRANS_YR3_RT',
 'IND_UNKN_2YR_TRANS_YR3_RT',
 'FEMALE_DEATH_YR3_RT',
 'FEMALE_COMP_ORIG_YR3_RT',
 'FEMALE_COMP_4YR_TRANS_YR3_RT',
 'FEMALE_COMP_2YR_TRANS_YR3_RT',
 'FEMALE_WDRAW_ORIG_YR3_RT',
 'FEMALE_WDRAW_4YR_TRANS_YR3_RT',
 'FEMALE_WDRAW_2YR_TRANS_YR3_RT',
 'FEMALE_ENRL_ORIG_YR3_RT',
 'FEMALE_ENRL_4YR_TRANS_YR3_RT',
 'FEMALE_ENRL_2YR_TRANS_YR3_RT',
 'FEMALE_UNKN_ORIG_YR3_RT',
 'FEMALE_UNKN_4YR_TRANS_YR3_RT',
 'FEMALE_UNKN_2YR_TRANS_YR3_RT',
 'MALE_DEATH_YR3_RT',
 'MALE_COMP_ORIG_YR3_RT',
 'MALE_COMP_4YR_TRANS_YR3_RT',
 'MALE_COMP_2YR_TRANS_YR3_RT',
 'MALE_WDRAW_ORIG_YR3_RT',
 'MALE_WDRAW_4YR_TRANS_YR3_RT',
 'MALE_WDRAW_2YR_TRANS_YR3_RT',
 'MALE_ENRL_ORIG_YR3_RT',
 'MALE_ENRL_4YR_TRANS_YR3_RT',
 'MALE_ENRL_2YR_TRANS_YR3_RT',
 'MALE_UNKN_ORIG_YR3_RT',
 'MALE_UNKN_4YR_TRANS_YR3_RT',
 'MALE_UNKN_2YR_TRANS_YR3_RT',
 'PELL_DEATH_YR3_RT',
 'PELL_COMP_ORIG_YR3_RT',
 'PELL_COMP_4YR_TRANS_YR3_RT',
 'PELL_COMP_2YR_TRANS_YR3_RT',
 'PELL_WDRAW_ORIG_YR3_RT',
 'PELL_WDRAW_4YR_TRANS_YR3_RT',
 'PELL_WDRAW_2YR_TRANS_YR3_RT',
 'PELL_ENRL_ORIG_YR3_RT',
 'PELL_ENRL_4YR_TRANS_YR3_RT',
 'PELL_ENRL_2YR_TRANS_YR3_RT',
 'PELL_UNKN_ORIG_YR3_RT',
 'PELL_UNKN_4YR_TRANS_YR3_RT',
 'PELL_UNKN_2YR_TRANS_YR3_RT',
 'NOPELL_DEATH_YR3_RT',
 'NOPELL_COMP_ORIG_YR3_RT',
 'NOPELL_COMP_4YR_TRANS_YR3_RT',
 'NOPELL_COMP_2YR_TRANS_YR3_RT',
 'NOPELL_WDRAW_ORIG_YR3_RT',
 'NOPELL_WDRAW_4YR_TRANS_YR3_RT',
 'NOPELL_WDRAW_2YR_TRANS_YR3_RT',
 'NOPELL_ENRL_ORIG_YR3_RT',
 'NOPELL_ENRL_4YR_TRANS_YR3_RT',
 'NOPELL_ENRL_2YR_TRANS_YR3_RT',
 'NOPELL_UNKN_ORIG_YR3_RT',
 'NOPELL_UNKN_4YR_TRANS_YR3_RT',
 'NOPELL_UNKN_2YR_TRANS_YR3_RT',
 'LOAN_DEATH_YR3_RT',
 'LOAN_COMP_ORIG_YR3_RT',
 'LOAN_COMP_4YR_TRANS_YR3_RT',
 'LOAN_COMP_2YR_TRANS_YR3_RT',
 'LOAN_WDRAW_ORIG_YR3_RT',
 'LOAN_WDRAW_4YR_TRANS_YR3_RT',
 'LOAN_WDRAW_2YR_TRANS_YR3_RT',
 'LOAN_ENRL_ORIG_YR3_RT',
 'LOAN_ENRL_4YR_TRANS_YR3_RT',
 'LOAN_ENRL_2YR_TRANS_YR3_RT',
 'LOAN_UNKN_ORIG_YR3_RT',
 'LOAN_UNKN_4YR_TRANS_YR3_RT',
 'LOAN_UNKN_2YR_TRANS_YR3_RT',
 'NOLOAN_DEATH_YR3_RT',
 'NOLOAN_COMP_ORIG_YR3_RT',
 'NOLOAN_COMP_4YR_TRANS_YR3_RT',
 'NOLOAN_COMP_2YR_TRANS_YR3_RT',
 'NOLOAN_WDRAW_ORIG_YR3_RT',
 'NOLOAN_WDRAW_4YR_TRANS_YR3_RT',
 'NOLOAN_WDRAW_2YR_TRANS_YR3_RT',
 'NOLOAN_ENRL_ORIG_YR3_RT',
 'NOLOAN_ENRL_4YR_TRANS_YR3_RT',
 'NOLOAN_ENRL_2YR_TRANS_YR3_RT',
 'NOLOAN_UNKN_ORIG_YR3_RT',
 'NOLOAN_UNKN_4YR_TRANS_YR3_RT',
 'NOLOAN_UNKN_2YR_TRANS_YR3_RT',
 'FIRSTGEN_DEATH_YR3_RT',
 'FIRSTGEN_COMP_ORIG_YR3_RT',
 'FIRSTGEN_COMP_4YR_TRANS_YR3_RT',
 'FIRSTGEN_COMP_2YR_TRANS_YR3_RT',
 'FIRSTGEN_WDRAW_ORIG_YR3_RT',
 'FIRSTGEN_WDRAW_4YR_TRANS_YR3_RT',
 'FIRSTGEN_WDRAW_2YR_TRANS_YR3_RT',
 'FIRSTGEN_ENRL_ORIG_YR3_RT',
 'FIRSTGEN_ENRL_4YR_TRANS_YR3_RT',
 'FIRSTGEN_ENRL_2YR_TRANS_YR3_RT',
 'FIRSTGEN_UNKN_ORIG_YR3_RT',
 'FIRSTGEN_UNKN_4YR_TRANS_YR3_RT',
 'FIRSTGEN_UNKN_2YR_TRANS_YR3_RT',
 'NOT1STGEN_DEATH_YR3_RT',
 'NOT1STGEN_COMP_ORIG_YR3_RT',
 'NOT1STGEN_COMP_4YR_TRANS_YR3_RT',
 'NOT1STGEN_COMP_2YR_TRANS_YR3_RT',
 'NOT1STGEN_WDRAW_ORIG_YR3_RT',
 'NOT1STGEN_WDRAW_4YR_TRANS_YR3_RT',
 'NOT1STGEN_WDRAW_2YR_TRANS_YR3_RT',
 'NOT1STGEN_ENRL_ORIG_YR3_RT',
 'NOT1STGEN_ENRL_4YR_TRANS_YR3_RT',
 'NOT1STGEN_ENRL_2YR_TRANS_YR3_RT',
 'NOT1STGEN_UNKN_ORIG_YR3_RT',
 'NOT1STGEN_UNKN_4YR_TRANS_YR3_RT',
 'NOT1STGEN_UNKN_2YR_TRANS_YR3_RT',
 'DEATH_YR4_RT',
 'COMP_ORIG_YR4_RT',
 'COMP_4YR_TRANS_YR4_RT',
 'COMP_2YR_TRANS_YR4_RT',
 'WDRAW_ORIG_YR4_RT',
 'WDRAW_4YR_TRANS_YR4_RT',
 'WDRAW_2YR_TRANS_YR4_RT',
 'ENRL_ORIG_YR4_RT',
 'ENRL_4YR_TRANS_YR4_RT',
 'ENRL_2YR_TRANS_YR4_RT',
 'UNKN_ORIG_YR4_RT',
 'UNKN_4YR_TRANS_YR4_RT',
 'UNKN_2YR_TRANS_YR4_RT',
 'LO_INC_DEATH_YR4_RT',
 'LO_INC_COMP_ORIG_YR4_RT',
 'LO_INC_COMP_4YR_TRANS_YR4_RT',
 'LO_INC_COMP_2YR_TRANS_YR4_RT',
 'LO_INC_WDRAW_ORIG_YR4_RT',
 'LO_INC_WDRAW_4YR_TRANS_YR4_RT',
 'LO_INC_WDRAW_2YR_TRANS_YR4_RT',
 'LO_INC_ENRL_ORIG_YR4_RT',
 'LO_INC_ENRL_4YR_TRANS_YR4_RT',
 'LO_INC_ENRL_2YR_TRANS_YR4_RT',
 'LO_INC_UNKN_ORIG_YR4_RT',
 'LO_INC_UNKN_4YR_TRANS_YR4_RT',
 'LO_INC_UNKN_2YR_TRANS_YR4_RT',
 'MD_INC_DEATH_YR4_RT',
 'MD_INC_COMP_ORIG_YR4_RT',
 'MD_INC_COMP_4YR_TRANS_YR4_RT',
 'MD_INC_COMP_2YR_TRANS_YR4_RT',
 'MD_INC_WDRAW_ORIG_YR4_RT',
 'MD_INC_WDRAW_4YR_TRANS_YR4_RT',
 'MD_INC_WDRAW_2YR_TRANS_YR4_RT',
 'MD_INC_ENRL_ORIG_YR4_RT',
 'MD_INC_ENRL_4YR_TRANS_YR4_RT',
 'MD_INC_ENRL_2YR_TRANS_YR4_RT',
 'MD_INC_UNKN_ORIG_YR4_RT',
 'MD_INC_UNKN_4YR_TRANS_YR4_RT',
 'MD_INC_UNKN_2YR_TRANS_YR4_RT',
 'HI_INC_DEATH_YR4_RT',
 'HI_INC_COMP_ORIG_YR4_RT',
 'HI_INC_COMP_4YR_TRANS_YR4_RT',
 'HI_INC_COMP_2YR_TRANS_YR4_RT',
 'HI_INC_WDRAW_ORIG_YR4_RT',
 'HI_INC_WDRAW_4YR_TRANS_YR4_RT',
 'HI_INC_WDRAW_2YR_TRANS_YR4_RT',
 'HI_INC_ENRL_ORIG_YR4_RT',
 'HI_INC_ENRL_4YR_TRANS_YR4_RT',
 'HI_INC_ENRL_2YR_TRANS_YR4_RT',
 'HI_INC_UNKN_ORIG_YR4_RT',
 'HI_INC_UNKN_4YR_TRANS_YR4_RT',
 'HI_INC_UNKN_2YR_TRANS_YR4_RT',
 'DEP_DEATH_YR4_RT',
 'DEP_COMP_ORIG_YR4_RT',
 'DEP_COMP_4YR_TRANS_YR4_RT',
 'DEP_COMP_2YR_TRANS_YR4_RT',
 'DEP_WDRAW_ORIG_YR4_RT',
 'DEP_WDRAW_4YR_TRANS_YR4_RT',
 'DEP_WDRAW_2YR_TRANS_YR4_RT',
 'DEP_ENRL_ORIG_YR4_RT',
 'DEP_ENRL_4YR_TRANS_YR4_RT',
 'DEP_ENRL_2YR_TRANS_YR4_RT',
 'DEP_UNKN_ORIG_YR4_RT',
 'DEP_UNKN_4YR_TRANS_YR4_RT',
 'DEP_UNKN_2YR_TRANS_YR4_RT',
 'IND_DEATH_YR4_RT',
 'IND_COMP_ORIG_YR4_RT',
 'IND_COMP_4YR_TRANS_YR4_RT',
 'IND_COMP_2YR_TRANS_YR4_RT',
 'IND_WDRAW_ORIG_YR4_RT',
 'IND_WDRAW_4YR_TRANS_YR4_RT',
 'IND_WDRAW_2YR_TRANS_YR4_RT',
 'IND_ENRL_ORIG_YR4_RT',
 'IND_ENRL_4YR_TRANS_YR4_RT',
 'IND_ENRL_2YR_TRANS_YR4_RT',
 'IND_UNKN_ORIG_YR4_RT',
 'IND_UNKN_4YR_TRANS_YR4_RT',
 'IND_UNKN_2YR_TRANS_YR4_RT',
 'FEMALE_DEATH_YR4_RT',
 'FEMALE_COMP_ORIG_YR4_RT',
 'FEMALE_COMP_4YR_TRANS_YR4_RT',
 'FEMALE_COMP_2YR_TRANS_YR4_RT',
 'FEMALE_WDRAW_ORIG_YR4_RT',
 'FEMALE_WDRAW_4YR_TRANS_YR4_RT',
 'FEMALE_WDRAW_2YR_TRANS_YR4_RT',
 'FEMALE_ENRL_ORIG_YR4_RT',
 'FEMALE_ENRL_4YR_TRANS_YR4_RT',
 'FEMALE_ENRL_2YR_TRANS_YR4_RT',
 'FEMALE_UNKN_ORIG_YR4_RT',
 'FEMALE_UNKN_4YR_TRANS_YR4_RT',
 'FEMALE_UNKN_2YR_TRANS_YR4_RT',
 'MALE_DEATH_YR4_RT',
 'MALE_COMP_ORIG_YR4_RT',
 'MALE_COMP_4YR_TRANS_YR4_RT',
 'MALE_COMP_2YR_TRANS_YR4_RT',

In [13]:
filtered_variable_name_list = column_heading_df['VARIABLE NAME'].unique().tolist()
filtered_variable_name_list.append('UGDS')

In [14]:
filtered_df = df.copy()

In [15]:
#for variable in complete_variable_name_list:
#    if variable not in filtered_variable_name_list:
#        filtered_df.drop(columns = variable, inplace = True)

In [16]:
filtered_df

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,ACCREDAGENCY,INSTURL,NPCURL,...,OMENRUP_PARTTIME_POOLED_SUPP,FTFTPCTPELL,FTFTPCTFLOAN,UG12MN,G12MN,SCUGFFN,POOLYRS_FTFTAIDPCT,FTFTPCTPELL_POOLED_SUPP,FTFTPCTFLOAN_POOLED_SUPP,SCUGFFN_POOLED
0,100654,100200,1002,Alabama A & M University,Normal,AL,35762,Southern Association of Colleges and Schools C...,www.aamu.edu/,www.aamu.edu/admissions-aid/tuition-fees/net-p...,...,0.3193,0.7057,0.7143,5343.0,1165.0,1288.0,2.0,0.7083,0.7287,2698.0
1,100663,105200,1052,University of Alabama at Birmingham,Birmingham,AL,35294-0110,Southern Association of Colleges and Schools C...,https://www.uab.edu,https://uab.studentaidcalculator.com/survey.aspx,...,0.2475,0.3788,0.5350,14445.0,10498.0,2228.0,2.0,0.3891,0.5414,4176.0
2,100690,2503400,25034,Amridge University,Montgomery,AL,36117-3553,Southern Association of Colleges and Schools C...,www.amridgeuniversity.edu,www2.amridgeuniversity.edu:9091/,...,0.2836,1.0000,1.0000,440.0,527.0,5.0,4.0,NaN,NaN,24.0
3,100706,105500,1055,University of Alabama in Huntsville,Huntsville,AL,35899,Southern Association of Colleges and Schools C...,www.uah.edu,finaid.uah.edu/,...,0.2496,0.2707,0.4556,8145.0,2443.0,1341.0,2.0,0.2378,0.4402,2544.0
4,100724,100500,1005,Alabama State University,Montgomery,AL,36104-0271,Southern Association of Colleges and Schools C...,www.alasu.edu,www.alasu.edu/cost-aid/tuition-costs/net-price...,...,0.2621,0.7792,0.7539,4732.0,642.0,951.0,2.0,0.7684,0.7464,2094.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6801,48511112,157114,1571,Georgia Military College - Dublin,Dublin,GA,310215149,Southern Association of Colleges and Schools C...,https://www.gmc.edu/index.cms,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6802,48511113,157115,1571,Georgia Military College - Eastman,Eastman,GA,310236109,Southern Association of Colleges and Schools C...,https://www.gmc.edu/index.cms,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6803,48616901,4204801,42048,American College of Barbering - Florence,Florence,KY,410421801,National Accrediting Commission of Career Arts...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6804,49005401,4182601,41826,HCI College - Fort Lauderdale Campus,Fort Lauderdale,FL,33309,Accrediting Commission of Career Schools and C...,www.hci.edu/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6805,49146401,4227001,42270,ABC Adult School - Cabrillo Lane,Cerritos,CA,907037748,Council on Occupational Education,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
filtered_df.columns

Index(['UNITID', 'OPEID', 'OPEID6', 'INSTNM', 'CITY', 'STABBR', 'ZIP',
       'ACCREDAGENCY', 'INSTURL', 'NPCURL',
       ...
       'OMENRUP_PARTTIME_POOLED_SUPP', 'FTFTPCTPELL', 'FTFTPCTFLOAN', 'UG12MN',
       'G12MN', 'SCUGFFN', 'POOLYRS_FTFTAIDPCT', 'FTFTPCTPELL_POOLED_SUPP',
       'FTFTPCTFLOAN_POOLED_SUPP', 'SCUGFFN_POOLED'],
      dtype='object', length=1986)

In [18]:
column_heading_df['dev-category'].unique()

array(['academics', 'admissions', 'aid', 'completion', 'cost', 'earnings',
       'repayment', 'root', 'school', 'student'], dtype=object)

In [19]:
#PREDEG == 3 is the university is predominately a 4 year school.
filtered_4_year_df = filtered_df.loc[df['PREDDEG'] == 3, :]
filtered_4_year_df

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,ACCREDAGENCY,INSTURL,NPCURL,...,OMENRUP_PARTTIME_POOLED_SUPP,FTFTPCTPELL,FTFTPCTFLOAN,UG12MN,G12MN,SCUGFFN,POOLYRS_FTFTAIDPCT,FTFTPCTPELL_POOLED_SUPP,FTFTPCTFLOAN_POOLED_SUPP,SCUGFFN_POOLED
0,100654,100200,1002,Alabama A & M University,Normal,AL,35762,Southern Association of Colleges and Schools C...,www.aamu.edu/,www.aamu.edu/admissions-aid/tuition-fees/net-p...,...,0.3193,0.7057,0.7143,5343.0,1165.0,1288.0,2.0,0.7083,0.7287,2698.0
1,100663,105200,1052,University of Alabama at Birmingham,Birmingham,AL,35294-0110,Southern Association of Colleges and Schools C...,https://www.uab.edu,https://uab.studentaidcalculator.com/survey.aspx,...,0.2475,0.3788,0.5350,14445.0,10498.0,2228.0,2.0,0.3891,0.5414,4176.0
2,100690,2503400,25034,Amridge University,Montgomery,AL,36117-3553,Southern Association of Colleges and Schools C...,www.amridgeuniversity.edu,www2.amridgeuniversity.edu:9091/,...,0.2836,1.0000,1.0000,440.0,527.0,5.0,4.0,NaN,NaN,24.0
3,100706,105500,1055,University of Alabama in Huntsville,Huntsville,AL,35899,Southern Association of Colleges and Schools C...,www.uah.edu,finaid.uah.edu/,...,0.2496,0.2707,0.4556,8145.0,2443.0,1341.0,2.0,0.2378,0.4402,2544.0
4,100724,100500,1005,Alabama State University,Montgomery,AL,36104-0271,Southern Association of Colleges and Schools C...,www.alasu.edu,www.alasu.edu/cost-aid/tuition-costs/net-price...,...,0.2621,0.7792,0.7539,4732.0,642.0,951.0,2.0,0.7684,0.7464,2094.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6299,492069,4276100,42761,Champion Christian College,Hot Springs,AR,71913,Transnational Association of Christian College...,championchristiancollege.com,championchristiancollege.com/NetPriceCalculato...,...,NaN,0.0000,0.0000,57.0,NaN,20.0,4.0,NaN,NaN,20.0
6314,492689,1067401,10674,Texas Tech University Health Sciences Center-E...,El Paso,TX,79905-2827,Southern Association of Colleges and Schools C...,elpaso.ttuhsc.edu/,www.depts.ttu.edu/financialaid/netCostCalcHome...,...,NaN,NaN,NaN,370.0,471.0,0.0,4.0,NaN,NaN,0.0
6318,492759,638521,6385,Chamberlain University-Louisiana,Jefferson,LA,70121,Higher Learning Commission,https://www.chamberlain.edu/,https://www.chamberlain.edu/admissions/financi...,...,NaN,NaN,NaN,21.0,NaN,NaN,NaN,NaN,NaN,NaN
6319,492801,246100,2461,Drury University-College of Continuing Profess...,Springfield,MO,65802,Higher Learning Commission,www.drury.edu/ccps/,tcc.ruffalonl.com/Drury%20University/Freshman-...,...,0.3681,0.7619,0.4048,2857.0,NaN,42.0,2.0,0.7619,0.4048,42.0
6322,492962,180500,1805,Indiana Institute of Technology-College of Pro...,Fort Wayne,IN,46803,Higher Learning Commission,cps.indianatech.edu/,cps.indianatech.edu/costs/,...,0.6939,0.8710,0.8996,6739.0,NaN,279.0,2.0,0.871,0.8996,279.0

In [20]:
filtered_4_year_df['OPEID'].dtypes

dtype('int64')

In [21]:
college_ranking_df = pd.read_csv(path2+forbes_data)

In [22]:
college_ranking_df['OPEID'].dtypes

dtype('int64')

In [23]:
college_ranking_df = college_ranking_df.fillna(0)

In [24]:
college_ranking_df['OPEID'] = college_ranking_df['OPEID'].astype('int')
college_ranking_df.head(51)

,UNITID,OPEID,OPEID6,Rank,Name,City,State,Public/Private,Undergraduate Population,Student Population,Net Price,Average Grant Aid,Total Annual Cost,Alumni Salary,Acceptance Rate,SAT Lower,SAT Upper,ACT Lower,ACT Upper,Website
0,166027,215500,2155,1,Harvard University,Cambridge,MA,Private,13844,31120,14327,49870,69600,146800.0,5.0,1460.0,1590.0,32.0,35.0,www.harvard.edu
1,243744,130500,1305,2,Stanford University,Stanford,CA,Private,8402,17534,13261,50134,69109,145200.0,5.0,1390.0,1540.0,32.0,35.0,www.stanford.edu
2,130794,142600,1426,3,Yale University,New Haven,CT,Private,6483,12974,18627,50897,71290,138300.0,7.0,1460.0,1580.0,32.0,35.0,www.yale.edu
3,166683,217800,2178,4,Massachusetts Institute of Technology,Cambridge,MA,Private,4680,11466,20771,43248,67430,155200.0,7.0,1490.0,1570.0,33.0,35.0,web.mit.edu
4,186131,262700,2627,5,Princeton University,Princeton,NJ,Private,5659,8273,9327,48088,66150,139400.0,6.0,1430.0,1570.0,31.0,35.0,www.princeton.edu
5,215062,337800,3378,6,University of Pennsylvania,Philadelphia,PA,Private,13437,25367,24242,44801,71715,133900.0,9.0,1420.0,1560.0,32.0,35.0,www.upenn.edu
6,217156,340100,3401,7,Brown University,Providence,RI,Private,7390,10095,30205,42455,71050,127600.0,8.0,1405.0,1570.0,31.0,35.0,www.brown.edu
7,110404,113100,1131,8,California Institute of Technology,Pasadena,CA,Private,1002,2238,24245,41408,68901,151600.0,8.0,1530.0,1590.0,34.0,35.0,www.caltech.edu
8,198419,292000,2920,9,Duke University,Durham,NC,Private,7184,16130,35737,47836,71764,132100.0,10.0,1380.0,1540.0,31.0,35.0,www.duke.edu
9,182670,257300,2573,10,Dartmouth College,Hanover,NH,Private,4693,6509,30421,47171,71827,130900.0,10.0,1430.0,1560.0,30.0,34.0,www.dartmouth.edu
10,190415,271100,2711,11,Cornell University,Ithaca,NY,Private,14774,23016,31230,36164,70321,128200.0,13.0,1390.0,1550.0,31.0,34.0,www.cornell.edu
11,121345,117300,1173,12,Pomona College,Claremont,CA,Private,1599,1665,15840,48930,69725,117200.0,8.0,1370.0,1530.0,30.0,34.0,www.pomona.edu
12,110635,131200,1312,13,"University of California, Berkeley",Berkeley,CA,Public,31133,41891,15859,18319,65003,131800.0,17.0,1260.0,1480.0,30.0,34.0,www.berkeley.edu
13,190150,270700,2707,14,Columbia University,New York,NY,Private,8523,30454,24231,49185,74199,126800.0,7.0,1410.0,1570.0,31.0,34.0,www.columbia.edu
14,131496,144500,1445,15,Georgetown University,Washington,DC,Private,8194,19005,30107,41893,71580,122200.0,16.0,1350.0,1520.0,30.0,34.0,www.georgetown.edu
15,144050,177400,1774,16,University of Chicago,Chicago,IL,Private,6915,16227,25455,37883,75735,114200.0,9.0,1480.0,1580.0,32.0,35.0,www.uchicago.edu
16,147767,173900,1739,17,Northwestern University,Evanston,IL,Private,10163,22008,24047,44247,72980,115400.0,9.0,1420.0,1560.0,32.0,34.0,www.northwestern.edu
17,152080,184000,1840,18,University of Notre Dame,Notre Dame,IN,Private,8664,12467,28768,39590,69395,130500.0,19.0,1370.0,1520.0,32.0,34.0,www.nd.edu
18,168342,222900,2229,19,Williams College,Williamstown,MA,Private,2134,2227,22667,48050,70650,127500.0,15.0,1400.0,1570.0,31.0,35.0,www.williams.edu
19,170976,232500,2325,20,"University of Michigan, Ann Arbor",Ann Arbor,MI,Public,29773,46002,14860,18751,62176,112200.0,27.0,1330.0,1500.0,30.0,33.0,www.umich.edu
20,227757,360400,3604,21,Rice University,Houston,TX,Private,4036,7022,20237,36387,63158,129500.0,16.0,1490.0,1580.0,33.0,35.0,www.rice.edu
21,162928,207700,2077,22,Johns Hopkins University,Baltimore,MD,Private,7825,25151,33586,38542,69863,117100.0,13.0,1450.0,1570.0,33.0,35.0,www.jhu.edu
22,115409,117100,1171,23,Harvey Mudd College,Claremont,CA,Private,847,861,34464,33782,74428,158200.0,15.0,1470.0,1570.0,33.0,35.0,www.hmc.edu
23,216287,337000,3370,25,Swarthmore College,Swarthmore,PA,Private,1577,1630,20511,46105,68846,123200.0,11.0,1380.0,1540.0,31.0,34.0,www.swarthmore.edu
24,161004,203800,2038,26,Bowdoin College,Brunswick,ME,Private,1816,1965,22810,41143,68070,112000.0,14.0,0.0,0.0,0.0,0.0,www.bowdoin.edu
25,221999,353500,3535,27,Vanderbilt University,Nashville,TN,Private,7006,12592,19959,41359,67392,119100.0,11.0,1440.0,1570.0,32.0,35.0,www.vanderbilt.edu
26,164465,211500,2115,28,Amherst College,Amherst,MA,Private,1836,1945,22463,49467,71300,116500.0,13.0,1400.0,1560.0,32.0,34.0,https://www.amherst.edu
27,112260,117000,1170,29,Claremont McKenna College,Claremont,CA,Private,1345,1364,26933,40673,71745,125400.0,10.0,1340.0,1510.0,30.0,34.0,www.claremontmckenna.edu
28,123961,132800,1328,30,University of Southern California,Los Angeles,CA,Private,20582,45687,30232,36686,72209,120600.0,16.0,1300.0,1500.0,30.0,34.0,www.usc.edu
29,179867,252000,2520,31,Washington University in St. Louis,St. Louis,MO,Private,8533,15303,28540,41977,71975,114900.0,16.0,1470.0,1570.0,32.0,34.0,www.wustl.edu
30,234076,374500,3745,33,University of Virginia,Charlottesville,VA,Public,18432,24360,20547,21171,62633,117500.0,27.0,1310.0,1500.0,29.0,33.0,www.virginia.edu
31,168148,221900,2219,34,Tufts University,Medford,MA,Private,5960,11449,32620,38605,70600,118100.0,15.0,1410.0,1540.0,31.0,34.0,www.tufts.edu
32,193900,278500,2785,35,New York University,New York,NY,Private,30252,51123,40336,31542,71790,117700.0,28.0,1290.0,1490.0,29.0,33.0,www.nyu.edu
33,230959,369100,3691,36,Middlebury College,Middlebury,VT,Private,2591,3855,26075,43491,69464,109800.0,17.0,1320.0,1510.0,30.0,34.0,www.middlebury.edu
34,211440,324200,3242,37,Carnegie Mellon University,Pittsburgh,PA,Private,6941,13869,31102,38163,70094,136100.0,22.0,1430.0,1560.0,32.0,35.0,www.cmu.edu
35,110662,131500,1315,38,"University of California, Los Angeles",Los Angeles,CA,Public,33148,44027,14309,20011,61915,116100.0,16.0,1220.0,1450.0,29.0,34.0,ucla.edu
36,160977,203600,2036,39,Bates College,Lewiston,ME,Private,1787,1905,25192,43238,68870,111900.0,22.0,0.0,0.0,0.0,0.0,bates.edu
37,130697,142400,1424,40,Wesleyan University,Middletown,CT,Private,3123,3213,29956,43276,69935,117000.0,16.0,0.0,0.0,0.0,0.0,www.wesleyan.edu
38,164924,212800,2128,41,Boston College,Chestnut Hill,MA,Private,10304,14628,34550,40716,70588,115400.0,32.0,1320.0,1490.0,31.0,33.0,www.bc.edu
39,234207,376800,3768,42,Washington and Lee University,Lexington,VA,Private,1855,2220,24761,39671,65950,123200.0,22.0,1350.0,1490.0,31.0,33.0,www.wlu.edu
40,168218,222400,2224,44,Wellesley College,Wellesley,MA,Private,2508,2688,23188,45777,69034,106200.0,22.0,1360.0,1530.0,30.0,33.0,www.wellesley.edu
41,199120,297400,2974,45,"University of North Carolina, Chapel Hill",Chapel Hill,NC,Public,19429,29911,14163,17291,51152,100800.0,24.0,1270.0,1460.0,28.0,33.0,www.unc.edu
42,190099,270100,2701,46,Colgate University,Hamilton,NY,Private,2894,3025,23310,45108,69860,130600.0,28.0,1310.0,1500.0,31.0,33.0,www.colgate.edu
43,231624,370500,3705,47,College of William & Mary,Williamsburg,VA,Public,6822,8740,19720,18738,59012,108900.0,36.0,1300.0,1480.0,29.0,33.0,www.wm.edu
44,198385,291800,2918,48,Davidson College,Davidson,NC,Private,1810,1959,21206,36359,66678,106900.0,20.0,1310.0,1470.0,30.0,33.0,www.davidson.edu
45,212911,327400,3274,49,Haverford College,Haverford,PA,Private,1296,1326,26607,45805,71614,112300.0,20.0,1390.0,1530.0,31.0,34.0,www.haverford.edu
46,189097,270800,2708,50,Barnard College,New York,NY,Private,2544,2668,25007,44776,71282,109800.0,15.0,1310.0,1500.0,30.0,33.0,barnard.edu
47,243744,1305001,1305,51,Santa Clara University,Santa Clara,CA,Private,5754,8629,33738,26671,69439,134700.0,54.0,1270.0,1440.0,28.0,32.0,www.scu.edu
48,173258,234000,2340,52,Carleton College,Northfield,MN,Private,2078,2155,27898,38342,68835,109900.0,21.0,1360.0,1530.0,31.0,34.0,www.carleton.edu
49,121257,117200,1172,54,Pitzer College,Claremont,CA,Private,1074,1087,28423,41257,70500,96600.0,16.0,0.0,0.0,0.0,0.0,www.pitzer.edu
50,139658,156400,1564,55,Emory University,Atlanta,GA,Private,7859,14263,26760,38213,66950,110800.0,22.0,1350.0,1520.0,30.0,33.0,www.emory.edu

In [25]:
college_ranking_df.loc[college_ranking_df['OPEID'].duplicated()]

Empty DataFrame
Columns: [UNITID, OPEID, OPEID6, Rank, Name, City, State, Public/Private, Undergraduate Population, Student Population, Net Price, Average Grant Aid, Total Annual Cost, Alumni Salary, Acceptance Rate, SAT Lower, SAT Upper, ACT Lower, ACT Upper, Website]
Index: []

In [26]:
len(college_ranking_df['UNITID'].unique())

630

In [27]:
#this will give us only the schools that have a rnaking from forbes and ones that we have on our list
filtered_ranking_4_year_df = filtered_4_year_df.merge(college_ranking_df, how = 'inner', on = 'OPEID')

In [28]:
filtered_ranking_4_year_df.columns

Index(['UNITID_x', 'OPEID', 'OPEID6_x', 'INSTNM', 'CITY', 'STABBR', 'ZIP',
       'ACCREDAGENCY', 'INSTURL', 'NPCURL',
       ...
       'Net Price', 'Average Grant Aid', 'Total Annual Cost', 'Alumni Salary',
       'Acceptance Rate', 'SAT Lower', 'SAT Upper', 'ACT Lower', 'ACT Upper',
       'Website'],
      dtype='object', length=2005)

In [29]:
filtered_ranking_4_year_df

,UNITID_x,OPEID,OPEID6_x,INSTNM,CITY,STABBR,ZIP,ACCREDAGENCY,INSTURL,NPCURL,...,Net Price,Average Grant Aid,Total Annual Cost,Alumni Salary,Acceptance Rate,SAT Lower,SAT Upper,ACT Lower,ACT Upper,Website
0,100663,105200,1052,University of Alabama at Birmingham,Birmingham,AL,35294-0110,Southern Association of Colleges and Schools C...,https://www.uab.edu,https://uab.studentaidcalculator.com/survey.aspx,...,17535,9254,36800,87200.0,92.0,990.0,1370.0,21.0,28.0,www.uab.edu
1,100706,105500,1055,University of Alabama in Huntsville,Huntsville,AL,35899,Southern Association of Colleges and Schools C...,www.uah.edu,finaid.uah.edu/,...,19986,9587,36881,103900.0,81.0,1080.0,1330.0,25.0,31.0,www.uah.edu
2,100751,105100,1051,The University of Alabama,Tuscaloosa,AL,35487-0100,Southern Association of Colleges and Schools C...,www.ua.edu/,financialaid.ua.edu/net-price-calculator/,...,21973,16494,46744,97400.0,53.0,1050.0,1280.0,23.0,32.0,www.ua.edu
3,100858,100900,1009,Auburn University,Auburn,AL,36849,Southern Association of Colleges and Schools C...,www.auburn.edu,https://www.auburn.edu/admissions/costcalc/fre...,...,23416,9030,49954,104500.0,84.0,1130.0,1310.0,24.0,30.0,www.auburn.edu
4,100937,101200,1012,Birmingham-Southern College,Birmingham,AL,35254,Southern Association of Colleges and Schools C...,www.bsc.edu/,www.bsc.edu/fp/np-calculator.cfm,...,22853,26594,52414,88300.0,62.0,1030.0,1260.0,23.0,29.0,www.bsc.edu
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
634,243780,182500,1825,Purdue University-Main Campus,West Lafayette,IN,47907-2040,Higher Learning Commission,https://www.purdue.edu,https://www.purdue.edu/dfa/cost/estimator.html,...,13746,10703,41614,110000.0,57.0,1150.0,1380.0,25.0,31.0,www.purdue.edu
635,245652,209300,2093,St. John's College,Santa Fe,NM,87505-4599,Higher Learning Commission,www.sjc.edu,www.sjc.edu/admissions-and-aid/financial-aid/n...,...,20605,31845,65456,0.0,63.0,1190.0,1350.0,23.0,32.0,www.sjca.edu
636,262129,3957400,39574,New College of Florida,Sarasota,FL,34243-2109,Southern Association of Colleges and Schools C...,www.ncf.edu,www.ncf.edu/admissions/cost-and-aid/tuition-an...,...,10248,9341,43678,86500.0,69.0,1190.0,1380.0,25.0,30.0,www.ncf.edu
637,433660,3255300,32553,Florida Gulf Coast University,Fort Myers,FL,33965-6565,Southern Association of Colleges and Schools C...,www.fgcu.edu,https://www2.fgcu.edu/financialaid/netpricecal...,...,15376,4726,39434,80000.0,64.0,1060.0,1210.0,21.0,25.0,www.fgcu.edu
638,482680,158500,1585,University of North Georgia,Dahlonega,GA,30597,Southern Association of Colleges and Schools C...,www.ung.edu,ung.edu/financial-aid/net-calculator.php,...,9854,5483,28094,85600.0,78.0,910.0,1130.0,20.0,25.0,www.ung.edu

In [30]:
filtered_ranking_4_year_df.columns

Index(['UNITID_x', 'OPEID', 'OPEID6_x', 'INSTNM', 'CITY', 'STABBR', 'ZIP',
       'ACCREDAGENCY', 'INSTURL', 'NPCURL',
       ...
       'Net Price', 'Average Grant Aid', 'Total Annual Cost', 'Alumni Salary',
       'Acceptance Rate', 'SAT Lower', 'SAT Upper', 'ACT Lower', 'ACT Upper',
       'Website'],
      dtype='object', length=2005)

In [31]:
#need to drop all text based columns
filtered_ranking_4_year_df = filtered_ranking_4_year_df.drop(columns = ['UNITID_x', 'OPEID6_x', 'Name','City','State','Public/Private','Website', 'OPEID', 'CITY', 'STABBR', 'ZIP', 'INSTURL'])

In [32]:
#lets also drop some nonsense columns like latitude, longitude, SCH_DEG, MAIN, PREDDEG, NUMBRANCH, REGION, ST_FIPS
filtered_ranking_4_year_df = filtered_ranking_4_year_df.drop(columns = ['REGION', 'ST_FIPS', 'MAIN', 'NUMBRANCH','LATITUDE','LONGITUDE'])

In [33]:
filtered_ranking_4_year_df

,INSTNM,ACCREDAGENCY,NPCURL,SCH_DEG,HCM2,PREDDEG,HIGHDEG,CONTROL,LOCALE,LOCALE2,...,Student Population,Net Price,Average Grant Aid,Total Annual Cost,Alumni Salary,Acceptance Rate,SAT Lower,SAT Upper,ACT Lower,ACT Upper
0,University of Alabama at Birmingham,Southern Association of Colleges and Schools C...,https://uab.studentaidcalculator.com/survey.aspx,3.0,0,3,4,1,12.0,NaN,...,20902,17535,9254,36800,87200.0,92.0,990.0,1370.0,21.0,28.0
1,University of Alabama in Huntsville,Southern Association of Colleges and Schools C...,finaid.uah.edu/,3.0,0,3,4,1,12.0,NaN,...,9101,19986,9587,36881,103900.0,81.0,1080.0,1330.0,25.0,31.0
2,The University of Alabama,Southern Association of Colleges and Schools C...,financialaid.ua.edu/net-price-calculator/,3.0,0,3,4,1,12.0,NaN,...,38563,21973,16494,46744,97400.0,53.0,1050.0,1280.0,23.0,32.0
3,Auburn University,Southern Association of Colleges and Schools C...,https://www.auburn.edu/admissions/costcalc/fre...,3.0,0,3,4,1,13.0,NaN,...,29776,23416,9030,49954,104500.0,84.0,1130.0,1310.0,24.0,30.0
4,Birmingham-Southern College,Southern Association of Colleges and Schools C...,www.bsc.edu/fp/np-calculator.cfm,3.0,0,3,3,2,12.0,NaN,...,1325,22853,26594,52414,88300.0,62.0,1030.0,1260.0,23.0,29.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
634,Purdue University-Main Campus,Higher Learning Commission,https://www.purdue.edu/dfa/cost/estimator.html,3.0,0,3,4,1,13.0,NaN,...,42699,13746,10703,41614,110000.0,57.0,1150.0,1380.0,25.0,31.0
635,St. John's College,Higher Learning Commission,www.sjc.edu/admissions-and-aid/financial-aid/n...,3.0,0,3,4,2,41.0,NaN,...,386,20605,31845,65456,0.0,63.0,1190.0,1350.0,23.0,32.0
636,New College of Florida,Southern Association of Colleges and Schools C...,www.ncf.edu/admissions/cost-and-aid/tuition-an...,3.0,0,3,4,1,13.0,NaN,...,885,10248,9341,43678,86500.0,69.0,1190.0,1380.0,25.0,30.0
637,Florida Gulf Coast University,Southern Association of Colleges and Schools C...,https://www2.fgcu.edu/financialaid/netpricecal...,3.0,0,3,4,1,21.0,NaN,...,15317,15376,4726,39434,80000.0,64.0,1060.0,1210.0,21.0,25.0
638,University of North Georgia,Southern Association of Colleges and Schools C...,ung.edu/financial-aid/net-calculator.php,3.0,0,3,4,1,31.0,NaN,...,20811,9854,5483,28094,85600.0,78.0,910.0,1130.0,20.0,25.0

In [34]:
#the next few lines are simply to move the school rank to the first column
col_list = filtered_ranking_4_year_df.columns.to_list()

In [35]:
col_list.pop(col_list.index('Rank'))

'Rank'

In [36]:
col_list.insert(0, 'Rank')
col_list

['Rank',
 'INSTNM',
 'ACCREDAGENCY',
 'NPCURL',
 'SCH_DEG',
 'HCM2',
 'PREDDEG',
 'HIGHDEG',
 'CONTROL',
 'LOCALE',
 'LOCALE2',
 'CCBASIC',
 'CCUGPROF',
 'CCSIZSET',
 'HBCU',
 'PBI',
 'ANNHI',
 'TRIBAL',
 'AANAPII',
 'HSI',
 'NANTI',
 'MENONLY',
 'WOMENONLY',
 'RELAFFIL',
 'ADM_RATE',
 'ADM_RATE_ALL',
 'SATVR25',
 'SATVR75',
 'SATMT25',
 'SATMT75',
 'SATWR25',
 'SATWR75',
 'SATVRMID',
 'SATMTMID',
 'SATWRMID',
 'ACTCM25',
 'ACTCM75',
 'ACTEN25',
 'ACTEN75',
 'ACTMT25',
 'ACTMT75',
 'ACTWR25',
 'ACTWR75',
 'ACTCMMID',
 'ACTENMID',
 'ACTMTMID',
 'ACTWRMID',
 'SAT_AVG',
 'SAT_AVG_ALL',
 'PCIP01',
 'PCIP03',
 'PCIP04',
 'PCIP05',
 'PCIP09',
 'PCIP10',
 'PCIP11',
 'PCIP12',
 'PCIP13',
 'PCIP14',
 'PCIP15',
 'PCIP16',
 'PCIP19',
 'PCIP22',
 'PCIP23',
 'PCIP24',
 'PCIP25',
 'PCIP26',
 'PCIP27',
 'PCIP29',
 'PCIP30',
 'PCIP31',
 'PCIP38',
 'PCIP39',
 'PCIP40',
 'PCIP41',
 'PCIP42',
 'PCIP43',
 'PCIP44',
 'PCIP45',
 'PCIP46',
 'PCIP47',
 'PCIP48',
 'PCIP49',
 'PCIP50',
 'PCIP51',
 'PCIP52',
 'PCIP54',
 'CIP01CERT1',
 'CIP01CERT2',
 'CIP01ASSOC',
 'CIP01CERT4',
 'CIP01BACHL',
 'CIP03CERT1',
 'CIP03CERT2',
 'CIP03ASSOC',
 'CIP03CERT4',
 'CIP03BACHL',
 'CIP04CERT1',
 'CIP04CERT2',
 'CIP04ASSOC',
 'CIP04CERT4',
 'CIP04BACHL',
 'CIP05CERT1',
 'CIP05CERT2',
 'CIP05ASSOC',
 'CIP05CERT4',
 'CIP05BACHL',
 'CIP09CERT1',
 'CIP09CERT2',
 'CIP09ASSOC',
 'CIP09CERT4',
 'CIP09BACHL',
 'CIP10CERT1',
 'CIP10CERT2',
 'CIP10ASSOC',
 'CIP10CERT4',
 'CIP10BACHL',
 'CIP11CERT1',
 'CIP11CERT2',
 'CIP11ASSOC',
 'CIP11CERT4',
 'CIP11BACHL',
 'CIP12CERT1',
 'CIP12CERT2',
 'CIP12ASSOC',
 'CIP12CERT4',
 'CIP12BACHL',
 'CIP13CERT1',
 'CIP13CERT2',
 'CIP13ASSOC',
 'CIP13CERT4',
 'CIP13BACHL',
 'CIP14CERT1',
 'CIP14CERT2',
 'CIP14ASSOC',
 'CIP14CERT4',
 'CIP14BACHL',
 'CIP15CERT1',
 'CIP15CERT2',
 'CIP15ASSOC',
 'CIP15CERT4',
 'CIP15BACHL',
 'CIP16CERT1',
 'CIP16CERT2',
 'CIP16ASSOC',
 'CIP16CERT4',
 'CIP16BACHL',
 'CIP19CERT1',
 'CIP19CERT2',
 'CIP19ASSOC',
 'CIP19CERT4',
 'CIP19BACHL',
 'CIP22CERT1',
 'CIP22CERT2',
 'CIP22ASSOC',
 'CIP22CERT4',
 'CIP22BACHL',
 'CIP23CERT1',
 'CIP23CERT2',
 'CIP23ASSOC',
 'CIP23CERT4',
 'CIP23BACHL',
 'CIP24CERT1',
 'CIP24CERT2',
 'CIP24ASSOC',
 'CIP24CERT4',
 'CIP24BACHL',
 'CIP25CERT1',
 'CIP25CERT2',
 'CIP25ASSOC',
 'CIP25CERT4',
 'CIP25BACHL',
 'CIP26CERT1',
 'CIP26CERT2',
 'CIP26ASSOC',
 'CIP26CERT4',
 'CIP26BACHL',
 'CIP27CERT1',
 'CIP27CERT2',
 'CIP27ASSOC',
 'CIP27CERT4',
 'CIP27BACHL',
 'CIP29CERT1',
 'CIP29CERT2',
 'CIP29ASSOC',
 'CIP29CERT4',
 'CIP29BACHL',
 'CIP30CERT1',
 'CIP30CERT2',
 'CIP30ASSOC',
 'CIP30CERT4',
 'CIP30BACHL',
 'CIP31CERT1',
 'CIP31CERT2',
 'CIP31ASSOC',
 'CIP31CERT4',
 'CIP31BACHL',
 'CIP38CERT1',
 'CIP38CERT2',
 'CIP38ASSOC',
 'CIP38CERT4',
 'CIP38BACHL',
 'CIP39CERT1',
 'CIP39CERT2',
 'CIP39ASSOC',
 'CIP39CERT4',
 'CIP39BACHL',
 'CIP40CERT1',
 'CIP40CERT2',
 'CIP40ASSOC',
 'CIP40CERT4',
 'CIP40BACHL',
 'CIP41CERT1',
 'CIP41CERT2',
 'CIP41ASSOC',
 'CIP41CERT4',
 'CIP41BACHL',
 'CIP42CERT1',
 'CIP42CERT2',
 'CIP42ASSOC',
 'CIP42CERT4',
 'CIP42BACHL',
 'CIP43CERT1',
 'CIP43CERT2',
 'CIP43ASSOC',
 'CIP43CERT4',
 'CIP43BACHL',
 'CIP44CERT1',
 'CIP44CERT2',
 'CIP44ASSOC',
 'CIP44CERT4',
 'CIP44BACHL',
 'CIP45CERT1',
 'CIP45CERT2',
 'CIP45ASSOC',
 'CIP45CERT4',
 'CIP45BACHL',
 'CIP46CERT1',
 'CIP46CERT2',
 'CIP46ASSOC',
 'CIP46CERT4',
 'CIP46BACHL',
 'CIP47CERT1',
 'CIP47CERT2',
 'CIP47ASSOC',
 'CIP47CERT4',
 'CIP47BACHL',
 'CIP48CERT1',
 'CIP48CERT2',
 'CIP48ASSOC',
 'CIP48CERT4',
 'CIP48BACHL',
 'CIP49CERT1',
 'CIP49CERT2',
 'CIP49ASSOC',
 'CIP49CERT4',
 'CIP49BACHL',
 'CIP50CERT1',
 'CIP50CERT2',
 'CIP50ASSOC',
 'CIP50CERT4',
 'CIP50BACHL',
 'CIP51CERT1',
 'CIP51CERT2',
 'CIP51ASSOC',
 'CIP51CERT4',
 'CIP51BACHL',
 'CIP52CERT1',
 'CIP52CERT2',
 'CIP52ASSOC',
 'CIP52CERT4',
 'CIP52BACHL',
 'CIP54CERT1',
 'CIP54CERT2',
 'CIP54ASSOC',
 'CIP54CERT4',
 'CIP54BACHL',
 'DISTANCEONLY',
 'UGDS',
 'UG',
 'UGDS_WHITE',
 'UGDS_BLACK',
 'UGDS_HISP',
 'UGDS_ASIAN',
 'UGDS_AIAN',
 'UGDS_NHPI',
 'UGDS_2MOR',
 'UGDS_NRA',
 'UGDS_UNKN',
 'UGDS_WHITENH',
 'UGDS_BLACKNH',
 'UGDS_API',
 'UGDS_AIANOLD',
 'UGDS_HISPOLD',
 'UG_NRA',
 'UG_UNKN',
 'UG_WHITENH',
 'UG_BLACKNH',
 'UG_API',
 'UG_AIANOLD',
 'UG_HISPOLD',
 'PPTUG_EF',
 'PPTUG_EF2',
 'CURROPER',
 'NPT4_PUB',
 'NPT4_PRIV',
 'NPT4_PROG',
 'NPT4_OTHER',
 'NPT41_PUB',
 'NPT42_PUB',
 'NPT43_PUB',
 'NPT44_PUB',
 'NPT45_PUB',
 'NPT41_PRIV',
 'NPT42_PRIV',
 'NPT43_PRIV',
 'NPT44_PRIV',
 'NPT45_PRIV',
 'NPT41_PROG',
 'NPT42_PROG',
 'NPT43_PROG',
 'NPT44_PROG',
 'NPT45_PROG',
 'NPT41_OTHER',
 'NPT42_OTHER',
 'NPT43_OTHER',
 'NPT44_OTHER',
 'NPT45_OTHER',
 'NPT4_048_PUB',
 'NPT4_048_PRIV',
 'NPT4_048_PROG',
 'NPT4_048_OTHER',
 'NPT4_3075_PUB',
 'NPT4_3075_PRIV',
 'NPT4_75UP_PUB',
 'NPT4_75UP_PRIV',
 'NPT4_3075_PROG',
 'NPT4_3075_OTHER',
 'NPT4_75UP_PROG',
 'NPT4_75UP_OTHER',
 'NUM4_PUB',
 'NUM4_PRIV',
 'NUM4_PROG',
 'NUM4_OTHER',
 'NUM41_PUB',
 'NUM42_PUB',
 'NUM43_PUB',
 'NUM44_PUB',
 'NUM45_PUB',
 'NUM41_PRIV',
 'NUM42_PRIV',
 'NUM43_PRIV',
 'NUM44_PRIV',
 'NUM45_PRIV',
 'NUM41_PROG',
 'NUM42_PROG',
 'NUM43_PROG',
 'NUM44_PROG',
 'NUM45_PROG',
 'NUM41_OTHER',
 'NUM42_OTHER',
 'NUM43_OTHER',
 'NUM44_OTHER',
 'NUM45_OTHER',
 'COSTT4_A',
 'COSTT4_P',
 'TUITIONFEE_IN',
 'TUITIONFEE_OUT',
 'TUITIONFEE_PROG',
 'TUITFTE',
 'INEXPFTE',
 'AVGFACSAL',
 'PFTFAC',
 'PCTPELL',
 'C150_4',
 'C150_L4',
 'C150_4_POOLED',
 'C150_L4_POOLED',
 'POOLYRS',
 'PFTFTUG1_EF',
 'D150_4',
 'D150_L4',
 'D150_4_POOLED',
 'D150_L4_POOLED',
 'C150_4_WHITE',
 'C150_4_BLACK',
 'C150_4_HISP',
 'C150_4_ASIAN',
 'C150_4_AIAN',
 'C150_4_NHPI',
 'C150_4_2MOR',
 'C150_4_NRA',
 'C150_4_UNKN',
 'C150_4_WHITENH',
 'C150_4_BLACKNH',
 'C150_4_API',
 'C150_4_AIANOLD',
 'C150_4_HISPOLD',
 'C150_L4_WHITE',
 'C150_L4_BLACK',
 'C150_L4_HISP',
 'C150_L4_ASIAN',
 'C150_L4_AIAN',
 'C150_L4_NHPI',
 'C150_L4_2MOR',
 'C150_L4_NRA',
 'C150_L4_UNKN',
 'C150_L4_WHITENH',
 'C150_L4_BLACKNH',
 'C150_L4_API',
 'C150_L4_AIANOLD',
 'C150_L4_HISPOLD',
 'C200_4',
 'C200_L4',
 'D200_4',
 'D200_L4',
 'RET_FT4',
 'RET_FTL4',
 'RET_PT4',
 'RET_PTL4',
 'C200_4_POOLED',
 'C200_L4_POOLED',
 'POOLYRS200',
 'D200_4_POOLED',
 'D200_L4_POOLED',
 'PCTFLOAN',
 'UG25ABV',
 'CDR2',
 'CDR3',
 'DEATH_YR2_RT',
 'COMP_ORIG_YR2_RT',
 'COMP_4YR_TRANS_YR2_RT',
 'COMP_2YR_TRANS_YR2_RT',
 'WDRAW_ORIG_YR2_RT',
 'WDRAW_4YR_TRANS_YR2_RT',
 'WDRAW_2YR_TRANS_YR2_RT',
 'ENRL_ORIG_YR2_RT',
 'ENRL_4YR_TRANS_YR2_RT',
 'ENRL_2YR_TRANS_YR2_RT',
 'UNKN_ORIG_YR2_RT',
 'UNKN_4YR_TRANS_YR2_RT',
 'UNKN_2YR_TRANS_YR2_RT',
 'LO_INC_DEATH_YR2_RT',
 'LO_INC_COMP_ORIG_YR2_RT',
 'LO_INC_COMP_4YR_TRANS_YR2_RT',
 'LO_INC_COMP_2YR_TRANS_YR2_RT',
 'LO_INC_WDRAW_ORIG_YR2_RT',
 'LO_INC_WDRAW_4YR_TRANS_YR2_RT',
 'LO_INC_WDRAW_2YR_TRANS_YR2_RT',
 'LO_INC_ENRL_ORIG_YR2_RT',
 'LO_INC_ENRL_4YR_TRANS_YR2_RT',
 'LO_INC_ENRL_2YR_TRANS_YR2_RT',
 'LO_INC_UNKN_ORIG_YR2_RT',
 'LO_INC_UNKN_4YR_TRANS_YR2_RT',
 'LO_INC_UNKN_2YR_TRANS_YR2_RT',
 'MD_INC_DEATH_YR2_RT',
 'MD_INC_COMP_ORIG_YR2_RT',
 'MD_INC_COMP_4YR_TRANS_YR2_RT',
 'MD_INC_COMP_2YR_TRANS_YR2_RT',
 'MD_INC_WDRAW_ORIG_YR2_RT',
 'MD_INC_WDRAW_4YR_TRANS_YR2_RT',
 'MD_INC_WDRAW_2YR_TRANS_YR2_RT',
 'MD_INC_ENRL_ORIG_YR2_RT',
 'MD_INC_ENRL_4YR_TRANS_YR2_RT',
 'MD_INC_ENRL_2YR_TRANS_YR2_RT',
 'MD_INC_UNKN_ORIG_YR2_RT',
 'MD_INC_UNKN_4YR_TRANS_YR2_RT',
 'MD_INC_UNKN_2YR_TRANS_YR2_RT',
 'HI_INC_DEATH_YR2_RT',
 'HI_INC_COMP_ORIG_YR2_RT',
 'HI_INC_COMP_4YR_TRANS_YR2_RT',
 'HI_INC_COMP_2YR_TRANS_YR2_RT',
 'HI_INC_WDRAW_ORIG_YR2_RT',
 'HI_INC_WDRAW_4YR_TRANS_YR2_RT',
 'HI_INC_WDRAW_2YR_TRANS_YR2_RT',
 'HI_INC_ENRL_ORIG_YR2_RT',
 'HI_INC_ENRL_4YR_TRANS_YR2_RT',
 'HI_INC_ENRL_2YR_TRANS_YR2_RT',
 'HI_INC_UNKN_ORIG_YR2_RT',
 'HI_INC_UNKN_4YR_TRANS_YR2_RT',
 'HI_INC_UNKN_2YR_TRANS_YR2_RT',
 'DEP_DEATH_YR2_RT',
 'DEP_COMP_ORIG_YR2_RT',
 'DEP_COMP_4YR_TRANS_YR2_RT',
 'DEP_COMP_2YR_TRANS_YR2_RT',
 'DEP_WDRAW_ORIG_YR2_RT',
 'DEP_WDRAW_4YR_TRANS_YR2_RT',
 'DEP_WDRAW_2YR_TRANS_YR2_RT',
 'DEP_ENRL_ORIG_YR2_RT',
 'DEP_ENRL_4YR_TRANS_YR2_RT',
 'DEP_ENRL_2YR_TRANS_YR2_RT',
 'DEP_UNKN_ORIG_YR2_RT',
 'DEP_UNKN_4YR_TRANS_YR2_RT',
 'DEP_UNKN_2YR_TRANS_YR2_RT',
 'IND_DEATH_YR2_RT',
 'IND_COMP_ORIG_YR2_RT',
 'IND_COMP_4YR_TRANS_YR2_RT',
 'IND_COMP_2YR_TRANS_YR2_RT',
 'IND_WDRAW_ORIG_YR2_RT',
 'IND_WDRAW_4YR_TRANS_YR2_RT',
 'IND_WDRAW_2YR_TRANS_YR2_RT',
 'IND_ENRL_ORIG_YR2_RT',
 'IND_ENRL_4YR_TRANS_YR2_RT',
 'IND_ENRL_2YR_TRANS_YR2_RT',
 'IND_UNKN_ORIG_YR2_RT',
 'IND_UNKN_4YR_TRANS_YR2_RT',
 'IND_UNKN_2YR_TRANS_YR2_RT',
 'FEMALE_DEATH_YR2_RT',
 'FEMALE_COMP_ORIG_YR2_RT',
 'FEMALE_COMP_4YR_TRANS_YR2_RT',
 'FEMALE_COMP_2YR_TRANS_YR2_RT',
 'FEMALE_WDRAW_ORIG_YR2_RT',
 'FEMALE_WDRAW_4YR_TRANS_YR2_RT',
 'FEMALE_WDRAW_2YR_TRANS_YR2_RT',
 'FEMALE_ENRL_ORIG_YR2_RT',
 'FEMALE_ENRL_4YR_TRANS_YR2_RT',
 'FEMALE_ENRL_2YR_TRANS_YR2_RT',
 'FEMALE_UNKN_ORIG_YR2_RT',
 'FEMALE_UNKN_4YR_TRANS_YR2_RT',
 'FEMALE_UNKN_2YR_TRANS_YR2_RT',
 'MALE_DEATH_YR2_RT',
 'MALE_COMP_ORIG_YR2_RT',
 'MALE_COMP_4YR_TRANS_YR2_RT',
 'MALE_COMP_2YR_TRANS_YR2_RT',
 'MALE_WDRAW_ORIG_YR2_RT',
 'MALE_WDRAW_4YR_TRANS_YR2_RT',
 'MALE_WDRAW_2YR_TRANS_YR2_RT',
 'MALE_ENRL_ORIG_YR2_RT',
 'MALE_ENRL_4YR_TRANS_YR2_RT',
 'MALE_ENRL_2YR_TRANS_YR2_RT',
 'MALE_UNKN_ORIG_YR2_RT',
 'MALE_UNKN_4YR_TRANS_YR2_RT',
 'MALE_UNKN_2YR_TRANS_YR2_RT',
 'PELL_DEATH_YR2_RT',
 'PELL_COMP_ORIG_YR2_RT',
 'PELL_COMP_4YR_TRANS_YR2_RT',
 'PELL_COMP_2YR_TRANS_YR2_RT',
 'PELL_WDRAW_ORIG_YR2_RT',
 'PELL_WDRAW_4YR_TRANS_YR2_RT',
 'PELL_WDRAW_2YR_TRANS_YR2_RT',
 'PELL_ENRL_ORIG_YR2_RT',
 'PELL_ENRL_4YR_TRANS_YR2_RT',
 'PELL_ENRL_2YR_TRANS_YR2_RT',
 'PELL_UNKN_ORIG_YR2_RT',
 'PELL_UNKN_4YR_TRANS_YR2_RT',
 'PELL_UNKN_2YR_TRANS_YR2_RT',
 'NOPELL_DEATH_YR2_RT',
 'NOPELL_COMP_ORIG_YR2_RT',
 'NOPELL_COMP_4YR_TRANS_YR2_RT',
 'NOPELL_COMP_2YR_TRANS_YR2_RT',
 'NOPELL_WDRAW_ORIG_YR2_RT',
 'NOPELL_WDRAW_4YR_TRANS_YR2_RT',
 'NOPELL_WDRAW_2YR_TRANS_YR2_RT',
 'NOPELL_ENRL_ORIG_YR2_RT',
 'NOPELL_ENRL_4YR_TRANS_YR2_RT',
 'NOPELL_ENRL_2YR_TRANS_YR2_RT',
 'NOPELL_UNKN_ORIG_YR2_RT',
 'NOPELL_UNKN_4YR_TRANS_YR2_RT',
 'NOPELL_UNKN_2YR_TRANS_YR2_RT',
 'LOAN_DEATH_YR2_RT',
 'LOAN_COMP_ORIG_YR2_RT',
 'LOAN_COMP_4YR_TRANS_YR2_RT',
 'LOAN_COMP_2YR_TRANS_YR2_RT',
 'LOAN_WDRAW_ORIG_YR2_RT',
 'LOAN_WDRAW_4YR_TRANS_YR2_RT',
 'LOAN_WDRAW_2YR_TRANS_YR2_RT',
 'LOAN_ENRL_ORIG_YR2_RT',
 'LOAN_ENRL_4YR_TRANS_YR2_RT',
 'LOAN_ENRL_2YR_TRANS_YR2_RT',
 'LOAN_UNKN_ORIG_YR2_RT',
 'LOAN_UNKN_4YR_TRANS_YR2_RT',
 'LOAN_UNKN_2YR_TRANS_YR2_RT',
 'NOLOAN_DEATH_YR2_RT',
 'NOLOAN_COMP_ORIG_YR2_RT',
 'NOLOAN_COMP_4YR_TRANS_YR2_RT',
 'NOLOAN_COMP_2YR_TRANS_YR2_RT',
 'NOLOAN_WDRAW_ORIG_YR2_RT',
 'NOLOAN_WDRAW_4YR_TRANS_YR2_RT',
 'NOLOAN_WDRAW_2YR_TRANS_YR2_RT',
 'NOLOAN_ENRL_ORIG_YR2_RT',
 'NOLOAN_ENRL_4YR_TRANS_YR2_RT',
 'NOLOAN_ENRL_2YR_TRANS_YR2_RT',
 'NOLOAN_UNKN_ORIG_YR2_RT',
 'NOLOAN_UNKN_4YR_TRANS_YR2_RT',
 'NOLOAN_UNKN_2YR_TRANS_YR2_RT',
 'FIRSTGEN_DEATH_YR2_RT',
 'FIRSTGEN_COMP_ORIG_YR2_RT',
 'FIRSTGEN_COMP_4YR_TRANS_YR2_RT',
 'FIRSTGEN_COMP_2YR_TRANS_YR2_RT',
 'FIRSTGEN_WDRAW_ORIG_YR2_RT',
 'FIRSTGEN_WDRAW_4YR_TRANS_YR2_RT',
 'FIRSTGEN_WDRAW_2YR_TRANS_YR2_RT',
 'FIRSTGEN_ENRL_ORIG_YR2_RT',
 'FIRSTGEN_ENRL_4YR_TRANS_YR2_RT',
 'FIRSTGEN_ENRL_2YR_TRANS_YR2_RT',
 'FIRSTGEN_UNKN_ORIG_YR2_RT',
 'FIRSTGEN_UNKN_4YR_TRANS_YR2_RT',
 'FIRSTGEN_UNKN_2YR_TRANS_YR2_RT',
 'NOT1STGEN_DEATH_YR2_RT',
 'NOT1STGEN_COMP_ORIG_YR2_RT',
 'NOT1STGEN_COMP_4YR_TRANS_YR2_RT',
 'NOT1STGEN_COMP_2YR_TRANS_YR2_RT',
 'NOT1STGEN_WDRAW_ORIG_YR2_RT',
 'NOT1STGEN_WDRAW_4YR_TRANS_YR2_RT',
 'NOT1STGEN_WDRAW_2YR_TRANS_YR2_RT',
 'NOT1STGEN_ENRL_ORIG_YR2_RT',
 'NOT1STGEN_ENRL_4YR_TRANS_YR2_RT',
 'NOT1STGEN_ENRL_2YR_TRANS_YR2_RT',
 'NOT1STGEN_UNKN_ORIG_YR2_RT',
 'NOT1STGEN_UNKN_4YR_TRANS_YR2_RT',
 'NOT1STGEN_UNKN_2YR_TRANS_YR2_RT',
 'DEATH_YR3_RT',
 'COMP_ORIG_YR3_RT',
 'COMP_4YR_TRANS_YR3_RT',
 'COMP_2YR_TRANS_YR3_RT',
 'WDRAW_ORIG_YR3_RT',
 'WDRAW_4YR_TRANS_YR3_RT',
 'WDRAW_2YR_TRANS_YR3_RT',
 'ENRL_ORIG_YR3_RT',
 'ENRL_4YR_TRANS_YR3_RT',
 'ENRL_2YR_TRANS_YR3_RT',
 'UNKN_ORIG_YR3_RT',
 'UNKN_4YR_TRANS_YR3_RT',
 'UNKN_2YR_TRANS_YR3_RT',
 'LO_INC_DEATH_YR3_RT',
 'LO_INC_COMP_ORIG_YR3_RT',
 'LO_INC_COMP_4YR_TRANS_YR3_RT',
 'LO_INC_COMP_2YR_TRANS_YR3_RT',
 'LO_INC_WDRAW_ORIG_YR3_RT',
 'LO_INC_WDRAW_4YR_TRANS_YR3_RT',
 'LO_INC_WDRAW_2YR_TRANS_YR3_RT',
 'LO_INC_ENRL_ORIG_YR3_RT',
 'LO_INC_ENRL_4YR_TRANS_YR3_RT',
 'LO_INC_ENRL_2YR_TRANS_YR3_RT',
 'LO_INC_UNKN_ORIG_YR3_RT',
 'LO_INC_UNKN_4YR_TRANS_YR3_RT',
 'LO_INC_UNKN_2YR_TRANS_YR3_RT',
 'MD_INC_DEATH_YR3_RT',
 'MD_INC_COMP_ORIG_YR3_RT',
 'MD_INC_COMP_4YR_TRANS_YR3_RT',
 'MD_INC_COMP_2YR_TRANS_YR3_RT',
 'MD_INC_WDRAW_ORIG_YR3_RT',
 'MD_INC_WDRAW_4YR_TRANS_YR3_RT',
 'MD_INC_WDRAW_2YR_TRANS_YR3_RT',
 'MD_INC_ENRL_ORIG_YR3_RT',
 'MD_INC_ENRL_4YR_TRANS_YR3_RT',
 'MD_INC_ENRL_2YR_TRANS_YR3_RT',
 'MD_INC_UNKN_ORIG_YR3_RT',
 'MD_INC_UNKN_4YR_TRANS_YR3_RT',
 'MD_INC_UNKN_2YR_TRANS_YR3_RT',
 'HI_INC_DEATH_YR3_RT',
 'HI_INC_COMP_ORIG_YR3_RT',
 'HI_INC_COMP_4YR_TRANS_YR3_RT',
 'HI_INC_COMP_2YR_TRANS_YR3_RT',
 'HI_INC_WDRAW_ORIG_YR3_RT',
 'HI_INC_WDRAW_4YR_TRANS_YR3_RT',
 'HI_INC_WDRAW_2YR_TRANS_YR3_RT',
 'HI_INC_ENRL_ORIG_YR3_RT',
 'HI_INC_ENRL_4YR_TRANS_YR3_RT',
 'HI_INC_ENRL_2YR_TRANS_YR3_RT',
 'HI_INC_UNKN_ORIG_YR3_RT',
 'HI_INC_UNKN_4YR_TRANS_YR3_RT',
 'HI_INC_UNKN_2YR_TRANS_YR3_RT',
 'DEP_DEATH_YR3_RT',
 'DEP_COMP_ORIG_YR3_RT',
 'DEP_COMP_4YR_TRANS_YR3_RT',
 'DEP_COMP_2YR_TRANS_YR3_RT',
 'DEP_WDRAW_ORIG_YR3_RT',
 'DEP_WDRAW_4YR_TRANS_YR3_RT',
 'DEP_WDRAW_2YR_TRANS_YR3_RT',
 'DEP_ENRL_ORIG_YR3_RT',
 'DEP_ENRL_4YR_TRANS_YR3_RT',
 'DEP_ENRL_2YR_TRANS_YR3_RT',
 'DEP_UNKN_ORIG_YR3_RT',
 'DEP_UNKN_4YR_TRANS_YR3_RT',
 'DEP_UNKN_2YR_TRANS_YR3_RT',
 'IND_DEATH_YR3_RT',
 'IND_COMP_ORIG_YR3_RT',
 'IND_COMP_4YR_TRANS_YR3_RT',
 'IND_COMP_2YR_TRANS_YR3_RT',
 'IND_WDRAW_ORIG_YR3_RT',
 'IND_WDRAW_4YR_TRANS_YR3_RT',
 'IND_WDRAW_2YR_TRANS_YR3_RT',
 'IND_ENRL_ORIG_YR3_RT',
 'IND_ENRL_4YR_TRANS_YR3_RT',
 'IND_ENRL_2YR_TRANS_YR3_RT',
 'IND_UNKN_ORIG_YR3_RT',
 'IND_UNKN_4YR_TRANS_YR3_RT',
 'IND_UNKN_2YR_TRANS_YR3_RT',
 'FEMALE_DEATH_YR3_RT',
 'FEMALE_COMP_ORIG_YR3_RT',
 'FEMALE_COMP_4YR_TRANS_YR3_RT',
 'FEMALE_COMP_2YR_TRANS_YR3_RT',
 'FEMALE_WDRAW_ORIG_YR3_RT',
 'FEMALE_WDRAW_4YR_TRANS_YR3_RT',
 'FEMALE_WDRAW_2YR_TRANS_YR3_RT',
 'FEMALE_ENRL_ORIG_YR3_RT',
 'FEMALE_ENRL_4YR_TRANS_YR3_RT',
 'FEMALE_ENRL_2YR_TRANS_YR3_RT',
 'FEMALE_UNKN_ORIG_YR3_RT',
 'FEMALE_UNKN_4YR_TRANS_YR3_RT',
 'FEMALE_UNKN_2YR_TRANS_YR3_RT',
 'MALE_DEATH_YR3_RT',
 'MALE_COMP_ORIG_YR3_RT',
 'MALE_COMP_4YR_TRANS_YR3_RT',
 'MALE_COMP_2YR_TRANS_YR3_RT',
 'MALE_WDRAW_ORIG_YR3_RT',
 'MALE_WDRAW_4YR_TRANS_YR3_RT',
 'MALE_WDRAW_2YR_TRANS_YR3_RT',
 'MALE_ENRL_ORIG_YR3_RT',
 'MALE_ENRL_4YR_TRANS_YR3_RT',
 'MALE_ENRL_2YR_TRANS_YR3_RT',
 'MALE_UNKN_ORIG_YR3_RT',
 'MALE_UNKN_4YR_TRANS_YR3_RT',
 'MALE_UNKN_2YR_TRANS_YR3_RT',
 'PELL_DEATH_YR3_RT',
 'PELL_COMP_ORIG_YR3_RT',
 'PELL_COMP_4YR_TRANS_YR3_RT',
 'PELL_COMP_2YR_TRANS_YR3_RT',
 'PELL_WDRAW_ORIG_YR3_RT',
 'PELL_WDRAW_4YR_TRANS_YR3_RT',
 'PELL_WDRAW_2YR_TRANS_YR3_RT',
 'PELL_ENRL_ORIG_YR3_RT',
 'PELL_ENRL_4YR_TRANS_YR3_RT',
 'PELL_ENRL_2YR_TRANS_YR3_RT',
 'PELL_UNKN_ORIG_YR3_RT',
 'PELL_UNKN_4YR_TRANS_YR3_RT',
 'PELL_UNKN_2YR_TRANS_YR3_RT',
 'NOPELL_DEATH_YR3_RT',
 'NOPELL_COMP_ORIG_YR3_RT',
 'NOPELL_COMP_4YR_TRANS_YR3_RT',
 'NOPELL_COMP_2YR_TRANS_YR3_RT',
 'NOPELL_WDRAW_ORIG_YR3_RT',
 'NOPELL_WDRAW_4YR_TRANS_YR3_RT',
 'NOPELL_WDRAW_2YR_TRANS_YR3_RT',
 'NOPELL_ENRL_ORIG_YR3_RT',
 'NOPELL_ENRL_4YR_TRANS_YR3_RT',
 'NOPELL_ENRL_2YR_TRANS_YR3_RT',
 'NOPELL_UNKN_ORIG_YR3_RT',
 'NOPELL_UNKN_4YR_TRANS_YR3_RT',
 'NOPELL_UNKN_2YR_TRANS_YR3_RT',
 'LOAN_DEATH_YR3_RT',
 'LOAN_COMP_ORIG_YR3_RT',
 'LOAN_COMP_4YR_TRANS_YR3_RT',
 'LOAN_COMP_2YR_TRANS_YR3_RT',
 'LOAN_WDRAW_ORIG_YR3_RT',
 'LOAN_WDRAW_4YR_TRANS_YR3_RT',
 'LOAN_WDRAW_2YR_TRANS_YR3_RT',
 'LOAN_ENRL_ORIG_YR3_RT',
 'LOAN_ENRL_4YR_TRANS_YR3_RT',
 'LOAN_ENRL_2YR_TRANS_YR3_RT',
 'LOAN_UNKN_ORIG_YR3_RT',
 'LOAN_UNKN_4YR_TRANS_YR3_RT',
 'LOAN_UNKN_2YR_TRANS_YR3_RT',
 'NOLOAN_DEATH_YR3_RT',
 'NOLOAN_COMP_ORIG_YR3_RT',
 'NOLOAN_COMP_4YR_TRANS_YR3_RT',
 'NOLOAN_COMP_2YR_TRANS_YR3_RT',
 'NOLOAN_WDRAW_ORIG_YR3_RT',
 'NOLOAN_WDRAW_4YR_TRANS_YR3_RT',
 'NOLOAN_WDRAW_2YR_TRANS_YR3_RT',
 'NOLOAN_ENRL_ORIG_YR3_RT',
 'NOLOAN_ENRL_4YR_TRANS_YR3_RT',
 'NOLOAN_ENRL_2YR_TRANS_YR3_RT',
 'NOLOAN_UNKN_ORIG_YR3_RT',
 'NOLOAN_UNKN_4YR_TRANS_YR3_RT',
 'NOLOAN_UNKN_2YR_TRANS_YR3_RT',
 'FIRSTGEN_DEATH_YR3_RT',
 'FIRSTGEN_COMP_ORIG_YR3_RT',
 'FIRSTGEN_COMP_4YR_TRANS_YR3_RT',
 'FIRSTGEN_COMP_2YR_TRANS_YR3_RT',
 'FIRSTGEN_WDRAW_ORIG_YR3_RT',
 'FIRSTGEN_WDRAW_4YR_TRANS_YR3_RT',
 'FIRSTGEN_WDRAW_2YR_TRANS_YR3_RT',
 'FIRSTGEN_ENRL_ORIG_YR3_RT',
 'FIRSTGEN_ENRL_4YR_TRANS_YR3_RT',
 'FIRSTGEN_ENRL_2YR_TRANS_YR3_RT',
 'FIRSTGEN_UNKN_ORIG_YR3_RT',
 'FIRSTGEN_UNKN_4YR_TRANS_YR3_RT',
 'FIRSTGEN_UNKN_2YR_TRANS_YR3_RT',
 'NOT1STGEN_DEATH_YR3_RT',
 'NOT1STGEN_COMP_ORIG_YR3_RT',
 'NOT1STGEN_COMP_4YR_TRANS_YR3_RT',
 'NOT1STGEN_COMP_2YR_TRANS_YR3_RT',
 'NOT1STGEN_WDRAW_ORIG_YR3_RT',
 'NOT1STGEN_WDRAW_4YR_TRANS_YR3_RT',
 'NOT1STGEN_WDRAW_2YR_TRANS_YR3_RT',
 'NOT1STGEN_ENRL_ORIG_YR3_RT',
 'NOT1STGEN_ENRL_4YR_TRANS_YR3_RT',
 'NOT1STGEN_ENRL_2YR_TRANS_YR3_RT',
 'NOT1STGEN_UNKN_ORIG_YR3_RT',
 'NOT1STGEN_UNKN_4YR_TRANS_YR3_RT',
 'NOT1STGEN_UNKN_2YR_TRANS_YR3_RT',
 'DEATH_YR4_RT',
 'COMP_ORIG_YR4_RT',
 'COMP_4YR_TRANS_YR4_RT',
 'COMP_2YR_TRANS_YR4_RT',
 'WDRAW_ORIG_YR4_RT',
 'WDRAW_4YR_TRANS_YR4_RT',
 'WDRAW_2YR_TRANS_YR4_RT',
 'ENRL_ORIG_YR4_RT',
 'ENRL_4YR_TRANS_YR4_RT',
 'ENRL_2YR_TRANS_YR4_RT',
 'UNKN_ORIG_YR4_RT',
 'UNKN_4YR_TRANS_YR4_RT',
 'UNKN_2YR_TRANS_YR4_RT',
 'LO_INC_DEATH_YR4_RT',
 'LO_INC_COMP_ORIG_YR4_RT',
 'LO_INC_COMP_4YR_TRANS_YR4_RT',
 'LO_INC_COMP_2YR_TRANS_YR4_RT',
 'LO_INC_WDRAW_ORIG_YR4_RT',
 'LO_INC_WDRAW_4YR_TRANS_YR4_RT',
 'LO_INC_WDRAW_2YR_TRANS_YR4_RT',
 'LO_INC_ENRL_ORIG_YR4_RT',
 'LO_INC_ENRL_4YR_TRANS_YR4_RT',
 'LO_INC_ENRL_2YR_TRANS_YR4_RT',
 'LO_INC_UNKN_ORIG_YR4_RT',
 'LO_INC_UNKN_4YR_TRANS_YR4_RT',
 'LO_INC_UNKN_2YR_TRANS_YR4_RT',
 'MD_INC_DEATH_YR4_RT',
 'MD_INC_COMP_ORIG_YR4_RT',
 'MD_INC_COMP_4YR_TRANS_YR4_RT',
 'MD_INC_COMP_2YR_TRANS_YR4_RT',
 'MD_INC_WDRAW_ORIG_YR4_RT',
 'MD_INC_WDRAW_4YR_TRANS_YR4_RT',
 'MD_INC_WDRAW_2YR_TRANS_YR4_RT',
 'MD_INC_ENRL_ORIG_YR4_RT',
 'MD_INC_ENRL_4YR_TRANS_YR4_RT',
 'MD_INC_ENRL_2YR_TRANS_YR4_RT',
 'MD_INC_UNKN_ORIG_YR4_RT',
 'MD_INC_UNKN_4YR_TRANS_YR4_RT',
 'MD_INC_UNKN_2YR_TRANS_YR4_RT',
 'HI_INC_DEATH_YR4_RT',
 'HI_INC_COMP_ORIG_YR4_RT',
 'HI_INC_COMP_4YR_TRANS_YR4_RT',
 'HI_INC_COMP_2YR_TRANS_YR4_RT',
 'HI_INC_WDRAW_ORIG_YR4_RT',
 'HI_INC_WDRAW_4YR_TRANS_YR4_RT',
 'HI_INC_WDRAW_2YR_TRANS_YR4_RT',
 'HI_INC_ENRL_ORIG_YR4_RT',
 'HI_INC_ENRL_4YR_TRANS_YR4_RT',
 'HI_INC_ENRL_2YR_TRANS_YR4_RT',
 'HI_INC_UNKN_ORIG_YR4_RT',
 'HI_INC_UNKN_4YR_TRANS_YR4_RT',
 'HI_INC_UNKN_2YR_TRANS_YR4_RT',
 'DEP_DEATH_YR4_RT',
 'DEP_COMP_ORIG_YR4_RT',
 'DEP_COMP_4YR_TRANS_YR4_RT',
 'DEP_COMP_2YR_TRANS_YR4_RT',
 'DEP_WDRAW_ORIG_YR4_RT',
 'DEP_WDRAW_4YR_TRANS_YR4_RT',
 'DEP_WDRAW_2YR_TRANS_YR4_RT',
 'DEP_ENRL_ORIG_YR4_RT',
 'DEP_ENRL_4YR_TRANS_YR4_RT',
 'DEP_ENRL_2YR_TRANS_YR4_RT',
 'DEP_UNKN_ORIG_YR4_RT',
 'DEP_UNKN_4YR_TRANS_YR4_RT',
 'DEP_UNKN_2YR_TRANS_YR4_RT',
 'IND_DEATH_YR4_RT',
 'IND_COMP_ORIG_YR4_RT',
 'IND_COMP_4YR_TRANS_YR4_RT',
 'IND_COMP_2YR_TRANS_YR4_RT',
 'IND_WDRAW_ORIG_YR4_RT',
 'IND_WDRAW_4YR_TRANS_YR4_RT',
 'IND_WDRAW_2YR_TRANS_YR4_RT',
 'IND_ENRL_ORIG_YR4_RT',
 'IND_ENRL_4YR_TRANS_YR4_RT',
 'IND_ENRL_2YR_TRANS_YR4_RT',
 'IND_UNKN_ORIG_YR4_RT',
 'IND_UNKN_4YR_TRANS_YR4_RT',
 'IND_UNKN_2YR_TRANS_YR4_RT',
 'FEMALE_DEATH_YR4_RT',
 'FEMALE_COMP_ORIG_YR4_RT',
 'FEMALE_COMP_4YR_TRANS_YR4_RT',
 'FEMALE_COMP_2YR_TRANS_YR4_RT',
 'FEMALE_WDRAW_ORIG_YR4_RT',
 'FEMALE_WDRAW_4YR_TRANS_YR4_RT',
 'FEMALE_WDRAW_2YR_TRANS_YR4_RT',
 'FEMALE_ENRL_ORIG_YR4_RT',
 'FEMALE_ENRL_4YR_TRANS_YR4_RT',
 'FEMALE_ENRL_2YR_TRANS_YR4_RT',
 'FEMALE_UNKN_ORIG_YR4_RT',
 'FEMALE_UNKN_4YR_TRANS_YR4_RT',
 'FEMALE_UNKN_2YR_TRANS_YR4_RT',
 'MALE_DEATH_YR4_RT',
 'MALE_COMP_ORIG_YR4_RT',
 'MALE_COMP_4YR_TRANS_YR4_RT',
 'MALE_COMP_2YR_TRANS_YR4_RT',
 'MALE_WDRAW_ORIG_YR4_RT',
 'MALE_WDRAW_4YR_TRANS_YR4_RT',
 'MALE_WDRAW_2YR_TRANS_YR4_RT',
 'MALE_ENRL_ORIG_YR4_RT',

In [37]:
filtered_ranking_4_year_df = filtered_ranking_4_year_df[col_list]

In [38]:
filtered_ranking_4_year_df = filtered_ranking_4_year_df.fillna(0)
filtered_ranking_4_year_df

,Rank,INSTNM,ACCREDAGENCY,NPCURL,SCH_DEG,HCM2,PREDDEG,HIGHDEG,CONTROL,LOCALE,...,Student Population,Net Price,Average Grant Aid,Total Annual Cost,Alumni Salary,Acceptance Rate,SAT Lower,SAT Upper,ACT Lower,ACT Upper
0,456,University of Alabama at Birmingham,Southern Association of Colleges and Schools C...,https://uab.studentaidcalculator.com/survey.aspx,3.0,0,3,4,1,12.0,...,20902,17535,9254,36800,87200.0,92.0,990.0,1370.0,21.0,28.0
1,475,University of Alabama in Huntsville,Southern Association of Colleges and Schools C...,finaid.uah.edu/,3.0,0,3,4,1,12.0,...,9101,19986,9587,36881,103900.0,81.0,1080.0,1330.0,25.0,31.0
2,252,The University of Alabama,Southern Association of Colleges and Schools C...,financialaid.ua.edu/net-price-calculator/,3.0,0,3,4,1,12.0,...,38563,21973,16494,46744,97400.0,53.0,1050.0,1280.0,23.0,32.0
3,166,Auburn University,Southern Association of Colleges and Schools C...,https://www.auburn.edu/admissions/costcalc/fre...,3.0,0,3,4,1,13.0,...,29776,23416,9030,49954,104500.0,84.0,1130.0,1310.0,24.0,30.0
4,463,Birmingham-Southern College,Southern Association of Colleges and Schools C...,www.bsc.edu/fp/np-calculator.cfm,3.0,0,3,3,2,12.0,...,1325,22853,26594,52414,88300.0,62.0,1030.0,1260.0,23.0,29.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
634,118,Purdue University-Main Campus,Higher Learning Commission,https://www.purdue.edu/dfa/cost/estimator.html,3.0,0,3,4,1,13.0,...,42699,13746,10703,41614,110000.0,57.0,1150.0,1380.0,25.0,31.0
635,577,St. John's College,Higher Learning Commission,www.sjc.edu/admissions-and-aid/financial-aid/n...,3.0,0,3,4,2,41.0,...,386,20605,31845,65456,0.0,63.0,1190.0,1350.0,23.0,32.0
636,277,New College of Florida,Southern Association of Colleges and Schools C...,www.ncf.edu/admissions/cost-and-aid/tuition-an...,3.0,0,3,4,1,13.0,...,885,10248,9341,43678,86500.0,69.0,1190.0,1380.0,25.0,30.0
637,519,Florida Gulf Coast University,Southern Association of Colleges and Schools C...,https://www2.fgcu.edu/financialaid/netpricecal...,3.0,0,3,4,1,21.0,...,15317,15376,4726,39434,80000.0,64.0,1060.0,1210.0,21.0,25.0
638,505,University of North Georgia,Southern Association of Colleges and Schools C...,ung.edu/financial-aid/net-calculator.php,3.0,0,3,4,1,31.0,...,20811,9854,5483,28094,85600.0,78.0,910.0,1130.0,20.0,25.0

In [39]:
filtered_ranking_4_year_df['Rank'].dtype

dtype('int64')

In [40]:
#I need to bin the school ranks into bins of 10% each
filtered_ranking_4_year_df['Rank'].describe()

count    639.000000
mean     327.456964
std      186.244600
min        1.000000
25%      167.500000
50%      328.000000
75%      487.500000
max      650.000000
Name: Rank, dtype: float64

In [41]:
filtered_ranking_4_year_df['10%_cut'] = pd.qcut(filtered_ranking_4_year_df['Rank'], q=10, labels = False)

In [42]:
filtered_ranking_4_year_df['5%_cut'] = pd.qcut(filtered_ranking_4_year_df['Rank'], q=20, labels = False)

In [43]:
filtered_ranking_4_year_df['20%_cut'] = pd.qcut(filtered_ranking_4_year_df['Rank'], q=5, labels = False)

In [44]:
filtered_ranking_4_year_df['50%_cut'] = pd.qcut(filtered_ranking_4_year_df['Rank'], q=2, labels = False)

In [45]:
filtered_ranking_4_year_df

,Rank,INSTNM,ACCREDAGENCY,NPCURL,SCH_DEG,HCM2,PREDDEG,HIGHDEG,CONTROL,LOCALE,...,Alumni Salary,Acceptance Rate,SAT Lower,SAT Upper,ACT Lower,ACT Upper,10%_cut,5%_cut,20%_cut,50%_cut
0,456,University of Alabama at Birmingham,Southern Association of Colleges and Schools C...,https://uab.studentaidcalculator.com/survey.aspx,3.0,0,3,4,1,12.0,...,87200.0,92.0,990.0,1370.0,21.0,28.0,7,14,3,1
1,475,University of Alabama in Huntsville,Southern Association of Colleges and Schools C...,finaid.uah.edu/,3.0,0,3,4,1,12.0,...,103900.0,81.0,1080.0,1330.0,25.0,31.0,7,14,3,1
2,252,The University of Alabama,Southern Association of Colleges and Schools C...,financialaid.ua.edu/net-price-calculator/,3.0,0,3,4,1,12.0,...,97400.0,53.0,1050.0,1280.0,23.0,32.0,3,7,1,0
3,166,Auburn University,Southern Association of Colleges and Schools C...,https://www.auburn.edu/admissions/costcalc/fre...,3.0,0,3,4,1,13.0,...,104500.0,84.0,1130.0,1310.0,24.0,30.0,2,4,1,0
4,463,Birmingham-Southern College,Southern Association of Colleges and Schools C...,www.bsc.edu/fp/np-calculator.cfm,3.0,0,3,3,2,12.0,...,88300.0,62.0,1030.0,1260.0,23.0,29.0,7,14,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
634,118,Purdue University-Main Campus,Higher Learning Commission,https://www.purdue.edu/dfa/cost/estimator.html,3.0,0,3,4,1,13.0,...,110000.0,57.0,1150.0,1380.0,25.0,31.0,1,3,0,0
635,577,St. John's College,Higher Learning Commission,www.sjc.edu/admissions-and-aid/financial-aid/n...,3.0,0,3,4,2,41.0,...,0.0,63.0,1190.0,1350.0,23.0,32.0,8,17,4,1
636,277,New College of Florida,Southern Association of Colleges and Schools C...,www.ncf.edu/admissions/cost-and-aid/tuition-an...,3.0,0,3,4,1,13.0,...,86500.0,69.0,1190.0,1380.0,25.0,30.0,4,8,2,0
637,519,Florida Gulf Coast University,Southern Association of Colleges and Schools C...,https://www2.fgcu.edu/financialaid/netpricecal...,3.0,0,3,4,1,21.0,...,80000.0,64.0,1060.0,1210.0,21.0,25.0,7,15,3,1
638,505,University of North Georgia,Southern Association of Colleges and Schools C...,ung.edu/financial-aid/net-calculator.php,3.0,0,3,4,1,31.0,...,85600.0,78.0,910.0,1130.0,20.0,25.0,7,15,3,1

In [46]:
#lets output this data file and run a neural network model on the dataset to see if it is better than randomforest.
filtered_ranking_4_year_df.to_csv(path2 + 'filtered_ranking_4_year_df.csv')

In [47]:
#now we are going to cut the columns on this model down to what is in the forbes formula
#20% rank on Forbes 2018 Top Colleges ranking + 20% student debt + 20% alumni earnings
#+ 20% net price + 10% graduation rate + 10% Pell Grant recipients.
#student debt
#GRAD_DEBT_MDN = The median debt for students who have completed
#GRAD_DEBT_MDN10YR = Median loan debt of completers in monthly payments (10-year amortization plan)
#DEP_DEBT_MDN = The median debt for dependent students
#IND_DEBT_MDN = The median debt for independent students
#alumni earnings
#MN_EARN_WNE_P6 = Mean earnings of students working and not enrolled 6 years after entry
#MN_EARN_WNE_P7 = Mean earnings of students working and not enrolled 7 years after entry
#MN_EARN_WNE_P8 = Mean earnings of students working and not enrolled 8 years after entry
#MN_EARN_WNE_P10 = Mean earnings of students working and not enrolled 10 years after entry
#net price
#NPT4_PUB = Average net price for Title IV institutions (public institutions)
#NPT4_PRIV = Average net price for Title IV institutions (private for-profit and nonprofit institutions)
#graduation percentage
#OVERALL_YR6_N = Number of students in overall 6-year completion cohort
#UGDS = Enrollment of all undergraduate students

In [48]:
forbes_ranking_df = filtered_ranking_4_year_df[['Rank','UGDS','INSTNM','GRAD_DEBT_MDN', 'GRAD_DEBT_MDN10YR', 'MN_EARN_WNE_P6', 'MN_EARN_WNE_P7', 'MN_EARN_WNE_P8', 'MN_EARN_WNE_P10', 'NPT4_PUB', 'NPT4_PRIV', 'OVERALL_YR6_N','UG', '10%_cut', '20%_cut', '50%_cut']]

In [49]:
forbes_ranking_df[['OVERALL_YR6_N', 'UGDS']]

    OVERALL_YR6_N     UGDS
0            2590  13186.0
1            1129   7458.0
2            4369  32177.0
3            2847  24147.0
4             245   1265.0
..            ...      ...
634          5421  33495.0
635           111    320.0
636           128    808.0
637          2442  13639.0
638          3818  17661.0

[639 rows x 2 columns]

In [50]:
forbes_ranking_df

,Rank,UGDS,INSTNM,GRAD_DEBT_MDN,GRAD_DEBT_MDN10YR,MN_EARN_WNE_P6,MN_EARN_WNE_P7,MN_EARN_WNE_P8,MN_EARN_WNE_P10,NPT4_PUB,NPT4_PRIV,OVERALL_YR6_N,UG,10%_cut,20%_cut,50%_cut
0,456,13186.0,University of Alabama at Birmingham,22500,233.511936049938,39400,40000,44100,48400,17005.0,0.0,2590,0.0,7,3,1
1,475,7458.0,University of Alabama in Huntsville,22021,228.540726389142,40300,43400,45900,52000,20909.0,0.0,1129,0.0,7,3,1
2,252,32177.0,The University of Alabama,23250,241.295667251603,42400,41700,45600,51600,22232.0,0.0,4369,0.0,3,1,0
3,166,24147.0,Auburn University,21000,217.944473646609,43100,44100,50800,56300,23696.0,0.0,2847,0.0,2,1,0
4,463,1265.0,Birmingham-Southern College,26000,269.83601499104,36700,35600,43500,53100,0.0,25494.0,245,0.0,7,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
634,118,33495.0,Purdue University-Main Campus,19500,202.37701124328,49000,50600,55700,62200,12527.0,0.0,5421,0.0,1,0,0
635,577,320.0,St. John's College,27000,280.214323259926,26400,27600,38600,41400,0.0,40973.0,111,0.0,8,4,1
636,277,808.0,New College of Florida,16000,166.052932302178,26000,0,36900,0,7991.0,0.0,128,0.0,4,2,0
637,519,13639.0,Florida Gulf Coast University,19500,202.37701124328,36500,37400,44000,45800,13745.0,0.0,2442,0.0,7,3,1
638,505,17661.0,University of North Georgia,18000,186.809548839951,37300,0,43900,46200,9994.0,0.0,3818,0.0,7,3,1

In [51]:
conditional = ((forbes_ranking_df['NPT4_PUB'] == 0) & (forbes_ranking_df['NPT4_PRIV'] == 0)) | \
(forbes_ranking_df[['MN_EARN_WNE_P6','MN_EARN_WNE_P7','MN_EARN_WNE_P8','MN_EARN_WNE_P10']].astype('int').sum(axis=1) == 0)
forbes_ranking_df = forbes_ranking_df.loc[~ conditional, :]

In [52]:
forbes_ranking_df

,Rank,UGDS,INSTNM,GRAD_DEBT_MDN,GRAD_DEBT_MDN10YR,MN_EARN_WNE_P6,MN_EARN_WNE_P7,MN_EARN_WNE_P8,MN_EARN_WNE_P10,NPT4_PUB,NPT4_PRIV,OVERALL_YR6_N,UG,10%_cut,20%_cut,50%_cut
0,456,13186.0,University of Alabama at Birmingham,22500,233.511936049938,39400,40000,44100,48400,17005.0,0.0,2590,0.0,7,3,1
1,475,7458.0,University of Alabama in Huntsville,22021,228.540726389142,40300,43400,45900,52000,20909.0,0.0,1129,0.0,7,3,1
2,252,32177.0,The University of Alabama,23250,241.295667251603,42400,41700,45600,51600,22232.0,0.0,4369,0.0,3,1,0
3,166,24147.0,Auburn University,21000,217.944473646609,43100,44100,50800,56300,23696.0,0.0,2847,0.0,2,1,0
4,463,1265.0,Birmingham-Southern College,26000,269.83601499104,36700,35600,43500,53100,0.0,25494.0,245,0.0,7,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
634,118,33495.0,Purdue University-Main Campus,19500,202.37701124328,49000,50600,55700,62200,12527.0,0.0,5421,0.0,1,0,0
635,577,320.0,St. John's College,27000,280.214323259926,26400,27600,38600,41400,0.0,40973.0,111,0.0,8,4,1
636,277,808.0,New College of Florida,16000,166.052932302178,26000,0,36900,0,7991.0,0.0,128,0.0,4,2,0
637,519,13639.0,Florida Gulf Coast University,19500,202.37701124328,36500,37400,44000,45800,13745.0,0.0,2442,0.0,7,3,1
638,505,17661.0,University of North Georgia,18000,186.809548839951,37300,0,43900,46200,9994.0,0.0,3818,0.0,7,3,1

In [53]:
graduation_rate = (forbes_ranking_df['OVERALL_YR6_N'].astype('int') / forbes_ranking_df['UGDS'].astype('int'))

In [54]:
while((graduation_rate.max()) != 1):
    graduation_rate.replace(to_replace = graduation_rate.max(),value = 1., inplace = True)

In [90]:
forbes_ranking_df.loc[:,'debt'] = forbes_ranking_df['GRAD_DEBT_MDN'].copy().astype('int').copy()
forbes_ranking_df.loc[:,'earning_average'] = forbes_ranking_df[['MN_EARN_WNE_P6','MN_EARN_WNE_P7','MN_EARN_WNE_P8','MN_EARN_WNE_P10']].astype('int').sum(axis=1).copy()
forbes_ranking_df.loc[:,'net_tuition'] = forbes_ranking_df[['NPT4_PUB', 'NPT4_PRIV']].max(axis=1).copy()
debt = forbes_ranking_df['debt']
earning_average = forbes_ranking_df['earning_average']
net_tuition  =forbes_ranking_df['net_tuition']

In [91]:
forbes_ranking_df.loc[:,'calculation'] = -0.25 * (debt / debt.max()) + 0.25 * (earning_average / earning_average.max()) - 0.25 * (net_tuition / net_tuition.max()) + 0.25 * (graduation_rate / graduation_rate.max())

In [93]:
forbes_ranking_df.loc[:,'calculation_ng'] = -0.33 * (debt / debt.max()) + 0.33 * (earning_average / earning_average.max()) - 0.33 * (net_tuition / net_tuition.max())

In [58]:
forbes_ranking_df['calculation'].min()

-0.38952525342777133

In [59]:
forbes_ranking_df['calculation']

0     -0.154429
1     -0.177975
2     -0.199916
3     -0.186356
4     -0.233239
         ...
634   -0.090107
635   -0.305071
636   -0.112089
637   -0.118973
638   -0.094134
Name: calculation, Length: 633, dtype: float64

In [72]:
forbes_ranking_sorted_calc_df = forbes_ranking_df.sort_values(by = 'calculation', ascending = False)

In [73]:
forbes_ranking_sorted_calc_df = forbes_ranking_sorted_calc_df.reset_index().reset_index().drop(columns = 'index').rename(columns = {'level_0':'calculation_rank'})
forbes_ranking_sorted_calc_df

,calculation_rank,Rank,UGDS,INSTNM,GRAD_DEBT_MDN,GRAD_DEBT_MDN10YR,MN_EARN_WNE_P6,MN_EARN_WNE_P7,MN_EARN_WNE_P8,MN_EARN_WNE_P10,...,OVERALL_YR6_N,UG,10%_cut,20%_cut,50%_cut,debt,earning_average,net_tuition,calculation,calculation_ng
0,0,70,2912.0,University of Florida-Online,16247,168.616374444593,47700,0,57800,65700,...,5183,0.0,0,0,0,16247,171200,8390.0,0.147410,-0.135419
1,1,330,937.0,St. Joseph's College-New York,19500,202.37701124328,41600,48200,47200,53900,...,1201,0.0,5,2,1,19500,190900,16769.0,0.083231,-0.220135
2,2,2,7083.0,Stanford University,11341,117.700394077438,92800,98600,121400,141300,...,579,0.0,0,0,0,11341,454100,12265.0,0.079013,0.077321
3,3,464,1630.0,Berea College,5600,58.1185263057625,27100,29200,32100,36300,...,476,0.0,7,3,1,5600,124700,1964.0,0.075098,0.002761
4,4,270,1548.0,College of the Ozarks,0,0,28800,30600,33100,35300,...,359,0.0,4,2,0,0,127800,9380.0,0.069989,0.015855
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
628,628,85,2785.0,Oberlin College,26000,269.83601499104,30700,31700,41300,45500,...,370,0.0,1,0,0,26000,149200,35555.0,-0.312899,-0.456868
629,629,428,4498.0,High Point University,26000,269.83601499104,38000,35800,40700,42900,...,826,0.0,6,3,1,26000,157400,38877.0,-0.314231,-0.475386
630,630,112,1994.0,Rhode Island School of Design,27000,280.214323259926,42600,38100,49200,56400,...,275,0.0,1,0,0,27000,186300,42484.0,-0.339733,-0.493959
631,631,328,3591.0,Pratt Institute-Main,25839,268.165107359749,40200,36900,43200,48900,...,617,0.0,4,2,0,25839,169200,45559.0,-0.346317,-0.513839
632,632,163,511.0,Manhattan School of Music,26243,272.357943900379,23700,24200,37000,40700,...,55,0.0,2,1,0,26243,125600,45952.0,-0.389525,-0.549692

In [75]:
forbes_ranking_sorted_calc_df_top_50 = forbes_ranking_sorted_calc_df.sort_values(by = 'Rank', ascending = True).head(50)
forbes_ranking_sorted_calc_df_top_50

,calculation_rank,Rank,UGDS,INSTNM,GRAD_DEBT_MDN,GRAD_DEBT_MDN10YR,MN_EARN_WNE_P6,MN_EARN_WNE_P7,MN_EARN_WNE_P8,MN_EARN_WNE_P10,...,OVERALL_YR6_N,UG,10%_cut,20%_cut,50%_cut,debt,earning_average,net_tuition,calculation,calculation_ng
8,8,1,7582.0,Harvard University,13875,143.999027230795,91300,113600,123700,139100,...,614,0.0,0,0,0,13875,467700,15561.0,0.045546,0.033396
2,2,2,7083.0,Stanford University,11341,117.700394077438,92800,98600,121400,141300,...,579,0.0,0,0,0,11341,454100,12265.0,0.079013,0.077321
19,19,3,5963.0,Yale University,13000,134.91800749552,67800,93200,97100,124400,...,384,0.0,0,0,0,13000,382500,18770.0,-0.010472,-0.035074
5,5,4,4550.0,Massachusetts Institute of Technology,12500,129.728853361077,99600,122900,130700,153600,...,503,0.0,0,0,0,12500,506800,18278.0,0.069410,0.055140
6,6,5,5301.0,Princeton University,9850,102.226336448528,73600,89600,92400,116300,...,273,0.0,0,0,0,9850,371900,9749.0,0.057567,0.058994
49,49,6,10764.0,University of Pennsylvania,19500,202.37701124328,91200,102200,107800,131600,...,1213,0.0,0,0,0,19500,432800,25033.0,-0.064229,-0.121970
209,209,7,6752.0,Brown University,15500,160.863778167735,64800,65600,76500,89100,...,668,0.0,0,0,0,15500,296000,31685.0,-0.136529,-0.212866
23,23,8,948.0,California Institute of Technology,8700,90.2912819393097,68500,66900,105700,106300,...,41,0.0,0,0,0,8700,347400,23820.0,-0.023126,-0.044798
13,13,9,6596.0,Duke University,11500,119.350545092191,93200,95000,103200,114500,...,850,0.0,0,0,0,11500,405900,23442.0,0.004825,-0.036157
74,74,10,4312.0,Dartmouth College,12500,129.728853361077,74600,79400,94000,110200,...,390,0.0,0,0,0,12500,358200,31449.0,-0.080575,-0.136206
81,81,11,15105.0,Cornell University,14000,145.296315764406,76300,78500,86300,101200,...,1899,0.0,0,0,0,14000,342300,30494.0,-0.087459,-0.156933
20,20,12,1549.0,Pomona College,10040,104.198215019617,51200,51000,66900,77300,...,124,0.0,0,0,0,10040,246400,13622.0,-0.019927,-0.052721
32,32,13,30845.0,University of California-Berkeley,13750,142.701738697184,57600,57600,68100,79000,...,3950,0.0,0,0,0,13750,262300,14846.0,-0.039029,-0.093778
83,83,14,8216.0,Columbia University in the City of New York,21979,228.104837441849,77900,89100,95500,115600,...,1213,0.0,0,0,0,21979,378100,22637.0,-0.091014,-0.168859
52,52,15,7089.0,Georgetown University,15397,159.79481241604,81100,95600,101400,125200,...,914,0.0,0,0,0,15397,403300,30169.0,-0.066955,-0.130928
92,92,16,6600.0,University of Chicago,17000,176.431240571064,72100,80500,89700,103000,...,651,0.0,0,0,0,17000,345300,26160.0,-0.095279,-0.158319
58,58,17,8451.0,Northwestern University,15000,155.674624033292,71900,73300,82800,93400,...,1271,0.0,0,0,0,15000,321400,24840.0,-0.069542,-0.141426
253,253,18,8568.0,University of Notre Dame,19000,197.187857108837,69700,70700,74700,98400,...,1147,0.0,0,0,0,19000,313500,32096.0,-0.151858,-0.244630
61,61,19,2028.0,Williams College,12702,131.825271631392,51400,56100,60000,89800,...,230,0.0,0,0,0,12702,257300,21239.0,-0.070817,-0.130905
60,60,20,30079.0,University of Michigan-Ann Arbor,16606,172.342187113123,55900,61500,68200,79000,...,3647,0.0,0,0,0,16606,264600,16010.0,-0.070786,-0.133449
35,35,21,3962.0,Rice University,11989,124.425537835676,68300,66600,74800,91600,...,405,0.0,0,0,0,11989,301300,20879.0,-0.043747,-0.091479
116,116,22,5567.0,Johns Hopkins University,15500,160.863778167735,68000,69300,78400,89300,...,982,0.0,0,0,0,15500,305000,30701.0,-0.107370,-0.199939
331,331,23,886.0,Harvey Mudd College,22960,238.285957853626,87200,68100,99300,104200,...,104,0.0,0,0,0,22960,358800,32739.0,-0.171596,-0.265243
261,261,25,1544.0,Swarthmore College,20000,207.566165377723,44500,50700,56800,70000,...,156,0.0,0,0,0,20000,222000,21067.0,-0.153903,-0.236494
96,96,26,1825.0,Bowdoin College,15850,164.496186061845,57100,55600,62700,83300,...,211,0.0,0,0,0,15850,258700,21300.0,-0.097304,-0.166595
64,64,27,6840.0,Vanderbilt University,15000,155.674624033292,61900,65500,78000,86200,...,594,0.0,0,0,0,15000,291600,20253.0,-0.075175,-0.127889
76,76,28,1855.0,Amherst College,12896,133.838663435556,61600,66700,64800,83300,...,230,0.0,0,0,0,12896,276400,25208.0,-0.082033,-0.149200
75,75,29,1318.0,Claremont McKenna College,14250,147.890892831628,68200,66800,80600,93200,...,107,0.0,0,0,0,14250,308800,23889.0,-0.081359,-0.134185
276,276,30,19548.0,University of Southern California,19500,202.37701124328,61400,68800,76900,88800,...,2489,0.0,0,0,0,19500,295900,30453.0,-0.157588,-0.250035
160,160,31,7356.0,Washington University in St Louis,16075,166.831305422345,63400,65700,78500,87900,...,592,0.0,0,0,0,16075,295500,27427.0,-0.123228,-0.189218
121,121,33,16405.0,University of Virginia-Main Campus,17756,184.277241622342,56800,60500,65300,79400,...,1693,0.0,0,0,0,17756,262000,20281.0,-0.109825,-0.179025
192,192,34,5597.0,Tufts University,16500,171.242086436621,56600,63500,84800,103300,...,708,0.0,0,0,0,16500,308200,31485.0,-0.131235,-0.214973
578,578,35,26339.0,New York University,21250,220.539050713831,55900,59300,68700,78600,...,3973,0.0,0,0,0,21250,262500,42397.0,-0.248397,-0.377662
156,156,36,2550.0,Middlebury College,13750,142.701738697184,47900,56300,61500,71900,...,201,0.0,0,0,0,13750,237600,25587.0,-0.121958,-0.186997
332,332,37,6483.0,Carnegie Mellon University,23250,241.295667251603,84000,82200,92200,103000,...,778,0.0,0,0,0,23250,361400,32674.0,-0.171827,-0.266414
43,43,38,31568.0,University of California-Los Angeles,15000,155.674624033292,52000,54900,63900,73200,...,4641,0.0,0,0,0,15000,244000,14171.0,-0.050523,-0.115206
143,143,39,1832.0,Bates College,12725,132.063972721576,46000,50400,56200,74300,...,190,0.0,0,0,0,12725,226900,26477.0,-0.116936,-0.188580
299,299,40,2922.0,Wesleyan University,17231,178.828629781177,46400,41100,53500,63400,...,346,0.0,0,0,0,17231,204400,26291.0,-0.162563,-0.253660
228,228,41,9639.0,Boston College,16939,175.798163766662,64900,72500,82200,92500,...,1307,0.0,0,0,0,16939,312100,33562.0,-0.142156,-0.232393
235,235,42,1822.0,Washington and Lee University,19500,202.37701124328,58900,69600,74700,93300,...,178,0.0,0,0,0,19500,296500,27083.0,-0.146366,-0.225443
47,47,44,2392.0,Wellesley College,10600,110.010067650193,48600,52800,59700,71800,...,341,0.0,0,0,0,10600,232900,22247.0,-0.062758,-0.129884
53,53,45,18946.0,University of North Carolina at Chapel Hill,16118,167.277572677907,49900,54900,60800,68800,...,2507,0.0,0,0,0,16118,234400,13918.0,-0.067286,-0.132484
200,200,46,2934.0,Colgate University,16125,167.350220835789,54300,55300,64100,81100,...,258,0.0,0,0,0,16125,254800,26041.0,-0.134335,-0.206341
113,113,47,6349.0,William & Mary,18325,190.182499027339,47400,51700,60100,74500,...,686,0.0,0,0,0,18325,233700,16383.0,-0.106318,-0.175995
227,227,48,1839.0,Davidson College,18519,192.195890831503,49400,47700,63400,71100,...,187,0.0,0,0,0,18519,231600,22109.0,-0.141785,-0.220712
250,250,49,1305.0,Haverford College,15000,155.674624033292,44100,56000,52200,75100,...,128,0.0,0,0,0,15000,227400,28799.0,-0.150528,-0.231065
311,311,50,2557.0,Barnard College,17500,181.620394705508,52800,51200,63800,69700,...,286,0.0,0,0,0,17500,237500,29184.0,-0.165956,-0.255973
269,269,52,2046.0,Carleton College,13834,143.573516591771,43400,47500,52500,67900,...,200,0.0,0,0,0,13834,211300,30210.0,-0.156082,-0.238286
387,387,54,1072.0,Pitzer College,14625,151.78275843246,37300,34100,43900,51500,...,126,0.0,0,0,0,14625,166800,31590.0,-0.187479,-0.286260
109,109,55,6975.0,Emory University,18000,186.809548839951,65500,68600,72300,84400,...,1165,0.0,0,0,0,18000,290800,24593.0,-0.105244,-0.194041

In [76]:
forbes_ranking_sorted_calc_df_top_50.to_csv(path2+'forbes_ranking_sorted_calc_df_top_50.csv')

In [63]:
forbes_ranking_sorted_calc_df.to_csv(path2+'forbes_ranking_check.csv')

PermissionError: [Errno 13] Permission denied: './data_documentation/forbes_ranking_check.csv'

In [ ]:
graduation_rate_new = pd.Series(dtype = 'float64')
for rate in graduation_rate:
    if rate > 1:
        graduation_rate_new.append(1.)
    else:
        graduation_rate_new.append(float(rate))

In [ ]:
graduation_rate_new.max()

In [ ]:
forbes_ranking_df

In [ ]:
earning_sum = forbes_ranking_df.loc[:,['MN_EARN_WNE_P6','MN_EARN_WNE_P7','MN_EARN_WNE_P8','MN_EARN_WNE_P10']].astype('int').sum(axis = 1)

In [ ]:
forbes_ranking_df[['MN_EARN_WNE_P6','MN_EARN_WNE_P7','MN_EARN_WNE_P8','MN_EARN_WNE_P10']]

In [ ]:
forbes_ranking_df['UGDS']

In [ ]:
(forbes_ranking_df['OVERALL_YR6_N'].astype('int') / forbes_ranking_df['UGDS'].astype('int'))

In [ ]:
#begin randomforest classifier work
X = filtered_ranking_4_year_df.drop(columns = ['Rank', '10%_cut', '5%_cut', '20%_cut', '50%_cut'])
column_list = X.columns.to_list()

In [ ]:
# here we need to choose either 10%_cut or 5%_cut.  Choose 10% first then redo with 5%
y = filtered_ranking_4_year_df['10%_cut']
y

In [ ]:
print(X.shape, y.shape)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = .4)

In [ ]:
# random forest generator classifier
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rf = RandomForestClassifier()
rf_a = rf.fit(X_train, y_train)
rf_a.score(X_test, y_test)

In [ ]:
# We can sort the features by their importance
importance_a = sorted(zip(rf_a.feature_importances_, column_list), reverse=True)
importance_a

In [ ]:
column_list_b = []
for tuple in importance_a:
    if tuple[0] > .01:
        column_list_b.append(tuple[1])
X_a = X[column_list_b]

In [ ]:
X_a

In [ ]:
rf_a.base_estimator_

In [ ]:
# Create the RandomizedSearchCV model
from sklearn.model_selection import RandomizedSearchCV# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 100, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
#criterion
criterion = ['gini', 'entropy']
# Maximum number of levels in tree
ccp_alpha = [0., 2., 3., 4., 5.]
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
#impurity decrease
impurity_decrease = [0, 1, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4, 8]
# Method of selecting samples for training each tree
bootstrap = [True, False]# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'criterion' : criterion,
               'ccp_alpha' : ccp_alpha,
               'min_impurity_decrease' : impurity_decrease,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap,
                'oob_score': [True, False]}
random_grid

In [ ]:
rf_random = RandomizedSearchCV(estimator = rf_a, param_distributions = random_grid, cv = 3, verbose = 2, n_iter = 200,  n_jobs = -1)

In [ ]:
rf_random.fit(X_train, y_train)

In [ ]:
rf_random.score(X_test, y_test)

In [ ]:
rf_random.best_params_

In [ ]:
# here we need to choose either 10%_cut or 5%_cut.  Choose 10% first then redo with 5%
y_a = filtered_ranking_4_year_df['10%_cut']
y_a

In [ ]:
X = X_a
y = y_a
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [ ]:
rf_a = rf.fit(X_train, y_train)
rf_a.score(X_test, y_test)

In [ ]:
# Random Forests in sklearn will automatically calculate feature importance
importances = rf_a.feature_importances_
importances

In [ ]:
# We can sort the features by their importance
importance_b = sorted(zip(rf.feature_importances_, column_list), reverse=True)
importance_b